### PR TITLE
Fix bug where CHARMM impropers did not respect toroidal boundary conditions

### LINKED ISSUE #1760: CHARMM reader produces incorrect improper energies
[`CharmmPsfFile`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/charmmpsffile.py) uses [this code](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/charmmpsffile.py#L910) to encode CHARMM improper torsions:
```python
        # Ick. OpenMM does not have an improper torsion class. Need to
        # construct one from CustomTorsionForce
        force = mm.CustomTorsionForce('k*(theta-theta0)^2')
```
Given that OpenMM computes [the torsion `theta` on the domain `[-pi,pi]`](http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.openmm.CustomTorsionForce.html#simtk.openmm.openmm.CustomTorsionForce), guess what happens when `theta0` is not 0?

### PR DESCRIPTION
**Pull request by jchodera**
Fixes #1760.

This is a major bug that affects the reading of CHARMM files, and can cause anything from subtle incorrect simulations to major explosions. Recommend bugfix point release after merging.

### CODE REVIEW

**Comment by swails** [comment]
Looks like parmed needs the same fix

**Comment by jchodera** [comment]
Whoops, I'm not sure why this pulled in a stray `README.md` change.

**Comment by jchodera** [comment]
Though we actually *want* that README change. It must have been neglected in another PR.

**Comment by jchodera** [comment]
Actually, we should also change the [problematic `CustomTorsionForce` example that led to this issue](http://docs.openmm.org/7.1.0/api-python/generated/simtk.openmm.openmm.CustomTorsionForce.html#simtk.openmm.openmm.CustomTorsionForce) too.

**Comment by peastman** [comment]
Thanks for catching this!  Would it be possible to add a test case?  Your fix looks reasonable to me, but it's just complicated enough that I'd feel more comfortable if something were verifying it.

**Comment by jchodera** [comment]
> Thanks for catching this! Would it be possible to add a test case? Your fix looks reasonable to me, but it's just complicated enough that I'd feel more comfortable if something were verifying it.

I've been trying to think of what a good test case might be. We noticed this because a system we prepared through the CHARMM-GUI containing spin labels had utterly bizarre behavior, and by turning off a force at a time, noticed the `CustomTorsionForce` was responsible and specific impropers in the `CYR1` residue (defined in `toppar_all36_label_spin.str`) with 180-degree reference angles were to blame:
```
IMPROPER
CTS1 CES1 CES1 CTS3    200.00   0   180.00 ! X X X P 2  !from Benoit
CTS1 CES1 CES1 CTS2    200.00   0   180.00 ! - - - - 0
CTS1 CES1 CES1 HES1    200.00   0   180.00 ! X X X P 1
```
What would a minimal test case be? I suppose I could craft an artificial system of four atoms with artificial `IMPROPER` entry, but what's the correct way to test this without introducing a lot of external machinery to perform a torsion drive and compute energies to validate against?

**Comment by peastman** [comment]
How about just manually putting the atoms into a few positions and verifying the energies are correct for them?

**Comment by peastman** [comment]
What's the status on this?

**Comment by jchodera** [comment]
Sorry for letting this slip. There was enough effort required to produce the customized test you suggested (configurations, CHARMM input files, reference energies) that I thought it might actually be *easier* (and much more useful) to add a Lepton expression for computing minimum-image angular differences and their derivatives as an alternative to the current hack. I managed to figure out that this seemed to be straightforward, but haven't actually started that coding yet.

**Comment by swails** [comment]
What functional form does CHARMM use?  Is it not what you implemented here?

**Comment by jchodera** [comment]
CHARMM uses a simple harmonic form, but the harmonic restraint must be centered on the reference improper torsion angle.

Some CHARMM parameter sets (such as EPR spin probe dyes) define the reference torsion angle to be 180 degrees, e.g.:
```
IMPROPER
CTS1 CES1 CES1 CTS3    200.00   0   180.00 ! X X X P 2  !from Benoit
CTS1 CES1 CES1 CTS2    200.00   0   180.00 ! - - - - 0
CTS1 CES1 CES1 HES1    200.00   0   180.00 ! X X X P 1
```
In this case, the [-180, +180] torsion domain used by OpenMM becomes problematic because the naive torsion expression `(K/2)*(theta-theta0)^2` uses a torsion deviation `(theta-theta0)` that is not the minimum-image torsion deviation about `theta0`.

**Comment by jchodera** [comment]
I suppose we could use the simpler expression
```
(K*2)*min(dtheta^2, (2*pi-dtheta)^2); dtheta = abs(theta-theta0);
```

instead?

**Comment by swails** [comment]
> There was enough effort required to produce the customized test you suggested (configurations, CHARMM input files, reference energies) that I thought it might actually be easier (and much more useful) to add a Lepton expression for computing minimum-image angular differences and their derivatives as an alternative to the current hack. I managed to figure out that this seemed to be straightforward, but haven't actually started that coding yet.

How does that eliminate the need for the test?  If this new expression works, why not just use it?

And why can't you just turn the system you found this issue on into the test case?  Or if it's too large, shave it down a little?

**Comment by jchodera** [comment]
> How does that eliminate the need for the test?

It doesn't eliminate the need for *a* test, but it could change what we're testing. If we implement `minimum_image_deviation(theta,theta0)` in lepton, we could test that instead, which is easier.

Arguably, we are missing some key things from our CHARMM validation suite as well, but that probably extends far beyond this particular term and should probably be tackled separately (e.g. by automating the tests we did for the OpenMM 7 paper).

> If this new expression works, why not just use it?

...because spending some time discussing the best approach to fixing this issue and what deeper implications this issue has in the first place is maybe better than merging in the first hacky fix that came to mind? 

For example, our [OpenMM 6.3.0 release also has this bug](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/charmmpsffile.py#L910) but doesn't support some lepton operations that this fix uses, but I think *does* support the alternative:
```
(K*2)*min(dtheta^2, (2*pi-dtheta)^2); dtheta = abs(theta-theta0);
```
If we wanted to backport the fix, we may want to adopt this simpler form.

**Comment by peastman** [comment]
If you still think we need a 7.1.1 patch release to fix this, we really should do the simple change.  That's a small change I'd feel comfortable including in a patch (as long as we have a test case for it).  But adding a new function is a big change involving lots of new code, separate implementations for each platform, etc.  Any release including that would be much more than a patch.

That's not to say we can't *also* add that function in 7.2.  But for a patch, let's do the simplest, safest fix.

**Comment by peastman** [comment]
Simpler is good.  An even simpler version is

```
(K*2)*min(dtheta, 2*pi-dtheta)^2; dtheta = abs(theta-theta0);
```

**Comment by peastman** [comment]
Any progress on this?

**Comment by jchodera** [comment]
We put a local workaround in place, so this had ended up back on the bottom of the pile.

I still don't have a good idea for how to build a good test without burning a whole afternoon. Any ideas?

I can at least substitute the simpler form right now...

**Comment by peastman** [comment]
I've written a test case for this and sent it to you as a PR.

**Comment by jchodera** [comment]
Thank you, @peastman!

**Pull request merged**
