### PR TITLE
ENH: TestVectorize8

### PR DESCRIPTION
**Pull request by rmcgibbo**
I don't think we have a test that checks the basic properties of fvec8 and ivec8 yet. I'm adapting TestVectorize.cpp, which checks fvec8/ivec4.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
As I suspected with clang 3.6.0
```
$ ./TestVectorize8
exception: Assertion failure at TestVectorize8.cpp:106.   Expected (1.5,3,4.5,6,7.5,9,10.5,12), found (1.5,3,4.5,6,8.40779e-45,0,0,0)
```

**Comment by peastman** [comment]
Note that I intentionally did *not* implement operator[]() for fvec8 and ivec8, because it would necessarily be less efficient than calling lowerVec() or upperVec(), and hence would lead people into unwittingly writing inefficient code.

**Comment by rmcgibbo** [comment]
I'm only using it to make the assert more convenient -- it's not really necessary.

**Comment by peastman** [comment]
Understood!

**Comment by rmcgibbo** [comment]
Would it be bad form to make some slow convenience functions only conditionally compiled in debug mode or something? operator[] (and also a print() method) are kind of useful for debugging sometimes.

**Comment by peastman** [comment]
Yes, that would be very bad form. :)  Besides, test cases need to work when compiled in release mode!  Just call lowerVec() or upperVec(), then get the appropriate element from that.

**Comment by rmcgibbo** [comment]
:) okay.

**Comment by rmcgibbo** [comment]
Okay. I think this is ready. @peastman: do you know why `bool isVec8Supported()` was [defined](https://github.com/pandegroup/openmm/blob/master/platforms/cpu/src/CpuNonbondedForceVec8.cpp#L52) in `CpuNonbondedForceVec8.cpp` instead of in  `vectorize8.h`? Can I move it over? Otherwise I need to copy-paste it into this file.

**Comment by peastman** [comment]
Moving isVec8Supported() to the header would be reasonable, but let's wait till after 6.3 to do that.  It feels like a slightly dangerous change to make this late.

What's up with the commented out blocks that it says require AVX2?  OpenMM doesn't use any AVX2 instructions anywhere.

**Comment by rmcgibbo** [comment]
It's just a placeholder for tests that we would add if we supported those operations on ivec8 (which we don't).

**Comment by rmcgibbo** [comment]
Okay, I removed the commented out blocks.

**Pull request merged**
