### PR TITLE
Fix two tests for python3

### PR DESCRIPTION
**Pull request by rmcgibbo**

### CODE REVIEW

**Comment by peastman** [comment]
It's been 23 minutes since you posted this.  Travis finished in under 8 minutes.  And AppVeyor still hasn't even started running.  I don't think we want to have to wait that long for every PR.  Maybe this can be used as a secondary test: we merge if travis passes, but then get notified if AppVeyor fails?

**Comment by swails** [comment]
+1

**Comment by rmcgibbo** [comment]
That sounds good. Do you want an email or something for failures?

**Comment by jchodera** [comment]
What if we foot the $19/mo bill for super fast builds?

**Comment by rmcgibbo** [comment]
Naw. It was going super fast earlier for me today. I think it's just stuck or something.

**Pull request merged**
