### PR TITLE
Fix for unit cell vector calculation

### PR DESCRIPTION
**Pull request by swails**
had no effect for orthorhombic boxes, but now that triclinics are supported this is important.

See mdtraj/mdtraj#713 (and the PR mdtraj/mdtraj#714)

### CODE REVIEW

**Comment by peastman** [comment]
Hold off on this for the moment.  I should have the general triclinic support checked in later today or tomorrow.

**Comment by swails** [comment]
is this going to be in that PR?

**Comment by peastman** [comment]
I figured I would leave the CHARMM and Amber readers to you, though if you want me to I can certainly try to do them myself.  But the PR will include a new routine for doing this conversion.  That will avoid duplicate code.  Also, it makes sure the vectors are in the particular reduced form required by OpenMM.

**Comment by swails** [comment]
> I figured I would leave the CHARMM and Amber readers to you, though if you want me to I can certainly try to do them myself. But the PR will include a new routine for doing this conversion. That will avoid duplicate code. Also, it makes sure the vectors are in the particular reduced form required by OpenMM.

OK, I can do that.  I'll keep this PR open and simply fix it when your next PR comes and gets merged.

**Comment by swails** [comment]
This is a WIP -- I'll remove the tag and report back when it's good to merge.

**Comment by swails** [comment]
Should be good to go if Travis passes.

**Comment by peastman** [comment]
Thanks!

**Pull request merged**
