### PR TITLE
Enable wildcard use for Atom Types

### PR DESCRIPTION
**Pull request by rafwiewiora**
A test would be good too - let me complete that.

### CODE REVIEW

**Comment by rafwiewiora** [comment]
Reference https://github.com/pandegroup/openmm/issues/1347

**Comment by peastman** [comment]
Looks good.  A test will also help though.

**Comment by jchodera** [comment]
@rafwiewiora: Just wanted to make sure that you saw the request to add tests.

**Comment by rafwiewiora** [comment]
Yep, thanks @jchodera!

**Comment by rafwiewiora** [comment]
Tests added!

**Comment by peastman** [comment]
Looks like there's an error in your test case:

```
E     File "/home/travis/build/pandegroup/openmm/python/tests/TestForceField.py", line 453
E       ff = ForceField(StringIO(xml))
E                                    ^
E   IndentationError: unindent does not match any outer indentation level
```

**Comment by rafwiewiora** [comment]
Whoops, yeah just noticed the fail, fixing!

**Comment by rafwiewiora** [comment]
Should be good now.

**Pull request merged**
