### PR TITLE
Update packaging scripts for zip installers

### PR DESCRIPTION
**Pull request by jchodera**
* Update packaging scripts for jchodera/omnia-build-box:cuda80-amd30 docker image

Note that I'm using `gcc` for this build to match the conda installers.

@peastman : I'm having trouble getting the API docs built. After `make PythonInstall` completes successfully, `simtk.openmm` is surprisingly not installed into the Python environment, and `make PythonApiDocs` fails with:
```
[100%] Built target C++ApiDocs
[  0%] Generating app.rst, library.rst
Traceback (most recent call last):
  File "/build/docs-source/api-python/render.py", line 11, in <module>
    import simtk.openmm
ImportError: No module named 'simtk'
make[3]: *** [docs-source/api-python/app.rst] Error 1
make[2]: *** [docs-source/api-python/CMakeFiles/PythonApiDocs.dir/all] Error 2
make[1]: *** [docs-source/api-python/CMakeFiles/PythonApiDocs.dir/rule] Error 2
make: *** [PythonApiDocs] Error 2
```
Steps to reproduce:

1. Start the container:
```
docker run -i -t --rm -v `pwd`:/io jchodera/omnia-build-box:cuda80-amd30 bash
```
2. Inside the container (using `bash`):
```
# Clone the OpenMM tag
git clone https://github.com/pandegroup/openmm.git
cd openmm; git checkout 1e5b258; cd ..
# Build
source openmm/devtools/packaging/scripts/linux/prepare.sh	
source openmm/devtools/packaging/scripts/linux/build-gcc.sh
```

### CODE REVIEW

**Comment by peastman** [comment]
> Note that I'm using gcc for this build to match the conda installers.

I thought you already had that working with clang?  Using gcc for conda is just a temporary workaround to get the beta out.  There's no reason not to use clang for these builds.

> After make PythonInstall completes successfully, simtk.openmm is surprisingly not installed into the Python environment

Sounds like make PythonInstall is failing.  Is there any error message from it?

**Comment by jchodera** [comment]
> I thought you already had that working with clang? Using gcc for conda is just a temporary workaround to get the beta out. There's no reason not to use clang for these builds.

I'll switch to `clang`.

> Sounds like make PythonInstall is failing. Is there any error message from it?

Let me get you a full build log.

**Comment by jchodera** [comment]
> I thought you already had that working with clang? Using gcc for conda is just a temporary workaround to get the beta out. There's no reason not to use clang for these builds.

Quick question, @peastman: Have *you* successfully built with clang and installed with (gcc-compiled) anaconda python? Does that really work?

**Comment by jchodera** [comment]
@peastman : I'm stuck in the same segfault land when linking `clang`-compiled OpenMM to `anaconda` python:
```
running install_egg_info
Writing /miniconda/lib/python3.5/site-packages/OpenMM-7.1.0-py3.5.egg-info
[100%] Built target PythonInstall
[100%] Built target C++ApiDocs
[  0%] Generating app.rst, library.rst
*** glibc detected *** //miniconda/bin/python: free(): invalid pointer: 0x00007f962a84f300 ***
======= Backtrace: =========
/lib64/libc.so.6[0x7f96324c44af]
/lib64/libc.so.6(cfree+0x4b)[0x7f96324c87ab]
//install/lib/plugins/libOpenMMCUDA.so[0x7f962a2c6d39]
//install/lib/plugins/libOpenMMCUDA.so(_ZN6OpenMM12CudaPlatformC1Ev+0x13e)[0x7f962a27c10e]
//install/lib/plugins/libOpenMMCUDA.so(registerPlatforms+0x19)[0x7f962a27bfa9]
//install/lib/libOpenMM.so(_ZN6OpenMM8Platform24loadPluginsFromDirectoryERKSs+0x733)[0x7f962bace953]
//miniconda/lib/python3.5/site-packages/simtk/openmm/_openmm.cpython-35m-x86_64-linux-gnu.so[0x7f962c01e01c]
/miniconda/bin/../lib/libpython3.5m.so.1.0(PyCFunction_Call+0xf9)[0x7f96333175e9]
/miniconda/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x8fb5)[0x7f963339ebd5]
```
Looks like it's either gcc or nothing at this point.

**Comment by peastman** [comment]
I do that all the time.  But of course, I'm not building on an ancient OS.

**Comment by jchodera** [comment]
Sigh. We could try moving everything to a CentOS 6-based docker image, but we have to move literally *everything*---OpenMM and Omnia---all at once.

**Comment by peastman** [comment]
With the coming end of support for CentOS 5, we should be doing that anyway.  Let's start the discussion with the omnia group about making that change.

**Comment by jchodera** [comment]
I've tried to get that discussion started, and nobody replied to by Dec 6 email asking if upgrading to CentOS 6 would cause issues:
> Omnia CentOS 6 migration: Would anyone object to migrating the build infrastructure to CentOS 6 minimum glibc requirements? This would mean we would no longer support CentOS 5, so let me know if this would break anything for anyone. This move would enable us to eventually migrate to the very nice conda-forge build system, which would drastically reduce maintenance burden.

I think we can probably move forward on this and hope nothing breaks. The big question is "what base image should we use"? `holy-build-box` is [starting to update to CentOS 6](https://github.com/phusion/holy-build-box/pull/3), and I was hoping we could wait for that.

There's also the [`conda-forge` `linux-anvil` docker image](https://github.com/conda-forge/docker-images/blob/master/linux-anvil/Dockerfile), which may be also good for setting us up to migrate there. We can layer texlive, AMD 3.0, CUDA 8.0, and clang 3.8 on top of it.

**Comment by jchodera** [comment]
I'm rebuilding our current omnia docker image stack from the [`holy-build-box` 1.2 image](https://github.com/phusion/holy-build-box/blob/master/Changelog.md#version-120-release-date-2016-11-16) just in case this fixes the issues we had with 1.1, but I'm not optimistic. We'll need to decide to either progress with gcc and the current images or base our docker images on top of something like `conda-forge`.

**Comment by peastman** [comment]
Assuming we eventually want to move a lot of our software to conda-forge, that would make sense as a thing to base it on.

**Comment by jchodera** [comment]
@peastman : Christmas comes early! I think I've sorted the issues with `clang` `linux` `beta` builds inside the CentOS 5 `omnia-build-box` container.

Surprisingly, the issue just seemed to be activating `/opt/rh/devtoolset-2/` instead of any of the `holy-build-box` toolkits. What I'm not certain of is whether this is going to cause any `glibc` compatibility issues.

Linux zip installers:
* [OpenMM-7.1.0-Linux.tgz](https://s3.amazonaws.com/omnia-ci/OpenMM-7.1.0-Linux.tgz)
* [OpenMM-7.1.0-Linux.zip](https://s3.amazonaws.com/omnia-ci/OpenMM-7.1.0-Linux.zip)

I've had some trouble generating the `osx` C++ API docs, but I built the package anyway:
* [OpenMM-7.1.0-Mac.tgz](https://s3.amazonaws.com/omnia-ci/OpenMM-7.1.0-Mac.tgz)
* [OpenMM-7.1.0-Mac.zip](https://s3.amazonaws.com/omnia-ci/OpenMM-7.1.0-Mac.zip)

Errors from the `osx` C++ API doc build:
```
mski1776:build choderaj$ make C++ApiDocs
Generating ../../api-c++/index.html
Running Sphinx v1.5.1
loading pickled environment... not yet created
[autosummary] generating autosummary for: generated/OpenMM.AmoebaAngleForce.rst, generated/OpenMM.AmoebaBondForce.rst, generated/OpenMM.AmoebaGeneralizedKirkwoodForce.rst, generated/OpenMM.AmoebaInPlaneAngleForce.rst, generated/OpenMM.AmoebaMultipoleForce.rst, generated/OpenMM.AmoebaOutOfPlaneBendForce.rst, generated/OpenMM.AmoebaPiTorsionForce.rst, generated/OpenMM.AmoebaStretchBendForce.rst, generated/OpenMM.AmoebaTorsionTorsionForce.rst, generated/OpenMM.AmoebaVdwForce.rst, ..., generated/OpenMM.ThreeParticleAverageSite.rst, generated/OpenMM.TwoParticleAverageSite.rst, generated/OpenMM.VariableLangevinIntegrator.rst, generated/OpenMM.VariableVerletIntegrator.rst, generated/OpenMM.Vec3.rst, generated/OpenMM.VerletIntegrator.rst, generated/OpenMM.VirtualSite.rst, generated/OpenMM.XmlSerializer.rst, index.rst, library.rst
[autosummary] generating autosummary for: generated/OpenMM.AmoebaAngleForce.rst, generated/OpenMM.AmoebaBondForce.rst, generated/OpenMM.AmoebaGeneralizedKirkwoodForce.rst, generated/OpenMM.AmoebaInPlaneAngleForce.rst, generated/OpenMM.AmoebaMultipoleForce.rst, generated/OpenMM.AmoebaOutOfPlaneBendForce.rst, generated/OpenMM.AmoebaPiTorsionForce.rst, generated/OpenMM.AmoebaStretchBendForce.rst, generated/OpenMM.AmoebaTorsionTorsionForce.rst, generated/OpenMM.AmoebaVdwForce.rst, ..., generated/OpenMM.ThreeParticleAverageSite.rst, generated/OpenMM.TwoParticleAverageSite.rst, generated/OpenMM.VariableLangevinIntegrator.rst, generated/OpenMM.VariableVerletIntegrator.rst, generated/OpenMM.Vec3.rst, generated/OpenMM.VerletIntegrator.rst, generated/OpenMM.VirtualSite.rst, generated/OpenMM.XmlSerializer.rst, index.rst, library.rst
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 72 source files that are out of date
updating environment: 72 added, 0 changed, 0 removed
reading sources... [  6%] generated/OpenMM.AmoebaMultipoleForce                                                                                                                                                                                                                                                                                                           
Exception occurred:
  File "/Users/choderaj/github/omnia/omnia-build-box/workspace/miniconda/lib/python3.5/site-packages/sphinxcontrib/autodoc_doxygen/autosummary/__init__.py", line 41, in import_by_name
    raise ImportError('no module named %s' % ' or '.join(tried))
ImportError: no module named NonbondedMethod
The full traceback has been saved in /var/folders/m1/wl3ptzqx2csf2r_q2bfy78n0h7kcfv/T/sphinx-err-4r_h6gfa.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make[3]: *** [api-c++/index.html] Error 1
make[2]: *** [docs-source/api-c++/CMakeFiles/C++ApiDocs.dir/all] Error 2
make[1]: *** [docs-source/api-c++/CMakeFiles/C++ApiDocs.dir/rule] Error 2
make: *** [C++ApiDocs] Error 2
```
Give them a try and see how it works for you.

I've also made some progress on `condaforge/linux-anvil`-based builds, but there are still issues to sort out there for migration to CentOS 6. I don't think they're insurmountable, though.

I'm working to see if I can use the same scheme to build `clang` versions of the `conda` recipe.

**Comment by peastman** [comment]
Great!  I'll test everything tomorrow.  The docs folder can just be copied over from the Linux build.  That's what I'll be doing with the Windows one anyway, since I can't build the pdfs there.

**Comment by jchodera** [comment]
> The docs folder can just be copied over from the Linux build. 

OK, you'll have to do that manually for the zip installers you post. 

I forgot to mention that the OS X zip installers were built with 10.11 frameworks, but I can find a machine with the 10.9 frameworks installed for the real release candidate. It just seemed [like a huge pain](https://github.com/devernay/xcodelegacy) to install them.

I'll document the manual zip installer build procedure in the `README.md` before we merge these updates. 

If we can fix the OS X Api docs build issue, what would you think about going further and having Travis build installers for each commit to `master` and upload the artifacts to S3 for testing? This could greatly simplify the release candidate procedure for zip installers.

**Comment by peastman** [comment]
I'm creating the release on simtk.org right now.  Do you have the source zip as well?

**Comment by jchodera** [comment]
Whoops! Give me 10 min.

**Comment by jchodera** [comment]
Sorry---taking longer than I thought because the scripts needed to be updated. But it's building now.

**Comment by jchodera** [comment]
Here you go!
* [OpenMM-7.1.0-Source.tgz](https://s3.amazonaws.com/omnia-ci/OpenMM-7.1.0-Source.tgz)
* [OpenMM-7.1.0-Source.zip](https://s3.amazonaws.com/omnia-ci/OpenMM-7.1.0-Source.zip)

**Comment by peastman** [comment]
The files are online at simtk.org.  Now we just need to test them and then I can post an announcement.  I'm testing the Mac one now.

**Comment by peastman** [comment]
The Mac zip works, except that I can't test the CUDA platform since my Mac doesn't have an NVIDIA GPU.  Checking Linux next.

**Comment by jchodera** [comment]
Shoot, I don't think the Mac I built this ZIP installer on had CUDA installed either.

Let me go back to the old machine I was using for that build and re-build. Thanks for jarring my memory.

**Comment by jchodera** [comment]
I've tested the conda packages via forced downgrade:
```bash
conda install --yes openmm==7.0.1 ; conda clean -plti --yes ; conda install --yes -c omnia/label/beta openmm==7.1.0
```
So far, `osx` and `linux` packages work fine on anaconda python 3.5.

**Comment by peastman** [comment]
Yeah, I'd just noticed the CUDA libraries were missing too.

**Comment by jchodera** [comment]
> Yeah, I'd just noticed the CUDA libraries were missing too.

The old machine still has CUDA 7.5 and I can't upgrade it remotely, but I think I can just install 8.0 on the new `osx` machine I used for this build. Doing that now.

**Comment by peastman** [comment]
The Linux zip works.

**Comment by jchodera** [comment]
I've updated the `osx` packages and verified they contain the CUDA libraries:
* [OpenMM-7.1.0-Mac.tgz](https://s3.amazonaws.com/omnia-ci/OpenMM-7.1.0-Mac.tgz)
* [OpenMM-7.1.0-Mac.zip](https://s3.amazonaws.com/omnia-ci/OpenMM-7.1.0-Mac.zip)

**Comment by peastman** [comment]
Thanks!  I verified that it works (aside from CUDA).  I'll write up a release announcement and post that later today.

**Comment by jchodera** [comment]
Awesome!

Can you include the conda instructions in the release announcement as well? I'm curious for people to test that too.

For users that already have OpenMM installed, we want to recommend they install with 
```bash
# Install beta
conda install --yes -c omnia/label/beta openmm==7.1.0
```
If they've been using the `dev` version of the `master` branch builds, they will need to force a downgrade first:
```bash
# Force downgrade
conda install --yes openmm==7.0.1
# Clean local package cache
conda clean -plti --yes
# Install beta
conda install --yes -c omnia/label/beta openmm==7.1.0
```

**Comment by jchodera** [comment]
OK, this should be ready to merge.

**Comment by peastman** [comment]
The announcement is posted at https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=7306&p=0&start=0&view=.

**Comment by jchodera** [comment]
> The announcement is posted at https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=7306&p=0&start=0&view=.

Thanks! I'll spread the word!

**Pull request merged**
