### PR TITLE
Rewrite run-ctest.py

### PR DESCRIPTION
**Pull request by rmcgibbo**
Fixes #1316

### CODE REVIEW

**Comment by rmcgibbo** [comment]
lol python2 is terrible. you can't multiply a timedelta and a float.

**Comment by jchodera** [comment]
Relevant: https://www.destroyallsoftware.com/talks/wat

**Comment by rmcgibbo** [comment]
@jchodera one of the errors is an OpenCL segfault, so it's probably something. I thought we'd previously ironed out all of the OpenCL CPU platform segfaults, but maybe not.

```
Test project /home/travis/build/pandegroup/openmm
    Start 76: TestOpenCLCustomManyParticleForceSingle
1/1 Test #76: TestOpenCLCustomManyParticleForceSingle ...***Exception: SegFault 22.26 sec
```

**Comment by jchodera** [comment]
The the segfaults *are* real!

**Comment by jchodera** [comment]
How did you make the segfaults go away?  Did you just limit the overall test runtime to be very short, and then retrigger travis a few times?  

Maybe we should let the tests run for a bit longer?  We're only using 23 / 50 travis minutes right now, I think...

**Comment by jchodera** [comment]
Or maybe we should split up the OpenCL tests into multiple parallel travis instances?
https://docs.travis-ci.com/user/speeding-up-the-build/#Parallelizing-your-builds-across-virtual-machines

**Comment by rmcgibbo** [comment]
> How did you make the segfaults go away?

Just cause it's stochastic, and I rebased and forced push to clean up the git history before merging.

Obviously there's a tension between having the tests be exhaustive and complete quickly. I think we get pretty good coverage with the current settings, in that we're aware of the failures pretty quickly.

**Comment by rmcgibbo** [comment]
The most useful thing to actually fix or investigate the segfault would be to get a stacktrace.

**Comment by jchodera** [comment]
> Just cause it's stochastic, and I rebased and forced push to clean up the git history before merging.

Actually, it doesn't look like the failure is stochastic, but the order in which tests are run is stochastic due to the `--schedule-random`.  The test that previously segfaulted (`TestOpenCLCustomManyParticleForceSingle`) wasn't even run this time.

**Comment by rmcgibbo** [comment]
Yes, that's what I meant by "it".

**Comment by jchodera** [comment]
> Obviously there's a tension between having the tests be exhaustive and complete quickly. I think we get pretty good coverage with the current settings, in that we're aware of the failures pretty quickly.

Could we use the `-I start,end,stride` argument and a couple of extra build matrix entries to split up the tests into, say, 4 groups that run in parallel?
https://cmake.org/cmake/help/v2.8.8/ctest.html#opt:-IStartEndStridetesttestTestfile--tests-information

**Comment by rmcgibbo** [comment]
We hashed out the pros and cons of testing a subset random order in #1212, and I discussed it with peter before that was merged. I'd prefer not to beat a dead horse. Splitting up the OpenCL with multiple jobs is also an option, but it's more complex, and isn't worth it, IMO.

**Comment by jchodera** [comment]
> The most useful thing to actually fix or investigate the segfault would be to get a stacktrace.

Now that there is a [more unified test infrastructure](https://github.com/pandegroup/openmm/tree/master/tests), we could have the tests [install a `SIGSEGV` handler](http://stackoverflow.com/questions/77005/how-to-generate-a-stacktrace-when-my-gcc-c-app-crashes) that will print a useful stacktrace if they segfault.

Right now, the tests all have their own `main()`, but we could presumably add a single header file that, for `unix/osx`, defines this handler and a corresponding `#define` that could be included at the beginning of each `main()`:
```C++
#include <stdio.h>
#include <execinfo.h>
#include <signal.h>
#include <stdlib.h>
#include <unistd.h>


void handler(int sig) {
  void *array[10];
  size_t size;

  // get void*'s for all entries on the stack
  size = backtrace(array, 10);

  // print out all the frames to stderr
  fprintf(stderr, "Error: signal %d:\n", sig);
  backtrace_symbols_fd(array, size, STDERR_FILENO);
  exit(1);
}
```
and does nothing for `win`.

**Comment by rmcgibbo** [comment]
I feel like this is something ctest should be able to do for you, but maybe not.

**Comment by jchodera** [comment]
> We hashed out the pros and cons of testing a subset random order in #1212, and I discussed it with peter before that was merged. I'd prefer not to beat a dead horse.

Oh, I have no problem with the random order testing if we're only testing everything in a single travis instance.

> Splitting up the OpenCL with multiple jobs is also an option, but it's more complex, and isn't worth it, IMO.

That's what I was suggesting, if there was a simple way to do it with the `-I` argument to CTest.  We can definitely explore that in a separate PR, though.

**Comment by rmcgibbo** [comment]
I thought it might help to get the exact same OpenCL CPU driver version, but I can't reproduce the test failure :(

```
root@33af72743cee:/openmm/build# ./TestOpenCLDeviceQuery
OpenCL devices:

OpenCLPlatformIndex 0, OpenCLDeviceIndex 0: "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz"
    CL_PLATFORM_NAME                 = AMD Accelerated Parallel Processing
    CL_PLATFORM_VENDOR               = Advanced Micro Devices, Inc.
    CL_DEVICE_VENDOR                 = GenuineIntel
    CL_DEVICE_VERSION                = OpenCL 1.2 AMD-APP (923.1)
    CL_DEVICE_TYPE                   = CL_DEVICE_TYPE_CPU
    CL_DEVICE_MAX_COMPUTE_UNITS      = 8
    CL_DEVICE_MAX_WORK_ITEM_SIZES    = [1024, 1024, 1024]
    CL_DEVICE_HOST_UNIFIED_MEMORY    = 1
    CL_DEVICE_GLOBAL_MEM_SIZE        = 12558561280
    CL_DEVICE_LOCAL_MEM_SIZE         = 32768
    CL_DEVICE_MAX_MEM_ALLOC_SIZE     = 3139640320
    CL_DEVICE_ADDRESS_BITS           = 64
    CL_DEVICE_MAX_CLOCK_FREQUENCY    = 2451
    processingElementsPerComputeUnit = 1
    estimatedSpeed                   = 19608
    CL_DEVICE_EXTENSIONS             = cl_amd_device_attribute_query
        cl_amd_fp64 cl_amd_media_ops cl_amd_popcnt cl_amd_printf cl_amd_vec3
        cl_ext_device_fission cl_khr_byte_addressable_store cl_khr_fp64
        cl_khr_gl_sharing cl_khr_global_int32_base_atomics
        cl_khr_global_int32_extended_atomics cl_khr_int64_base_atomics
        cl_khr_int64_extended_atomics cl_khr_local_int32_base_atomics
        cl_khr_local_int32_extended_atomics

root@33af72743cee:/openmm/build# ./TestOpenCLCustomManyParticleForce single
Done
```

**Comment by jchodera** [comment]
This should be ready to merge, yes?

**Comment by jchodera** [comment]
Also might be good to open a separate issue thread about the OpenCL segfaults.

**Comment by rmcgibbo** [comment]
Sure, yeah. This is ready to merge.

**Pull request merged**
