### PR TITLE
[WIP] Bug in CPU neighborlist?

### PR DESCRIPTION
**Pull request by rmcgibbo**
This change triggers a test failure on my machine -- want to run on travis.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Reverting 95423468ab fixes the test failure, so I think there's a bug here.

**Comment by jchodera** [comment]
Did the test from this PR get incorporated somewhere?  Seems like it would be useful to retain the test that caught this bug.

**Comment by swails** [comment]
@rmcgibbo found this just running the existing test suite with a different compiler (icc).

**Comment by swails** [comment]
See #1004

**Comment by jchodera** [comment]
Wasn't this a PR containing test changes that revealed the error using `gcc`?  He demonstrated that the test fails on travis too (which uses `gcc`):
https://github.com/pandegroup/openmm/pull/1014/files

I know he was able to get things to fail with `icc`, but if there is a test that reveals the issue with `gcc` too, that may be worth including...

**Comment by swails** [comment]
No, the PR just changed 1 file, no tests (it reverted a single commit).  @rmcgibbo posted test failures from Intel and one or two from GCC from the existing test suite.  The test failures seem to be intermittent and hardware-dependent, which is why Travis didn't catch it but @rmcgibbo did.

**Comment by jchodera** [comment]
Sorry, I'm still confused; maybe we're mixing up issues?

If you click on the "files" tab on this PR, or you click on [this link which takes you to the same place](https://github.com/pandegroup/openmm/pull/1014/files), you will see:

Showing  1 changed file  with 14 additions and 5 deletions.
`platforms/cpu/tests/TestCpuNeighborList.cpp`

which clearly shows edits made to `TestCpuNeighborList`, which when run on travis (using `clang`) show that this test *fails*:
```
37: Test command: /home/travis/build/pandegroup/openmm/TestCpuNeighborList "single"
37: Test timeout computed to be: 1500
37: exception: Assertion failure at TestCpuNeighborList.cpp:127
 36/108 Test  #37: TestCpuNeighborList ...........................***Failed    0.10 sec
```

**Comment by swails** [comment]
Oh, my mistake.  I misread the filename.  I'll wait for @rmcgibbo to comment.

**Pull request closed without merging**
