### PR TITLE
Updated version number to 6.3.1

### PR DESCRIPTION
**Pull request by peastman**
This should be version 6.3.1.  I'm running unit tests right now, and I'll get the system tests started to begin running tonight.  But in the mean time, let's go ahead and build installers.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Do you want to file a PR against https://github.com/omnia-md/conda-recipes/blob/master/openmm/meta.yaml too? That will automatically compile and deploy packages for OS X and Linux (built on CentOS 5).

**Comment by peastman** [comment]
We should finish the testing before we deploy it.

**Comment by rmcgibbo** [comment]
Sure. It'll only deploy after we merge the PR.

**Comment by jchodera** [comment]
I'm happy to start the Jenkins `linux`, `osx`, and `source` builds.  I just need you to tell me what you want git branch, hash, or release tag you want me to pull from.

**Comment by rmcgibbo** [comment]
Presumably  731a9e2

**Comment by peastman** [comment]
Pull from 6.3_branch.  Remember this needs to be built against exactly the same libraries we used when building 6.3.  In particular, we need to use CUDA 7.0, not 7.5.

**Comment by jchodera** [comment]
I haven't changed any of the build settings.

**Comment by jchodera** [comment]
Here you go!
* Linux: https://jenkins.choderalab.org/job/package-openmm-linux-vagrant/ws/packaging/compressed/
* OSX: https://jenkins.choderalab.org/job/package-openmm-osx/ws/packaging/compressed/
* Source: https://jenkins.choderalab.org/job/package-openmm-source/ws/packaging/compressed/

Let me know if anything is messed up, but this should have been built exactly the same way as 6.3.  The only thing I changed was the branch/tag I pulled from.

**Pull request merged**
