### PR TITLE
Add Bohrs to units

### PR DESCRIPTION
**Pull request by rmcgibbo**

### CODE REVIEW

**Comment by peastman** [comment]
Where did you get the value from?  I just checked several online sources, and all of them report a slightly different value.  Wikipedia (https://en.wikipedia.org/wiki/Bohr_radius) lists it as 0.52917721067.

**Comment by rmcgibbo** [comment]
I don't remember. I'll change it to the value from CODATA.

**Comment by rmcgibbo** [comment]
Do you mind if I add `hartree`s too?

**Comment by jchodera** [comment]
> Do you mind if I add hartrees too?

Sounds like a good idea.

Are there other QM units that would be good to add at this point? Or constants?

**Comment by rmcgibbo** [comment]
There could be, but those were the two things that came to mind for my purposes.

**Comment by swails** [comment]
Whatever happened to this PR?

**Comment by jchodera** [comment]
It is among the forgotten...

**Comment by peastman** [comment]
@rmcgibbo looks like we were waiting for you.  Just we go ahead and merge this?

**Comment by rmcgibbo** [comment]
yeah, +1 to just merge as is.

**Comment by peastman** [comment]
Ok, thanks.  We should go through old PRs and clean them up.

**Pull request merged**
