### PR TITLE
Optimized computing long range correction for CustomNonbondedForce

### PR DESCRIPTION
**Pull request by peastman**
This tries to address #1832, but don't expect anything dramatic.  It's a bit faster than before, but not hugely faster.

### CODE REVIEW

**Comment by peastman** [comment]
Has something changed with the travis configuration?  The CUDA and OpenCL builds are both failing with the error

```
In file included from /home/travis/build/pandegroup/openmm/platforms/opencl/./include/OpenCLContext.h:40:0,
                 from /home/travis/build/pandegroup/openmm/platforms/opencl/./include/OpenCLArray.h:30,
                 from /home/travis/build/pandegroup/openmm/platforms/opencl/src/OpenCLArray.cpp:27:
/home/travis/build/pandegroup/openmm/platforms/opencl/src/cl.hpp:177:19: fatal error: GL/gl.h: No such file or directory
 #include <GL/gl.h>
```

It looks like the OpenGL headers aren't being installed anymore.

**Comment by jchodera** [comment]
The [travis image update history](https://docs.travis-ci.com/user/build-environment-updates/) doesn't show any updates to `trusty` images (Ubuntu 14.04).

**Comment by peastman** [comment]
I'm going to merge this anyway, since the error is unrelated to this PR and everything passed on Jenkins.

**Comment by jchodera** [comment]
The [travis issue log](https://www.traviscistatus.com/incidents/rnlm5ffmk7dm) doesn't suggest anything either.

Where does `GL/gl.h` come from? Is it installed in the `trusty` build image, do we install it, or is it something in the ccache (which may have been corrupted or cleared)?

**Comment by peastman** [comment]
No idea where it was coming from in this particular case.  There are various packages that can install OpenGL headers, such as `mesa-dev`.

**Comment by jchodera** [comment]
It looks like you can add `mesa-common-dev` from the [`trusty` whitelist](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty#L3859) to [this block in `.travis.yml`](https://github.com/pandegroup/openmm/blob/master/.travis.yml#L5-L10) and that might ensure `GL/gl.h` is available. But I'm not sure why this changed.

**Comment by peastman** [comment]
They did in fact just change their images:

https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch

And the new versions removed the `libgl1-mesa-dev` package:

https://github.com/travis-ci/build-environment-updates/blob/master/2017Q2/gce/garnet-trusty/dpkg-manifest.diff#L402

I'll add it back.

**Pull request merged**
