### PR TITLE
GBn now uses Discrete2DFunctions

### PR DESCRIPTION
**Pull request by peastman**
This should address #928.

### CODE REVIEW

**Comment by swails** [comment]
OK, I'll post the results of my test after I finish.

**Comment by pgrinaway** [comment]
This is great! Thanks!

**Comment by peastman** [comment]
@swails have you had a chance to run your tests yet?

**Comment by swails** [comment]
haha -- that's what I'm doing literally right now.  Report coming soon.  Everything's looking good so far -- I'm about to throw in some random radii in the 1-2 AA range to do more of a stress-test.

**Comment by swails** [comment]
This is my test script: https://gist.github.com/swails/f74df2de58c5cfb54bcf

It runs one of the Amber test cases (`$AMBERHOME/test/gb7_trx`) using both GBn and GBn2 (igb=7, igb=8 in Amber).  First it uses the "original" radii in the prmtop, then it runs 5 energy/force evaluations using randomly distributed radii within the range [1.0, 2.0) angstroms.

The energy comparisons with the "original" radii with sander are quite good, but get worse for other radii:

```
Checking model GBn
------------------
E sander            =   -2.156420e+03
E OpenMM            =   -2.155807e+03
Max Force Diff      =    2.032802e-02
Max Force Mag. Diff =    2.391367e-02
Avg Force Mag. Diff =    1.943566e-03
-------------------------------------
-------------------------------------
E sander            =   -1.829176e+03
E OpenMM            =   -1.819952e+03
Max Force Diff      =    6.953035e+00
Max Force Mag. Diff =    1.188045e+01
Avg Force Mag. Diff =    5.540031e-01
-------------------------------------
-------------------------------------
E sander            =   -1.686757e+03
E OpenMM            =   -1.667562e+03
Max Force Diff      =    3.690253e+01
Max Force Mag. Diff =    3.879398e+01
Avg Force Mag. Diff =    1.245999e+00
-------------------------------------
-------------------------------------
E sander            =   -1.846999e+03
E OpenMM            =   -1.922989e+03
Max Force Diff      =    1.572608e+01
Max Force Mag. Diff =    1.936157e+01
Avg Force Mag. Diff =    5.039407e-01
-------------------------------------
-------------------------------------
E sander            =   -1.798418e+03
E OpenMM            =   -1.773712e+03
Max Force Diff      =    1.231288e+01
Max Force Mag. Diff =    2.278232e+01
Avg Force Mag. Diff =    5.747239e-01
-------------------------------------
-------------------------------------
================================================================================
Checking model GBn2
-------------------
E sander            =   -2.228559e+03
E OpenMM            =   -2.228168e+03
Max Force Diff      =    9.850390e-02
Max Force Mag. Diff =    1.224215e-01
Avg Force Mag. Diff =    3.262610e-03
-------------------------------------
-------------------------------------
E sander            =   -1.721675e+03
E OpenMM            =   -1.816765e+03
Max Force Diff      =    1.866333e+01
Max Force Mag. Diff =    1.903141e+01
Avg Force Mag. Diff =    2.589554e+00
-------------------------------------
-------------------------------------
E sander            =   -1.598679e+03
E OpenMM            =   -1.788212e+03
Max Force Diff      =    1.438623e+01
Max Force Mag. Diff =    2.016102e+01
Avg Force Mag. Diff =    2.720518e+00
-------------------------------------
-------------------------------------
E sander            =   -1.789613e+03
E OpenMM            =   -1.799055e+03
Max Force Diff      =    1.387589e+01
Max Force Mag. Diff =    1.594612e+01
Avg Force Mag. Diff =    2.020813e+00
-------------------------------------
-------------------------------------
E sander            =   -1.741496e+03
E OpenMM            =   -1.871661e+03
Max Force Diff      =    2.628223e+01
Max Force Mag. Diff =    2.938952e+01
Avg Force Mag. Diff =    2.550608e+00
-------------------------------------
-------------------------------------
================================================================================
```

The next thing I'm going to try is the old vs. new `CustomGBForce` implementation (i.e., the `Discrete1DFunction` vs. the `Discrete2DFunction`) and sander vs. the old `CustomGBForce`.

**Comment by swails** [comment]
OK.  Tests finished.  Results are *weird*

Here is the same test, but using the `Discrete1DFunction` version instead of sander (so the old vs. new in OpenMM):

```
Checking model GBn
------------------
E Discrete1D        =   -2.155807e+03
E Discrete2D        =   -2.155807e+03
Max Force Diff      =    0.000000e+00
Max Force Mag. Diff =    0.000000e+00
Avg Force Mag. Diff =    0.000000e+00
-------------------------------------
-------------------------------------
E Discrete1D        =   -1.845813e+03
E Discrete2D        =   -1.730895e+03
Max Force Diff      =    2.733109e+01
Max Force Mag. Diff =    3.382521e+01
Avg Force Mag. Diff =    2.130993e+00
-------------------------------------
-------------------------------------
E Discrete1D        =   -1.964465e+03
E Discrete2D        =   -1.727269e+03
Max Force Diff      =    2.162581e+01
Max Force Mag. Diff =    2.657319e+01
Avg Force Mag. Diff =    2.176550e+00
-------------------------------------
-------------------------------------
E Discrete1D        =   -1.618387e+03
E Discrete2D        =   -1.630293e+03
Max Force Diff      =    1.898730e+01
Max Force Mag. Diff =    2.148378e+01
Avg Force Mag. Diff =    2.318956e+00
-------------------------------------
-------------------------------------
E Discrete1D        =   -1.887010e+03
E Discrete2D        =   -1.658992e+03
Max Force Diff      =    1.318186e+01
Max Force Mag. Diff =    1.625035e+01
Avg Force Mag. Diff =    1.864984e+00
-------------------------------------
-------------------------------------
================================================================================
Checking model GBn2
-------------------
E Discrete1D        =   -2.228168e+03
E Discrete2D        =   -2.228168e+03
Max Force Diff      =    0.000000e+00
Max Force Mag. Diff =    0.000000e+00
Avg Force Mag. Diff =    0.000000e+00
-------------------------------------
-------------------------------------
E Discrete1D        =   -1.838067e+03
E Discrete2D        =   -1.774878e+03
Max Force Diff      =    9.110860e+00
Max Force Mag. Diff =    1.664071e+01
Avg Force Mag. Diff =    1.491690e+00
-------------------------------------
-------------------------------------
E Discrete1D        =   -1.910883e+03
E Discrete2D        =   -1.741842e+03
Max Force Diff      =    1.155570e+01
Max Force Mag. Diff =    1.218819e+01
Avg Force Mag. Diff =    1.225679e+00
-------------------------------------
-------------------------------------
E Discrete1D        =   -1.992120e+03
E Discrete2D        =   -1.844206e+03
Max Force Diff      =    9.795158e+00
Max Force Mag. Diff =    1.254181e+01
Avg Force Mag. Diff =    1.199221e+00
-------------------------------------
-------------------------------------
E Discrete1D        =   -1.868477e+03
E Discrete2D        =   -1.775594e+03
Max Force Diff      =    7.343641e+00
Max Force Mag. Diff =    1.080126e+01
Avg Force Mag. Diff =    1.260433e+00
-------------------------------------
-------------------------------------
================================================================================
```
Perfect agreement for original parameters, poor agreement for random radii (within the range).  I also checked that all of the per-particle parameters are identical for both custom forces, and they are.

Now to compare the Discrete1DFunction with sander:

```
Checking model GBn
------------------
E sander            =   -2.156420e+03
E OpenMM            =   -2.155807e+03
Max Force Diff      =    2.032802e-02
Max Force Mag. Diff =    2.391367e-02
Avg Force Mag. Diff =    1.943566e-03
-------------------------------------
-------------------------------------
E sander            =   -1.607512e+03
E OpenMM            =   -1.744549e+03
Max Force Diff      =    2.093195e+01
Max Force Mag. Diff =    2.384010e+01
Avg Force Mag. Diff =    2.254651e+00
-------------------------------------
-------------------------------------
E sander            =   -1.675657e+03
E OpenMM            =   -1.615865e+03
Max Force Diff      =    4.759672e+01
Max Force Mag. Diff =    4.843315e+01
Avg Force Mag. Diff =    2.180477e+00
-------------------------------------
-------------------------------------
E sander            =   -1.911935e+03
E OpenMM            =   -1.933507e+03
Max Force Diff      =    1.874645e+01
Max Force Mag. Diff =    1.876855e+01
Avg Force Mag. Diff =    2.022342e+00
-------------------------------------
-------------------------------------
E sander            =   -1.639804e+03
E OpenMM            =   -1.646607e+03
Max Force Diff      =    1.633338e+01
Max Force Mag. Diff =    1.645744e+01
Avg Force Mag. Diff =    2.015325e+00
-------------------------------------
-------------------------------------
================================================================================
Checking model GBn2
-------------------
E sander            =   -2.228559e+03
E OpenMM            =   -2.228168e+03
Max Force Diff      =    9.850390e-02
Max Force Mag. Diff =    1.224215e-01
Avg Force Mag. Diff =    3.262610e-03
-------------------------------------
-------------------------------------
E sander            =   -1.479301e+03
E OpenMM            =   -1.821799e+03
Max Force Diff      =    1.642054e+01
Max Force Mag. Diff =    2.071402e+01
Avg Force Mag. Diff =    2.843942e+00
-------------------------------------
-------------------------------------
E sander            =   -1.699386e+03
E OpenMM            =   -2.045032e+03
Max Force Diff      =    3.083708e+01
Max Force Mag. Diff =    3.307308e+01
Avg Force Mag. Diff =    3.262057e+00
-------------------------------------
-------------------------------------
E sander            =   -1.663350e+03
E OpenMM            =   -1.926292e+03
Max Force Diff      =    3.334869e+01
Max Force Mag. Diff =    5.348361e+01
Avg Force Mag. Diff =    3.256423e+00
-------------------------------------
-------------------------------------
E sander            =   -1.738235e+03
E OpenMM            =   -2.109049e+03
Max Force Diff      =    4.113632e+01
Max Force Mag. Diff =    4.181749e+01
Avg Force Mag. Diff =    3.090540e+00
-------------------------------------
-------------------------------------
================================================================================
```

Same type of behavior as Discrete2DFunction.  Neither seems better compared to the "reference" implementation.  No idea what to do here, or why it disagrees for "random" radii.  One comment I'll make is that I *think* all of the standard radii fall basically exactly on one of the bins, whereas the random radii do not.

**Comment by peastman** [comment]
For radii that aren't multiples of 0.05 (all of the standard radii are multiples of that), the old version was clearly and unambiguously wrong.  It produced meaningless results.  The new version does something reasonable with them, but it might not be the same thing Amber does.  For example, perhaps it always rounds downward (takes the integer part of the index) rather than rounding to the nearest value?

**Comment by peastman** [comment]
By the way, if that really is the difference, I'd say the OpenMM behavior is "better" than the Amber behavior (though of course it makes no difference as long as your radii are multiples of 0.05).

**Comment by swails** [comment]
Amber uses a 2-D table similar to `Discrete2DFunction`, and uses Fortran's `nint` to get the index from the radius.  I posted the code snippet [in issue 928](https://github.com/pandegroup/openmm/issues/928#issuecomment-105896351) earlier.  So I don't think the `Discrete2DFunction` approach is better than what Amber does (I'm still not sure why it's even different, to be honest).

**Comment by swails** [comment]
@peastman -- I submitted a PR to your gbn branch to use a `Continuous2DFunction` in the GBn forces instead of the `Discrete2DFunction`.  IMO, the results it gives are just as good if not better agreement with Amber (esp. in the forces), agreement with "standard" radii doesn't get any worse, and this really is the intended implementation if you look at the original GBneck paper.

The behavior deviates from how Amber implements it, but clearly so does all other implementations here, anyway.

**Pull request merged**
