### PR TITLE
CompoundIntegrator::stateChanged() calls through to component integrators

### PR DESCRIPTION
**Pull request by peastman**
Fixes https://github.com/choderalab/openmmtools/issues/118.

### CODE REVIEW

**Comment by jchodera** [comment]
Thanks!

**Comment by jchodera** [comment]
We can test again once this is merged and the `dev` build rebuilds.

**Comment by gregoryross** [comment]
Thanks so much for your fast response! You're fix looks good. @peastman, would you mind merging this so I can test this on the `dev` build as I'm still having trouble compiling `openmm` from source.

**Comment by jchodera** [comment]
I've retriggered the nighly build, so it should update shortly:
https://anaconda.org/omnia/openmm/files

**Comment by gregoryross** [comment]
Thanks!

**Pull request merged**
