### PR TITLE
Update appveyor.yml

### PR DESCRIPTION
**Pull request by rmcgibbo**

### CODE REVIEW

**Comment by peastman** [comment]
Why are we now getting two different set of travis builds?

**Comment by rmcgibbo** [comment]
I have no idea. Maybe https://github.com/travis-ci/travis-ci/issues/3241?

**Comment by mpharrigan** [comment]
Could be because the branch is in this repo instead of a fork like normal

**Comment by rmcgibbo** [comment]
Oh right. I just made it through the web ui.

**Comment by rmcgibbo** [comment]
this got messed up. reopening a new one.

**Pull request closed without merging**
