### PR TITLE
Add elapsed time column in statedatareporter

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
PS: my use case for this is correlating observables with wall clock time as a measure of sampling efficiency.

**Comment by swails** [comment]
+1

**Comment by jchodera** [comment]
+1

**Comment by peastman** [comment]
I see you're writing the elapsed time in a different format than time remaining.  Is that intentional?  Would it make more sense to use the same format for both?

**Comment by kyleabeauchamp** [comment]
I guess I find seconds to be most intuitive to parse and use for my purposes, but I can be flexible.  For example, here is my output and analysis workflow:

```
kyleb@kyleb-DX4870:~/src/kyleabeauchamp/HMCNotes$ head data/mixed_alanine_LangevinIntegrator_2.000_100.csv 
#"Step","Time (ps)","Potential Energy (kJ/mole)","Temperature (K)","Density (g/mL)","Elapsed Time (s)"
250,0.5,-128.750662174,335.629864539,0.0299262299353,0.000486135482788
500,1.0,-110.278975893,282.891012163,0.0299262299353,0.0405340194702
750,1.5,-116.162421457,351.069457215,0.0299262299353,0.0765290260315
1000,2.0,-122.055149854,279.377111366,0.0299262299353,0.107105970383
1250,2.5,-71.8858504798,312.448293434,0.0299262299353,0.136034011841
1500,3.0,-109.905863909,377.003302288,0.0299262299353,0.166398048401
1750,3.5,-109.477079985,281.783014721,0.0299262299353,0.196824073792
2000,4.0,-111.744609892,205.340526053,0.0299262299353,0.227587938309
2250,4.5,-112.795592543,429.930643583,0.0299262299353,0.256407976151
```

```
import pandas as pd

In [2]: pd.read_csv("./data/mixed_alanine_LangevinIntegrator_2.000_100.csv")[0:5]
Out[2]: 
   #"Step"  Time (ps)  Potential Energy (kJ/mole)  Temperature (K)  \
0      250        0.5                 -128.750662       335.629865   
1      500        1.0                 -110.278976       282.891012   
2      750        1.5                 -116.162421       351.069457   
3     1000        2.0                 -122.055150       279.377111   
4     1250        2.5                  -71.885850       312.448293   

   Density (g/mL)  Elapsed Time (s)  
0        0.029926          0.000486  
1        0.029926          0.040534  
2        0.029926          0.076529  
3        0.029926          0.107106  
4        0.029926          0.136034  
```

**Comment by swails** [comment]
> I see you're writing the elapsed time in a different format than time remaining. Is that intentional? Would it make more sense to use the same format for both?

I can see the arguments for allowing them to be different:

Remaining time is printed out for humans to make sense/use of.  Elapsed time is more interesting for efficiency measurements, so a machine would probably be more likely to read and process that information.

**Comment by peastman** [comment]
That sounds reasonable.  The use of different formats offends my aesthetic sensibilities :), but I don't feel strongly about it.  So if seconds is more useful, let's stick with that.

**Pull request merged**
