### PR TITLE
Fix errors in sphinx formatting for docs

### PR DESCRIPTION
**Pull request by jchodera**

### CODE REVIEW

**Comment by jchodera** [comment]
These were my fault.

**Comment by swails** [comment]
It's weird seeing Travis always fail and appveyor do fine.

**Comment by jchodera** [comment]
Looks like those are `OpenCL` failures that are unrelated to this PR:
```
******************************
Rerunning failing tests...
******************************
Test project /home/travis/build/pandegroup/openmm
    Start 76: TestOpenCLCustomManyParticleForceSingle
1/2 Test #76: TestOpenCLCustomManyParticleForceSingle ...***Exception: SegFault 19.12 sec
    Start 78: TestOpenCLCustomManyParticleForceDouble
2/2 Test #78: TestOpenCLCustomManyParticleForceDouble ...***Failed   20.00 sec
exception: Assertion failure at TestCustomManyParticleForce.h:705.  Expected 107521, found 2.77347e+06
```

**Comment by jchodera** [comment]
(AppVeyor doesn't have OpenCL, I don't think.)

**Pull request merged**
