### PR TITLE
Support multiple NonbondedForces in one System 

### LINKED ISSUE #2082: Failure to compile OpenCL kernels
As I was putting some finishing touches on exception fixes, I ended up with an unusual error (at bottom, it's quite long). The code I used to reproduce this error is here:

```python
import numpy as np
from simtk import openmm, unit

hybrid_positions = np.load("hybrid_positions.npy")

with open("hybrid_system.xml", 'r') as infile:
    hybrid_system = openmm.XmlSerializer.deserialize(infile.read())

integrator = openmm.VerletIntegrator(1.0*unit.femtoseconds)
platform = openmm.Platform.getPlatformByName("OpenCL")
ctx = openmm.Context(hybrid_system, integrator, platform)
ctx.setPositions(hybrid_positions)

openmm.LocalEnergyMinimizer.minimize(ctx)


```
Version '7.2.0.dev-69aa676'

Compressed files to use for input:
[hybrid_system.tar.gz](https://github.com/pandegroup/openmm/files/2033272/hybrid_system.tar.gz)

[hybrid_positions.tar.gz](https://github.com/pandegroup/openmm/files/2033273/hybrid_positions.tar.gz)

```
OpenCL internal error: [CL_DEVICE_NOT_AVAILABLE] : OpenCL Error : Error: Build Program driver returned (10015)
OpenCL internal error: OpenCL Warning : clBuildProgram failed: could not build program for 0x1024500 (HD Graphics 5000) (err:-2)
OpenCL internal error: [CL_BUILD_ERROR] : OpenCL Build Error : Compiler build log:
<program source>:57:7: error: duplicate member 'sigmaEpsilon_x'
float sigmaEpsilon_x;
      ^
<program source>:55:11: note: previous declaration is here
    float sigmaEpsilon_x;
          ^
<program source>:58:7: error: duplicate member 'sigmaEpsilon_y'
float sigmaEpsilon_y;
      ^
<program source>:56:7: note: previous declaration is here
float sigmaEpsilon_y;
      ^
<program source>:81:96: error: redefinition of parameter 'global_sigmaEpsilon'
        , __global const float2* restrict global_sigmaEpsilon, __global const float2* restrict global_sigmaEpsilon) {
                                                                                               ^
<program source>:81:43: note: previous declaration is here
        , __global const float2* restrict global_sigmaEpsilon, __global const float2* restrict global_sigmaEpsilon) {
                                          ^
<program source>:81:96: error: parameter name omitted
        , __global const float2* restrict global_sigmaEpsilon, __global const float2* restrict global_sigmaEpsilon) {
                                                                                               ^
<program source>:102:8: error: redefinition of 'sigmaEpsilon1'
float2 sigmaEpsilon1 = global_sigmaEpsilon[atom1];
       ^
<program source>:101:16: note: previous definition is here
        float2 sigmaEpsilon1 = global_sigmaEpsilon[atom1];
               ^
<program source>:133:8: error: redefinition of 'sigmaEpsilon2'
float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
       ^
<program source>:132:24: note: previous definition is here
                float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
                       ^
<program source>:194:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
        if (1-erfcAlphaR > 1e-6) {
                           ^
<program source>:324:8: error: redefinition of 'temp_sigmaEpsilon'
float2 temp_sigmaEpsilon = global_sigmaEpsilon[j];
       ^
<program source>:321:20: note: previous definition is here
            float2 temp_sigmaEpsilon = global_sigmaEpsilon[j];
                   ^
<program source>:350:8: error: redefinition of 'sigmaEpsilon2'
float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
       ^
<program source>:349:28: note: previous definition is here
                    float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
                           ^
<program source>:411:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
        if (1-erfcAlphaR > 1e-6) {
                           ^
<program source>:633:8: error: redefinition of 'sigmaEpsilon1'
float2 sigmaEpsilon1 = global_sigmaEpsilon[atom1];
       ^
<program source>:632:20: note: previous definition is here
            float2 sigmaEpsilon1 = global_sigmaEpsilon[atom1];
                   ^
<program source>:651:8: error: redefinition of 'temp_sigmaEpsilon'
float2 temp_sigmaEpsilon = global_sigmaEpsilon[j];
       ^
<program source>:648:24: note: previous definition is here
                float2 temp_sigmaEpsilon = global_sigmaEpsilon[j];
                       ^
<program source>:686:8: error: redefinition of 'sigmaEpsilon2'
float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
       ^
<program source>:685:32: note: previous definition is here
                        float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
                               ^
<program source>:747:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
        if (1-erfcAlphaR > 1e-6) {
                           ^
<program source>:892:8: error: redefinition of 'sigmaEpsilon2'
float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
       ^
<program source>:891:32: note: previous definition is here
                        float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
                               ^
<program source>:953:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
        if (1-erfcAlphaR > 1e-6) {
                           ^
<program source>:94:44: warning: comparison of integers of different signs: 'int' and 'const unsigned int'
    for (int pos = firstExclusionTile; pos < lastExclusionTile; pos++) {
                                       ~~~ ^ ~~~~~~~~~~~~~~~~~
<program source>:154:64: warning: comparison of integers of different signs: 'unsigned int' and 'int'
    bool needCorrection = hasExclusions && isExcluded && atom1 != atom2 && atom1 < NUM_ATOMS && atom2 < NUM_ATOMS;
                                                         ~~~~~ ^  ~~~~~
<program source>:371:64: warning: comparison of integers of different signs: 'unsigned int' and 'int'
    bool needCorrection = hasExclusions && isExcluded && atom1 != atom2 && atom1 < NUM_ATOMS && atom2 < NUM_ATOMS;
                                                         ~~~~~ ^  ~~~~~
<program source>:707:64: warning: comparison of integers of different signs: 'unsigned int' and 'int'
    bool needCorrection = hasExclusions && isExcluded && atom1 != atom2 && atom1 < NUM_ATOMS && atom2 < NUM_ATOMS;
                                                         ~~~~~ ^  ~~~~~
<program source>:913:64: warning: comparison of integers of different signs: 'unsigned int' and 'int'
    bool needCorrection = hasExclusions && isExcluded && atom1 != atom2 && atom1 < NUM_ATOMS && atom2 < NUM_ATOMS;
                                                         ~~~~~ ^  ~~~~~


Traceback (most recent call last):
  File "reproduce_failure.py", line 14, in <module>
    openmm.LocalEnergyMinimizer.minimize(ctx)
  File "/Users/grinawap/anaconda3/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 15129, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
Exception: Error compiling kernel: <program source>:57:7: error: duplicate member 'sigmaEpsilon_x'
float sigmaEpsilon_x;
      ^
<program source>:55:11: note: previous declaration is here
    float sigmaEpsilon_x;
          ^
<program source>:58:7: error: duplicate member 'sigmaEpsilon_y'
float sigmaEpsilon_y;
      ^
<program source>:56:7: note: previous declaration is here
float sigmaEpsilon_y;
      ^
<program source>:81:96: error: redefinition of parameter 'global_sigmaEpsilon'
        , __global const float2* restrict global_sigmaEpsilon, __global const float2* restrict global_sigmaEpsilon) {
                                                                                               ^
<program source>:81:43: note: previous declaration is here
        , __global const float2* restrict global_sigmaEpsilon, __global const float2* restrict global_sigmaEpsilon) {
                                          ^
<program source>:81:96: error: parameter name omitted
        , __global const float2* restrict global_sigmaEpsilon, __global const float2* restrict global_sigmaEpsilon) {
                                                                                               ^
<program source>:102:8: error: redefinition of 'sigmaEpsilon1'
float2 sigmaEpsilon1 = global_sigmaEpsilon[atom1];
       ^
<program source>:101:16: note: previous definition is here
        float2 sigmaEpsilon1 = global_sigmaEpsilon[atom1];
               ^
<program source>:133:8: error: redefinition of 'sigmaEpsilon2'
float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
       ^
<program source>:132:24: note: previous definition is here
                float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
                       ^
<program source>:194:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
        if (1-erfcAlphaR > 1e-6) {
                           ^
<program source>:324:8: error: redefinition of 'temp_sigmaEpsilon'
float2 temp_sigmaEpsilon = global_sigmaEpsilon[j];
       ^
<program source>:321:20: note: previous definition is here
            float2 temp_sigmaEpsilon = global_sigmaEpsilon[j];
                   ^
<program source>:350:8: error: redefinition of 'sigmaEpsilon2'
float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
       ^
<program source>:349:28: note: previous definition is here
                    float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
                           ^
<program source>:411:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
        if (1-erfcAlphaR > 1e-6) {
                           ^
<program source>:633:8: error: redefinition of 'sigmaEpsilon1'
float2 sigmaEpsilon1 = global_sigmaEpsilon[atom1];
       ^
<program source>:632:20: note: previous definition is here
            float2 sigmaEpsilon1 = global_sigmaEpsilon[atom1];
                   ^
<program source>:651:8: error: redefinition of 'temp_sigmaEpsilon'
float2 temp_sigmaEpsilon = global_sigmaEpsilon[j];
       ^
<program source>:648:24: note: previous definition is here
                float2 temp_sigmaEpsilon = global_sigmaEpsilon[j];
                       ^
<program source>:686:8: error: redefinition of 'sigmaEpsilon2'
float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
       ^
<program source>:685:32: note: previous definition is here
                        float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
                               ^
<program source>:747:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
        if (1-erfcAlphaR > 1e-6) {
                           ^
<program source>:892:8: error: redefinition of 'sigmaEpsilon2'
float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
       ^
<program source>:891:32: note: previous definition is here
                        float2 sigmaEpsilon2 = (float2) (localData[atom2].sigmaEpsilon_x, localData[atom2].sigmaEpsilon_y);
                               ^
<program source>:953:28: warning: double precision constant requires cl_khr_fp64, casting to single precision
        if (1-erfcAlphaR > 1e-6) {
                           ^
<program source>:94:44: warning: comparison of integers of different signs: 'int' and 'const unsigned int'
    for (int pos = firstExclusionTile; pos < lastExclusionTile; pos++) {
                                       ~~~ ^ ~~~~~~~~~~~~~~~~~
<program source>:154:64: warning: comparison of integers of different signs: 'unsigned int' and 'int'
    bool needCorrection = hasExclusions && isExcluded && atom1 != atom2 && atom1 < NUM_ATOMS && atom2 < NUM_ATOMS;
                                                         ~~~~~ ^  ~~~~~
<program source>:371:64: warning: comparison of integers of different signs: 'unsigned int' and 'int'
    bool needCorrection = hasExclusions && isExcluded && atom1 != atom2 && atom1 < NUM_ATOMS && atom2 < NUM_ATOMS;
                                                         ~~~~~ ^  ~~~~~
<program source>:707:64: warning: comparison of integers of different signs: 'unsigned int' and 'int'
    bool needCorrection = hasExclusions && isExcluded && atom1 != atom2 && atom1 < NUM_ATOMS && atom2 < NUM_ATOMS;
                                                         ~~~~~ ^  ~~~~~
<program source>:913:64: warning: comparison of integers of different signs: 'unsigned int' and 'int'
    bool needCorrection = hasExclusions && isExcluded && atom1 != atom2 && atom1 < NUM_ATOMS && atom2 < NUM_ATOMS;
                                                         ~~~~~ ^  ~~~~~

```

### PR DESCRIPTION
**Pull request by peastman**
Fixes #2082 and #2083

### CODE REVIEW

**Comment by peastman** [comment]
@swails something seems to be up with Jenkins again.  All the CUDA tests are failing with this error.

```
16:12:45 exception: Error launching CUDA compiler: 256
16:12:45 /usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"
16:12:45 
16:12:45 /usr/include/bits/floatn.h(73): error: identifier "__float128" is undefined
```

**Comment by swails** [comment]
Thanks for the ping.

I'm typically very proactive at keeping my system as up-to-date as possible, and for system packages I usually let my package manager do what it wants.  Well, it wanted to upgrade glibc to 2.26-r7, which is, apparently, [known to be incompatible with CUDA 8](https://github.com/caffe2/caffe2/issues/1194), but has the same problem with CUDA 9.1 (which is what I have installed on my machine).

I implemented the [hack fix described on that thread](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/cuda&id=ae90e4d243510e9565e66e9e8e08c509f5719fe0) and tested `TestCudaHarmonicBondForce single`, and that fixed the error.  I was alerted to the same issue with Amber's CUDA code as well, which I have testing in that Jenkins instance.

I retriggered Jenkins just now, and I expect that things should be back to normal.

**Comment by swails** [comment]
The build worked -- it claimed that it failed to set the build status, but I don't see how that's true.

I may have added a step in the build recipe that's unnecessary.  I removed it and will rerun the tests.  But this is good to merge.

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
Latest build just worked.  I had added an extra notification to the end of the job which is unnecessary (GHPRB plugin does that, I don't need to do it with the GitHub plugin separately).

**Pull request merged**
