### PR TITLE
addExtraParticles() can use bonds to select positions

### PR DESCRIPTION
**Pull request by peastman**
This is one piece of #1176.  It allows addExtraParticles() to work for multi-site ion models where several extra particles are connected to the atom (and to each other) by harmonic bonds.  @rafwiewiora and @jchodera could you take a look at this and see if it looks OK for your purposes?

### CODE REVIEW

**Comment by rafwiewiora** [comment]
Awesome, thanks @peastman! I'm going to have a more detailed look ASAP.

**Comment by jchodera** [comment]
Seems like it might work.

**Comment by peastman** [comment]
Shall I go ahead and merge this?

**Comment by jchodera** [comment]
@rafwiewiora: Does this meet your needs?

**Comment by rafwiewiora** [comment]
Sorry, too many talks this week - let me check this out now.

**Comment by rafwiewiora** [comment]
@peastman: looks like there's a problem with the addition of bonds to `newExtraPoints` and hence `system = forcefield.createSystem(newTopology, constraints=AllBonds)` can't be created (ZN residues do not match templates on bonds). 

Looking at the code it seems to me this is the issue: [here] (https://github.com/peastman/openmm/blob/extraparticles/wrappers/python/simtk/openmm/app/modeller.py#L1032) the central ZN's will be in `matchingAtoms`, but `matchingAtoms` is a template atom --> old topology dictionary, so you actually create a new topology extra point to old topology central Zn atom bond, right?

Now you can't use `newAtoms` either, because that's an old topology atom --> new topology atom dictionary. What you're missing and need here is a template atom --> new atom dictionary. Perhaps `newAtoms` could become that by changing: 

```python
for atom in residue.atoms():
    if atom.element is not None:
        newAtoms[atom] = newTopology.addAtom(atom.name, atom.element, newResidue)
        newPositions.append(deepcopy(self.positions[atom.index]))
```

to:

```python
for atom in template.atoms:
    if atom.element is not None:
        newAtoms[atom] = newTopology.addAtom(atom.name, atom.element, newResidue)
        newPositions.append(deepcopy(matchingAtoms[atom].index))
```

**Comment by rafwiewiora** [comment]
Also, thinking about this, it seems to me there's a certain redundancy here - you only add to `newTopology` those atoms from the old topology for which `atom.element is not None`, why not all `matchingAtoms`? If I load a PDB in which the dummy atoms already exist, this will recreate the `element == None` dummies and then have to SHAKE the positions - why not use the existing information already?

**Comment by peastman** [comment]
Do you have a test case that is failing?  The one I added to TestModeller is passing.

**Comment by peastman** [comment]
Ok, I figured out how to reproduce it.  I updated the test case and fixed the problem.

**Comment by rafwiewiora** [comment]
Awesome! Works like a charm! Here's applied to the 2-Zn cluster in 4H12:
untitled

Would you expect that any problems might arise with the SHAKE positioning, i.e. would this benefit from testing on a larger number of systems? Or is it a works on one, will work on all kind of thing?

**Comment by rafwiewiora** [comment]
Good to merge.

**Comment by peastman** [comment]
SHAKE is a pretty robust algorithm.  And in this case it doesn't need to produce perfect positions, just ones that are good enough not to cause problems for energy minimization.  So it will probably be fine, but keep an eye out for any problems.

**Pull request merged**
