### PR TITLE
fix swig build

### PR DESCRIPTION
**Pull request by xantares**

### CODE REVIEW

**Comment by swails** [comment]
What version of SWIG does the current version not work for?

**Comment by xantares** [comment]
305

**Comment by swails** [comment]
Weird. 3.0.5 worked for me...

**Comment by swails** [comment]
But I don't know SWIG that well and your changes appear to work on Travis, so thanks!

**Comment by peastman** [comment]
I'm using 3.0.5 and haven't seen any errors with it.  What error was it giving?

**Comment by xantares** [comment]
I've got this this error:
```
./swig_lib/python/extend.i:420: Error: Unknown SWIG preprocessor directive: Look (if this is a block of target language code, delimit it with %{ and %})
```

**Comment by peastman** [comment]
Strange.  No idea why it worked for me and not for you, but if this fixes it, great.

**Comment by swails** [comment]
Maybe @xantares is using a development version of SWIG?  I know that they've been pretty active on fixing Python-related bugs recently, some of which we've been relying on.  So it wouldn't completely surprise me if this is really an issue for the *next* SWIG release (whenever that will be).

**Comment by xantares** [comment]
@swails maybe yes

**Pull request merged**
