### PR TITLE
Hopefully improve the docstring so the generated docs will improve

### PR DESCRIPTION
**Pull request by swails**
See http://docs.openmm.org/development/api-python/generated/simtk.openmm.mtsintegrator.MTSIntegrator.html#
for the rendered results that are less than ideal.

### CODE REVIEW

**Comment by peastman** [comment]
Does Sphinx recognize \`\`\` syntax?  For what it's worth, I think the "recommended" way of marking code examples is just to indent them four spaces.

**Comment by rmcgibbo** [comment]
I think it will also come out correctly if you put it inside `<tt><pre>`, instead of just `<pre>`

**Comment by rmcgibbo** [comment]
But yeah, @peastman is right that "```" is Markdown syntax, not reStructuredText.

**Comment by swails** [comment]
Yea, I was hoping they'd be enough alike... :).  I'll switch to indentation.

Also, remember this isn't going through the doxygen translator, I don't think (since it's all living in pure Python).

**Comment by swails** [comment]
How does that look?

**Comment by rmcgibbo** [comment]
Right, but it does get piped through this code: https://github.com/pandegroup/openmm/blob/master/docs-source/api-python/process-docstring.py

**Comment by rmcgibbo** [comment]
untitled

**Comment by peastman** [comment]
Ok, that look good.

**Pull request merged**
