### PR TITLE
Fix segfault in swig wrappers

### PR DESCRIPTION
**Pull request by rmcgibbo**
The fix for #1214 is on line 472, because PyImport_AddModule gives a borrowed reference. The other decrefs are just fixing leaked references.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
I suspect it would speed things up slightly to have these imports done only once, statically, as is done by the unit stripping code at the top of the file.

**Comment by jchodera** [comment]
Would it be worthwhile to add a corresponding test?

**Comment by jchodera** [comment]
Maybe at least this one?
```python
from simtk import unit, openmm                                                                                                                                                                 
for i in range(100):                                                                                                                                                                       
    system = openmm.System()                                                                                                                                                                   
    box_vectors = system.getDefaultPeriodicBoxVectors()     
```

**Comment by peastman** [comment]
> I suspect it would speed things up slightly to have these imports done only once

Feel free to change that too if you want.

**Comment by rmcgibbo** [comment]
> Feel free to change that too if you want.

Will do.

**Comment by rmcgibbo** [comment]
Okay, I cleaned this up a little bit and factored some copy-paste code out into a function.

**Comment by jchodera** [comment]
Hooray!  Thanks!

**Pull request merged**
