### PR TITLE
Add error checking for the input GB radii in the GBn methods.

### PR DESCRIPTION
**Pull request by swails**
The radii must be between 1 and 2 Angstroms, or they fall outside the bounds of the neck lookup
tables.

At least on my Mac, this results in a C++ exception that does not get translated
into a Python exception (i.e., it is not catchable and crashes the application)

### CODE REVIEW

**Comment by peastman** [comment]
Looks like some test cases are failing.

**Comment by swails** [comment]
> Looks like some test cases are failing.

I used the wrong index.  I should have applied the WIP tag, apologies.

**Comment by peastman** [comment]
Ok, let us know when it's ready.

**Comment by swails** [comment]
I'm not declaring this 'ready' yet (but I doubt I will need any more changes).  The failure was a stochastic test that succeeded upon re-test.

**Comment by swails** [comment]
OK -- this seems to work correctly.  Good to go.

**Pull request merged**
