### PR TITLE
Nosé-Hoover thermostat

### PR DESCRIPTION
**Pull request by andysim**
I was chatting with somebody at a conference, who wanted a Nosé-Hoover thermostat to study transport properties, so I decided to code one up using the super-slick CustomIntegrator machinery.  Give the discussion on issue #1306 this may not be something you want, so feel free to close this PR.  The implementation uses the [reversible, higher-order MTS integration method](http://dx.doi.org/10.1080/00268979600100761) from Martyna and co-workers.  I arrived at the default parameters by testing on a couple of systems, but they may be overkill.  The only thing I'm not sure about is how to obtain the number of degrees of freedom; I have a janky solution implemented now, but it fails to account for translations and constraints.  Perhaps that could be provided as one of the automatic variables in `CustomIntegrator`?

### CODE REVIEW

**Comment by jchodera** [comment]
We've also been collecting integrators in [`openmmtools.integrators`](http://openmmtools.readthedocs.io/en/latest/integrators.html), though our focus has been on Langevin integrators that don't have all the pathologies that continuous thermostats share.

**Comment by andysim** [comment]
I agree that for most uses the Langevin integrators are ideal; this implementation came from the need to study transport properties, which Langevin integrators can't do.  If you're interested in adding NHC to openmmtools, you're free to copy/paste it, or I can slap an MIT license on the code, if that's what's needed legally.

**Comment by peastman** [comment]
Thanks!  @jchodera you were the one most negative about Nose-Hoover.  Would this be a good thing to put in OpenMM itself, or would `openmmtools.integrators` be a better place for it?  I agree NH is probably not a good choice for most people most of the time, but it does also have its uses.

**Comment by jchodera** [comment]
I think there are enough people interested in Nosé-Hoover that it's worth merging into OpenMM directly since the PR is already set up that way.

**Comment by peastman** [comment]
Ok, sounds reasonable.  Based on a quick scan the code looks pretty good.  I'll try to go through it in more detail shortly.

I notice you're using underscore separated names, or in some cases all lower case names with no separator, which isn't consistent with the rest of OpenMM.  For example, it should be `getCurrentTemperature()` instead of `get_current_temperature()`, `chainLength` instead of `chainlength`, `numYoshidaSuzuki` instead of `n_yoshidasuzuki`, etc.  I don't care about local variables or private fields, only things that are part of the public API.

**Comment by andysim** [comment]
Thanks for the feedback, guys.  I think we're all on the same page; this is designed to help with corner cases, rather than being a go-to tool for everyday use.  Therefore, if it's better suited to openmmtools, I'm happy to close this PR and launch a new one to that project.  I'm glad you noticed the camel case problem, @peastman; I was up late last night cleaning it up and changed everything from the correct convention to the underscores, for some unknown reason.  Will fix that now.

**Comment by jchodera** [comment]
How about we put it in `openmmtools.integrators`, then? I think there's utility in collecting them there until we decide how best to migrate a batch of stable `CustomIntegrator`s into OpenMM proper.

Notably, there's an issue we are still trying to find the best way to resolve: Subclasses of `CustomIntegrator` work very well, but swig-wrapped functions that retrieve the integrator (like `System.getIntegrator()`) return only the base `CustomIntegrator` class, losing any of the subclass methods. This can be surprising behavior and, at minimum, needs to be handled with some documentation. We can hopefully figure out a way to improve this behavior by improving the Swig interface at some point (or maybe migrating to pybind11).

**Comment by peastman** [comment]
That sounds like a reasonable plan.  I think I can fix `Context.getIntegrator()` pretty easily.  It already stores a reference to the Python integrator object to keep it from getting garbage collected, so I just need to replace `getIntegrator()` to make it return that object instead of creating a new Python object from the C++ integrator.

**Comment by bas-rustenburg** [comment]
Would a similar improvement be possible for `CompountIntegrator.getIntegrator()`? If I recall correctly, that also returns only a `CustomIntegrator`.

**Comment by peastman** [comment]
Probably.  I'll look into that too.

**Comment by andysim** [comment]
Closing this one, because it's been ported to [this PR](https://github.com/choderalab/openmmtools/pull/265) to openmmtools.

**Pull request closed without merging**
