### PR TITLE
Add check for null context inside integrator.step()

### LINKED ISSUE #957: Check context before integrator.step()?
So the following code causes a segmentation fault.  According to the source (https://github.com/pandegroup/openmm/blob/master/openmmapi/src/VerletIntegrator.cpp#L72), shouldn't it be easy enough to check that the context pointer is non-null before the `for` loop?

```
import simtk.openmm as mm
integrator = mm.VerletIntegrator(1.0)
integrator.step(1)
```

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
Fixes #957

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Test code:

```
import simtk.openmm as mm
import openmmtools

integrator = mm.VerletIntegrator(1.0)
integrator.step(1)

integrator = mm.VariableVerletIntegrator(1.0)
integrator.step(1)

integrator = mm.LangevinIntegrator(1.0, 1.0, 1.0)
integrator.step(1)

integrator = mm.VariableLangevinIntegrator(1.0, 1.0, 1.0)
integrator.step(1)

integrator = mm.VariableVerletIntegrator(1.0)
integrator.step(1)

integrator = openmmtools.integrators.HMCIntegrator()
integrator.step(1)
```

**Comment by peastman** [comment]
Looks good, but you're missing several integrators:

BrownianIntegrator
RPMDIntegrator
DrudeSCFIntegrator
DrudeLangevinIntegrator

**Comment by jchodera** [comment]
What about moving the check to the base `Integrator::step()` and having all the subclasses call this first?

**Comment by kyleabeauchamp** [comment]
If we're going to do that, then we should move *all* the shared code to the base class.  We can do this in a separate PR, as that breaks the current code layout.

**Comment by kyleabeauchamp** [comment]
Added remaining integrators

**Comment by peastman** [comment]
I think the test failure is a stochastic test that just happened to fail twice:

```
72: Test command: /home/travis/build/pandegroup/openmm/TestReferenceDrudeLangevinIntegrator
72: Test timeout computed to be: 1500
72: exception: Assertion failure at TestReferenceDrudeLangevinIntegrator.cpp:174.  Expected 203.333, found 207.612 (This test is stochastic and may occasionally fail)
```

**Pull request merged**
