### PR TITLE
Add appveyor.yml

### PR DESCRIPTION
**Pull request by rmcgibbo**
Ideally, this will be fast enough to be useful. See e.g. https://ci.appveyor.com/project/rmcgibbo/openmm/build/1.0.40

### CODE REVIEW

**Comment by peastman** [comment]
I see it reported a failure due to a stochastic test, and therefore never ran the python tests.  Can we make it handle those the same way travis does?

**Comment by rmcgibbo** [comment]
https://ci.appveyor.com/project/rmcgibbo/openmm/build/1.0.42

**Comment by peastman** [comment]
Looks like lots of Python tests failed.

**Comment by rmcgibbo** [comment]
We gotta lower the msvc warning level

**Comment by rmcgibbo** [comment]
Also it's not rerunning the failing test. It just reran all of the tests.

**Comment by peastman** [comment]
I'm working on that right now. :)

**Comment by rmcgibbo** [comment]
Python Failures: 
```
======================================================================
ERROR: Failure: ImportError (No module named 'numpy')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Python34-x64\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Python34-x64\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Python34-x64\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Python34-x64\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\Python34-x64\lib\imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\projects\openmm\build\python\tests\TestCheckpointReporter.py", line 3, in <module>
    import numpy as np
ImportError: No module named 'numpy'
 
======================================================================
ERROR: Failure: ImportError (No module named 'numpy')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Python34-x64\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Python34-x64\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Python34-x64\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Python34-x64\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\Python34-x64\lib\imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\projects\openmm\build\python\tests\TestNumpyCompatibility.py", line 2, in <module>
    import numpy as np
ImportError: No module named 'numpy'
 
======================================================================
ERROR: Failure: ImportError (No module named 'cStringIO')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python34-x64\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Python34-x64\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Python34-x64\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Python34-x64\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Python34-x64\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\Python34-x64\lib\imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\projects\openmm\build\python\tests\TestPdbFile.py", line 6, in <module>
    import cStringIO
ImportError: No module named 'cStringIO'
 
======================================================================
ERROR: test_createCheckpoint (TestBytes.TestBytes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\openmm\build\python\tests\TestBytes.py", line 21, in test_createCheckpoint
    context.loadCheckpoint(chk)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\openmm.py", line 3853, in loadCheckpoint
    return _openmm.Context_loadCheckpoint(self, *args)
TypeError: in method 'Context_loadCheckpoint', argument 2 of type 'std::string'
 
======================================================================
ERROR: Check that an amber simulation like the docs example works with a DCD reporter.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\openmm\build\python\tests\TestAmberPrmtopFile.py", line 318, in test_with_dcd_reporter
    os.remove(fname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpyutwc09c.dcd'
 
======================================================================
ERROR: Test to make sure the nonbondedCutoff parameter is passed correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\openmm\build\python\tests\TestGromacsTopFile.py", line 16, in setUp
    self.top1 = GromacsTopFile('systems/explicit.top', unitCellDimensions=Vec3(6.223, 6.223, 6.223)*nanometers)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 475, in __init__
    self._processFile(file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 125, in _processFile
    self._processLine(append+' '+line, file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 162, in _processLine
    raise ValueError('Could not locate #include file: '+name)
ValueError: Could not locate #include file: amber99sb.ff/forcefield.itp
 
======================================================================
ERROR: Test to make sure the ewaldErrorTolerance parameter is passed correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\openmm\build\python\tests\TestGromacsTopFile.py", line 16, in setUp
    self.top1 = GromacsTopFile('systems/explicit.top', unitCellDimensions=Vec3(6.223, 6.223, 6.223)*nanometers)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 475, in __init__
    self._processFile(file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 125, in _processFile
    self._processLine(append+' '+line, file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 162, in _processLine
    raise ValueError('Could not locate #include file: '+name)
ValueError: Could not locate #include file: amber99sb.ff/forcefield.itp
 
======================================================================
ERROR: Test that altering the mass of hydrogens works correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\openmm\build\python\tests\TestGromacsTopFile.py", line 16, in setUp
    self.top1 = GromacsTopFile('systems/explicit.top', unitCellDimensions=Vec3(6.223, 6.223, 6.223)*nanometers)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 475, in __init__
    self._processFile(file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 125, in _processFile
    self._processLine(append+' '+line, file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 162, in _processLine
    raise ValueError('Could not locate #include file: '+name)
ValueError: Could not locate #include file: amber99sb.ff/forcefield.itp
 
======================================================================
ERROR: Test implicit solvent using the implicitSolvent parameter.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\openmm\build\python\tests\TestGromacsTopFile.py", line 16, in setUp
    self.top1 = GromacsTopFile('systems/explicit.top', unitCellDimensions=Vec3(6.223, 6.223, 6.223)*nanometers)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 475, in __init__
    self._processFile(file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 125, in _processFile
    self._processLine(append+' '+line, file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 162, in _processLine
    raise ValueError('Could not locate #include file: '+name)
ValueError: Could not locate #include file: amber99sb.ff/forcefield.itp
 
======================================================================
ERROR: Test that solventDielectric and soluteDielectric are passed correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\openmm\build\python\tests\TestGromacsTopFile.py", line 16, in setUp
    self.top1 = GromacsTopFile('systems/explicit.top', unitCellDimensions=Vec3(6.223, 6.223, 6.223)*nanometers)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 475, in __init__
    self._processFile(file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 125, in _processFile
    self._processLine(append+' '+line, file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 162, in _processLine
    raise ValueError('Could not locate #include file: '+name)
ValueError: Could not locate #include file: amber99sb.ff/forcefield.itp
 
======================================================================
ERROR: Test all five options for the nonbondedMethod parameter.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\openmm\build\python\tests\TestGromacsTopFile.py", line 16, in setUp
    self.top1 = GromacsTopFile('systems/explicit.top', unitCellDimensions=Vec3(6.223, 6.223, 6.223)*nanometers)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 475, in __init__
    self._processFile(file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 125, in _processFile
    self._processLine(append+' '+line, file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 162, in _processLine
    raise ValueError('Could not locate #include file: '+name)
ValueError: Could not locate #include file: amber99sb.ff/forcefield.itp
 
======================================================================
ERROR: Test both options (True and False) for the removeCMMotion parameter.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\openmm\build\python\tests\TestGromacsTopFile.py", line 16, in setUp
    self.top1 = GromacsTopFile('systems/explicit.top', unitCellDimensions=Vec3(6.223, 6.223, 6.223)*nanometers)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 475, in __init__
    self._processFile(file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 125, in _processFile
    self._processLine(append+' '+line, file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 162, in _processLine
    raise ValueError('Could not locate #include file: '+name)
ValueError: Could not locate #include file: amber99sb.ff/forcefield.itp
 
======================================================================
ERROR: Test all eight options for the constraints and rigidWater parameters.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\openmm\build\python\tests\TestGromacsTopFile.py", line 16, in setUp
    self.top1 = GromacsTopFile('systems/explicit.top', unitCellDimensions=Vec3(6.223, 6.223, 6.223)*nanometers)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 475, in __init__
    self._processFile(file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 125, in _processFile
    self._processLine(append+' '+line, file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 162, in _processLine
    raise ValueError('Could not locate #include file: '+name)
ValueError: Could not locate #include file: amber99sb.ff/forcefield.itp
 
======================================================================
ERROR: Test Gromacs topology #define replacement as used in ff99SB-ILDN
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\openmm\build\python\tests\TestGromacsTopFile.py", line 16, in setUp
    self.top1 = GromacsTopFile('systems/explicit.top', unitCellDimensions=Vec3(6.223, 6.223, 6.223)*nanometers)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 475, in __init__
    self._processFile(file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 125, in _processFile
    self._processLine(append+' '+line, file)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\gromacstopfile.py", line 162, in _processLine
    raise ValueError('Could not locate #include file: '+name)
ValueError: Could not locate #include file: amber99sb.ff/forcefield.itp
 
======================================================================
ERROR: Tests the PDBxReporter with PBC
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\openmm\build\python\tests\TestPdbxFile.py", line 114, in testReporterExplicit
    os.unlink('test.cif')
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'test.cif'
 
======================================================================
ERROR: Tests the PDBxReporter without PBC
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\openmm\build\python\tests\TestPdbxFile.py", line 73, in testReporterImplicit
    os.unlink('test.cif')
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'test.cif'
 
======================================================================
ERROR: Test that checkpointing works correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\openmm\build\python\tests\TestSimulation.py", line 39, in testCheckpointing
    simulation.loadCheckpoint(filename)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\simulation.py", line 203, in loadCheckpoint
    self.context.loadCheckpoint(f.read())
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\openmm.py", line 3853, in loadCheckpoint
    return _openmm.Context_loadCheckpoint(self, *args)
TypeError: in method 'Context_loadCheckpoint', argument 2 of type 'std::string'
 
======================================================================
ERROR: Test the runForClockTime() method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\openmm\build\python\tests\TestSimulation.py", line 131, in testRunForClockTime
    simulation.loadCheckpoint(checkpointFile)
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\app\simulation.py", line 203, in loadCheckpoint
    self.context.loadCheckpoint(f.read())
  File "C:\Python34-x64\lib\site-packages\simtk\openmm\openmm.py", line 3853, in loadCheckpoint
    return _openmm.Context_loadCheckpoint(self, *args)
TypeError: in method 'Context_loadCheckpoint', argument 2 of type 'std::string'
 
----------------------------------------------------------------------
Ran 154 tests in 100.172s
```

**Comment by rmcgibbo** [comment]
Let's merge and fix these separately. Many should just be extra skips.

**Comment by peastman** [comment]
Ok.

**Comment by rmcgibbo** [comment]
okay. i'll enable appveyor on this repo and disable it on my fork.

**Comment by rmcgibbo** [comment]
@peastman the reason that it's queued a lot is that for OSS, they rate limit it to one concurrent build _per account_ (source: https://twitter.com/appveyor/status/631636487398776832). The problem here is that I set this up under my account, which is also where the MSMBuilder and MDTraj appveyors are set up, so this was waiting behind some of @mpharrigan's PRs into MSMBuilder.

We should disable it from my account, and set it up under yours, since I assume that you don't have other ones.

**Comment by peastman** [comment]
I created an account.  How do we transfer it over?

**Comment by rmcgibbo** [comment]
Go to https://ci.appveyor.com/projects, and just create a new project pointing to pandegroup/openmm. I deleted  the project from my account on appveyor.

**Comment by peastman** [comment]
Done!  We'll see how it works.

**Comment by rmcgibbo** [comment]
Looks like it's starting to run. Do you want to add a badge link to the README.md file?

**Comment by peastman** [comment]
Once we actually get to the point where AppVeyor is capable of passing.

It's really slow.  Even after it starts running, it takes about half an hour to complete.  I don't think that's their fault though.  Building on Windows is just really, really slow.

**Comment by jchodera** [comment]
From the FAQ:
> What hardware is used to run builds?
> Every build job runs on a pristine virtual machine provisioned just for this build. "Basic" and "Free" plans run builds on "Azure" environment where each build worker has 1 CPU core and 1.75 GB of RAM ("Small" instance). "Pro" and "Premium" plans run builds on dedicated hardware with faster CPUs, SSD drives, 1 GB network uplink and use Hyper-V for creating isolated build workers.

I guess that means we would need the "Pro" plan to make it go faster.

**Comment by peastman** [comment]
If it's only $19/month, that sounds very worthwhile to me.

**Comment by rmcgibbo** [comment]
Kind of depends how much faster it actually goes.

**Pull request merged**
