### PR TITLE
added XML File classes

### PR DESCRIPTION
**Pull request by cxhernandez**
Should make it simpler for users to load XML files.

### CODE REVIEW

**Comment by peastman** [comment]
What is the intended use of this class?  I don't think I understand it.

**Comment by cxhernandez** [comment]
My understanding of the python API is that if I wanted to load in any sort of XML file to start a simulation, I would have to execute this three times:

``` python
with open(filename, 'rb') as f:
    xmlfile = XmlSerializer.deserialize(f.read())
```

As a beginner, this was not immediately obvious/intuitive to me, and I thought it'd be nice to have functions with the same ease-of-use as PDBFile.

Another suggestion that @mpharrigan had was to define a `load_from_xml` module for the `Simulation` object, which would initialize a simulation from the state, system, and integrator xml files.

**Comment by mpharrigan** [comment]
Yes, I think a class method
```python
simulation = Simulation.from_xml('system.xml', 'integrator.xml', 'state.xml')
```
 would be swell

**Comment by swails** [comment]
Do we still want to make a `from_xml` constructor on `Simulation`?  If so, I'll write up a PR for it if nobody else wants to.  But it seems like we're not moving forward with what's in this PR currently, right?

**Comment by cxhernandez** [comment]
+1 for `from_xml`

I would write the PR but I'm not entirely sure how to gracefully circumvent the `Topology` requirement that the `Simulation` class currently has.

**Comment by swails** [comment]
Ah, turns out to be easy :smiley:.  The `Topology` is no longer needed.  The only thing it's there for is to determine whether or not PBCs are used.  But this is now accessible through `System.usesPeriodicBoundaryConditions()`.

There is still one incredibly obscure corner case where it's better to use `topology.getUnitCellDimensions()` instead of `system.usesPeriodicBoundaryConditions()`, but for 99.9% of cases, the latter is actually better.

That corner case is when someone uses a plugin `Force` they wrote that doesn't implement `usesPeriodicBoundaryConditions`.  If that's the case, and their system is *not* periodic (as defined by some other `Force` in the system), then you get an exception thrown.

I'll put together a PR.

**Comment by mpharrigan** [comment]
Isn't the topology still used for (certain) reporters?

**Comment by jchodera** [comment]
I wonder if we need an XML representation for `Topology` as well.

**Comment by swails** [comment]
> Isn't the topology still used for (certain) reporters?

Sure, but that has nothing to do with `Simulation`

**Comment by swails** [comment]
Have a look at #1370 which implements my ideas.

**Comment by peastman** [comment]
> Sure, but that has nothing to do with Simulation

It has lots to do with Simulation.  If you set `topology` to `None` and then add a PDBReporter, PDBxReporter, or DCDReporter, you'll get an exception.  `None` is not a supported value for that field, and other classes rely on that.

**Comment by swails** [comment]
Oh because those reporters take Simulation as an input parameter...  I forgot about that!

My bad... Yea, I'll need to rethink this a bit.

**Comment by swails** [comment]
A Topology can always be constructed from the System, but it won't have as much information attached to it (but it will have enough for all of the reporters in OpenMM if I recall correctly).

**Comment by peastman** [comment]
Not if you want to write out a valid PDB or PDBx file.  The System has no information about atom or residue names, or how the atoms are grouped into residues.  Or elements, though you could try to guess those from the masses.

**Comment by swails** [comment]
Good point. Ok. I'm done replying about omm details from my phone :). How about I just remove the fromXmlFiles constructor for now and keep the additions of being able to accept XML files in the constructor? Is that a decent addition?

**Comment by mpharrigan** [comment]
> How about I just remove the fromXmlFiles constructor for now and keep the additions of being able to accept XML files in the constructor? Is that a decent addition?

Sounds like a good improvement to me!

**Comment by peastman** [comment]
Sounds reasonable.

**Comment by cxhernandez** [comment]
+1

**Comment by swails** [comment]
#1370 was merged, so this can probably be closed now...

**Pull request closed without merging**
