### PR TITLE
Added new Amber and CHARMM force fields

### PR DESCRIPTION
**Pull request by peastman**
At long last!  Look this over and see if everything looks OK: the files I've chosen to include, the way I've named and organized them, and the documentation.

### CODE REVIEW

**Comment by peastman** [comment]
@swails Jenkins builds seem to be broken again (but only the CUDA 9.0 ones).

**Comment by jchodera** [comment]
Note there are just placeholder references for the ipolq forcefields. @rafwiewiora will fix this, but you'll need to copy over the new files.

cc: https://github.com/pandegroup/openmm/issues/1611#issuecomment-347668514

**Comment by peastman** [comment]
No problem, I'll do that when they're ready.

**Comment by peastman** [comment]
Is it ok if I merge this?  It's blocking other things.  Once @rafwiewiora fixes the references we can change them in a separate PR.

Does anyone see any other problems with this?

**Comment by jchodera** [comment]
Go for it.

**Pull request merged**
