### PR TITLE
Optimized initializing interaction groups

### PR DESCRIPTION
**Pull request by peastman**
When using a CustomNonbondedForce with large interaction groups, creating the Context should now be a lot faster.  See the discussion in #2014.

### CODE REVIEW

**Comment by jchodera** [comment]
@peastman: Did you just peel off part of #2014 for this PR, or is this a separate implementation from the one in #2014?

**Comment by jchodera** [comment]
Oh! This is further optimization!

**Comment by peastman** [comment]
Just for you!  #2014 optimized computing forces.  This optimizes creating the Context.

**Comment by jchodera** [comment]
Do you want this benchmarked before merging?

**Comment by peastman** [comment]
Sure, if you want to.

**Comment by jchodera** [comment]
It's a bit of a pain to convert the build machinery to test this branch, but if you merge it, the dev package will automatically get built with `master` and I can give you updated benchmarks in the morning!

**Comment by peastman** [comment]
Ok, that's fine.

**Comment by jchodera** [comment]
I've just tested this, and get the following error:
```
[chodera@lilac:openmmtools]$ python cnbtiming2.py
HostGuestExplicit
126 solute atoms, 4365 solvent atoms
3.2893431387452243 /nm
Creating Context...
Traceback (most recent call last):
  File "cnbtiming2.py", line 109, in <module>
    context = openmm.Context(system, integrator)
  File "/home/chodera/miniconda/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 11936, in __init__
    this = _openmm.new_Context(*args)
Exception: Error uploading array rebuildNeighborList: The specified vector does not match the size of the array
```
Here's the code to reproduce:
```
#!/bin/env python

from simtk import openmm, unit
from simtk.openmm import app
from openmmtools import testsystems, integrators
from openmmtools.constants import ONE_4PI_EPS0
import mdtraj as md
import numpy as np
import copy
import time

#t = testsystems.SrcExplicit(nonbondedMethod=app.PME)
#t = testsystems.DHFRExplicit(nonbondedMethod=app.PME)
t = testsystems.HostGuestExplicit(nonbondedMethod=app.PME)
system, positions, topology = t.system, t.positions, t.topology
print(t.__class__.__name__)

def create_solute_forces(nonbonded_force, solvent, solute, switch_width=None):
    """
    Create CustomNonbondedForce to capture solute-solute and solute-solvent interactions.
    Assumes PME is in use.
    """

    # Determine PME parameters from nonbonded_force
    cutoff_distance = nonbonded_force.getCutoffDistance()
    [alpha_ewald, nx, ny, nz] = nonbonded_force.getPMEParameters()
    if (alpha_ewald/alpha_ewald.unit) == 0.0:
        # If alpha is 0.0, alpha_ewald is computed by OpenMM from from the error tolerance
        tol = nonbonded_force.getEwaldErrorTolerance()
        alpha_ewald = (1.0/cutoff_distance) * np.sqrt(-np.log(2.0*tol))        
    print(alpha_ewald)

    # Create CustomNonbondedForce
    energy_expression  = "(4*epsilon*((sigma/r)^12 - (sigma/r)^6) + ONE_4PI_EPS0*chargeprod*erfc(alpha_ewald*r)/r);"
    energy_expression += "epsilon = epsilon1*epsilon2;"
    energy_expression += "sigma = 0.5*(sigma1+sigma2);"
    energy_expression += "ONE_4PI_EPS0 = {:f};".format(ONE_4PI_EPS0)  # already in OpenMM units
    energy_expression += "chargeprod = charge1*charge2;"
    energy_expression += "alpha_ewald = {:f};".format(alpha_ewald.value_in_unit_system(unit.md_unit_system))
    custom_nonbonded_force = openmm.CustomNonbondedForce(energy_expression)
    custom_nonbonded_force.addPerParticleParameter('charge')
    custom_nonbonded_force.addPerParticleParameter('sigma')
    custom_nonbonded_force.addPerParticleParameter('epsilon')
    #custom_nonbonded_force.addInteractionGroup(solute, solute)
    custom_nonbonded_force.addInteractionGroup(solute, solvent)

    # Configure force
    custom_nonbonded_force.setNonbondedMethod(openmm.CustomNonbondedForce.CutoffPeriodic)
    custom_nonbonded_force.setCutoffDistance(cutoff_distance)
    custom_nonbonded_force.setUseLongRangeCorrection(False)
    if switch_width is not None:
        custom_nonbonded_force.setUseSwitchingFunction(True)
        custom_nonbonded_force.setSwitchingDistance(cutoff_distance - switch_width)
    else:  # Truncated
        custom_nonbonded_force.setUseSwitchingFunction(False)

    # Create CustomBondForce for exceptions
    energy_expression  = "(4*epsilon*((sigma/r)^12 - (sigma/r)^6) + ONE_4PI_EPS0*chargeprod/r);"
    energy_expression += "ONE_4PI_EPS0 = {:f};".format(ONE_4PI_EPS0)  # already in OpenMM units
    custom_bond_force = openmm.CustomBondForce(energy_expression)
    custom_bond_force.addPerBondParameter('chargeprod')
    custom_bond_force.addPerBondParameter('sigma')
    custom_bond_force.addPerBondParameter('epsilon')

    # Copy particles
    for particle_index in range(nonbonded_force.getNumParticles()):
        [charge, sigma, epsilon] = nonbonded_force.getParticleParameters(particle_index)
        custom_nonbonded_force.addParticle([charge, sigma, epsilon])

    # Copy solute-solute exclusions
    for exception_index in range(nonbonded_force.getNumExceptions()):
        [iatom, jatom, chargeprod, sigma, epsilon] = nonbonded_force.getExceptionParameters(exception_index)
        custom_nonbonded_force.addExclusion(iatom, jatom)      
        if (iatom in solute) and (jatom in solute):
            custom_bond_force.addBond(iatom, jatom, [chargeprod, sigma, epsilon])

    return custom_nonbonded_force, custom_bond_force

def create_negative_force(force):
    negative_force = copy.copy(force)
    energy_expression = '-1.0*{}'.format(force.getEnergyFunction())
    negative_force.setEnergyFunction(energy_expression)
    return negative_force

# Get solute and solvent indices
mdtraj_topology = md.Topology.from_openmm(topology)
solute = [ int(i) for i in mdtraj_topology.select('protein') ]
solvent = [ int(i) for i in mdtraj_topology.select('not protein') ]
print('%d solute atoms, %d solvent atoms' % (len(solute), len(solvent)))

# Get forces
forces = { force.__class__.__name__ : force for force in system.getForces() }
nonbonded_force = forces['NonbondedForce']

# Add a custom force and its negative
custom_nonbonded_force, custom_bond_force = create_solute_forces(nonbonded_force, solute, solvent, switch_width=1.0*unit.angstroms)
negative_custom_nonbonded_force = create_negative_force(custom_nonbonded_force)
system.addForce(custom_nonbonded_force)
system.addForce(negative_custom_nonbonded_force)

# Create MTS solute-solvent splitting g-BAOAB integrator with 4 substeps
print('Creating Context...')
temperature = 300*unit.kelvin
collision_rate = 1.0/unit.picoseconds
timestep = 2.0*unit.femtoseconds
nsteps = 1000
integrator = openmm.LangevinIntegrator(temperature, collision_rate, timestep)
initial_time = time.time()
context = openmm.Context(system, integrator)
final_time = time.time()
elapsed_time = (final_time - initial_time) * unit.seconds
print('%8.3f s elapsed' % (elapsed_time / unit.seconds))
print('Setting positions...')
context.setPositions(positions)
print('Minimizing...')
openmm.LocalEnergyMinimizer.minimize(context)

print('Warming...')
integrator.step(nsteps)

# Time integration
print('Timing %d steps of integration...' % nsteps)
initial_time = time.time()
integrator.step(nsteps)
final_time = time.time()
elapsed_time = (final_time - initial_time) * unit.seconds
integrated_time = nsteps*timestep
print('%d steps of %.1f fs timestep (%.3f ps) took %.3f s : %.3f ns/day' % (nsteps, timestep/unit.femtoseconds, integrated_time/unit.picoseconds, elapsed_time/unit.seconds, (integrated_time/elapsed_time)/(unit.nanoseconds/unit.day)))
```

**Comment by jchodera** [comment]
Oof. It looks like this definitely broke everything we have that uses `CustomNonbondedForces` with interaction groups.

**Comment by peastman** [comment]
Strange, this PR doesn't have anything to do with that code.

**Pull request merged**
