### PR TITLE
Attempt at fixing a race condition in CPU PME

### PR DESCRIPTION
**Pull request by peastman**
This is an attempt at fixing #1065.  I am not at all confident that this fix is actually correct!  Any testing you can do of it would be great.

### CODE REVIEW

**Comment by swails** [comment]
The easiest way for me to test this will be to run it in Travis.  @rmcgibbo -- is there any way you can turn this into a conda package that we later get rid of?

**Comment by rmcgibbo** [comment]
that's a lot more work. i'll just test it using my current setup

**Comment by swails** [comment]
Ah.  OK.  I'll see what I can do.

**Comment by swails** [comment]
Were you able to get reliable hangs?

**Comment by rmcgibbo** [comment]
Yeah, running like 8 copies build in release mode with -g

**Comment by rmcgibbo** [comment]
@peastman i got this to hang. it's in a slightly different place. the app thread is in the destructor.

**Comment by rmcgibbo** [comment]
i think he went home

**Comment by rmcgibbo** [comment]
Main app thread is joining the last thread here: https://github.com/peastman/openmm/blob/threads/plugins/cpupme/src/CpuPmeKernels.cpp#L470, but that thread is hung at https://github.com/peastman/openmm/blob/threads/plugins/cpupme/src/CpuPmeKernels.cpp#L563

**Comment by rmcgibbo** [comment]
https://gist.github.com/rmcgibbo/2db8456d8d150bf16a97

**Comment by peastman** [comment]
```
Thread 2 (Thread 0x7fff6efed700 (LWP 12986)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fffefda764e in OpenMM::CpuCalcPmeReciprocalForceKernel::threadWait (this=0x31d0720) at /home/rmcgibbo/projects/openmm/plugins/cpupme/src/CpuPmeKernels.cpp:568
#2  0x00007fffefda7b4d in OpenMM::CpuCalcPmeReciprocalForceKernel::runThread (this=<optimized out>, index=<optimized out>) at /home/rmcgibbo/projects/openmm/plugins/cpupme/src/CpuPmeKernels.cpp:532
#3  0x00007fffefda895f in threadBody (args=0x47051d0) at /home/rmcgibbo/projects/openmm/plugins/cpupme/src/CpuPmeKernels.cpp:349
#4  0x00007ffff77176aa in start_thread (arg=0x7fff6efed700) at pthread_create.c:333
#5  0x00007ffff6d3deed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

The line numbers don't match the current source code.  Have you added some debugging code?  Which are lines 532 and 568?

**Comment by rmcgibbo** [comment]
Yeah, there was some extra printfs. I'm on my way in -- we can debug it interactively in gdb.

**Comment by rmcgibbo** [comment]
damnit

**Comment by rmcgibbo** [comment]
its like voodoo

**Comment by rmcgibbo** [comment]
Okay, I have one of these open in GDB now. Not going to close this terminal.

**Comment by peastman** [comment]
New version.  This time I did a major rewrite to use ThreadPool.  This might or might not fix the problems.

**Comment by rmcgibbo** [comment]
Cool. I have 13 copies of the parmed test running, and haven't got anything yet...

**Comment by rmcgibbo** [comment]
Each of the processes looped a half dozen times or so, and I didn't get any hangs. Obviously we can't prove that it can't hang, but it seems better than the current code. +1 to merge. Maybe then parmed can switch its test suite to use the master branch (`openmm-dev` or whatever), and we can see if any hangs show up there.

**Comment by swails** [comment]
> Each of the processes looped a half dozen times or so, and I didn't get any hangs. Obviously we can't prove that it can't hang, but it seems better than the current code. +1 to merge. Maybe then parmed can switch its test suite to use the master branch (openmm-dev or whatever), and we can see if any hangs show up there.

+1 on this idea.  The most common place where hangs occurred was on Travis, so hopefully this will provide more evidence that everything's good :).

Thanks @peastman and @rmcgibbo!

**Comment by peastman** [comment]
Ok!  Give it a try.

**Comment by swails** [comment]
@rmcgibbo -- can you let me know when the conda package is updated?

**Comment by rmcgibbo** [comment]
I'm not exactly sure how it happens. I think it's from John's jenkins server. Maybe https://jenkins.choderalab.org/job/conda-openmm-dev-linux-vagrant-2/

**Comment by swails** [comment]
Then pinging @jchodera -- can you let me know when the next `openmm-dev` package is posted?

**Comment by rmcgibbo** [comment]
You should be able to watch the console output on that page and see it.

**Comment by swails** [comment]
OK, I'll keep an eye on it.

**Comment by rmcgibbo** [comment]
Maybe @jchodera can add a twitter bot to the jenkins configuration :)

**Comment by jchodera** [comment]
You can just monitor this page for changes:
https://binstar.org/omnia/openmm-dev/files

I can look into a twitterbot if desired...

**Comment by jchodera** [comment]
We are in the process of switching to a new Jenkins build machine that will hopefully speed up this process greatly.  Our poor old Mac Mini was so very slow...

**Comment by rmcgibbo** [comment]
haha

**Comment by jchodera** [comment]
I"m showing this doesn't compile on appveyor:
```
Linking CXX shared library OpenMM.dll
   Creating library OpenMM.lib and object OpenMM.exp
ThreadPool.cpp.obj : error LNK2019: unresolved external symbol "unsigned long _pthread_tls" (?_pthread_tls@@3KA) referenced in function "void __cdecl pthread_tls_init(void)" (?pthread_tls_init@@YAXXZ)
ThreadPool.cpp.obj : error LNK2019: unresolved external symbol "void (__cdecl** _pthread_key_dest)(void *)" (?_pthread_key_dest@@3PEAP6AXPEAX@ZEA) referenced in function "void __cdecl _pthread_cleanup_dest(struct _pthread_v *)" (?_pthread_cleanup_dest@@YAXPEAU_pthread_v@@@Z)
ThreadPool.cpp.obj : error LNK2019: unresolved external symbol "struct _RTL_SRWLOCK _pthread_key_lock" (?_pthread_key_lock@@3U_RTL_SRWLOCK@@A) referenced in function "void __cdecl _pthread_cleanup_dest(struct _pthread_v *)" (?_pthread_cleanup_dest@@YAXPEAU_pthread_v@@@Z)
ThreadPool.cpp.obj : error LNK2019: unresolved external symbol "long _pthread_tls_once" (?_pthread_tls_once@@3JA) referenced in function "struct _pthread_v * __cdecl pthread_self(void)" (?pthread_self@@YAPEAU_pthread_v@@XZ)
ThreadPool.cpp.obj : error LNK2019: unresolved external symbol "long volatile _pthread_cancelling" (?_pthread_cancelling@@3JC) referenced in function "void __cdecl _pthread_invoke_cancel(void)" (?_pthread_invoke_cancel@@YAXXZ)
OpenMM.dll : fatal error LNK1120: 5 unresolved externals
LINK failed. with 1120
jom: C:\Python34_64\conda-bld\work\build\CMakeFiles\OpenMM.dir\build.make [OpenMM.dll] Error 2
jom: C:\Python34_64\conda-bld\work\build\CMakeFiles\Makefile2 [CMakeFiles\OpenMM.dir\all] Error 2
jom: C:\Python34_64\conda-bld\work\build\Makefile [all] Error 2
 
C:\Python34_64\conda-bld\work\build>if errorlevel 1 exit 1 
```

**Pull request merged**
