### PR TITLE
Master

### PR DESCRIPTION
**Pull request by mharger**
changes to match pandeGroup github.

### CODE REVIEW

**Comment by jchodera** [comment]
Whoa, it looks like this totally breaks the public API for a bunch of Forces.

**Comment by mharger** [comment]
did I push to the main? I am sorry. I am only intending to keep local. This
is my mistake. Please reject.

**Comment by everyday847** [comment]
You may have meant to have mharger:master as the base for the comparison,
rather than pandegroup:master (i.e., to merge pandegroup:master INTO your
branch).

**Comment by mharger** [comment]
I think this was the problem. I am sorry for the confusion.

**Pull request closed without merging**
