### PR TITLE
[WIP] Attempting to implement conditional termination

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
This is woefully incomplete at present, but might be useful to get the discussion going.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Hmm, so a design question that comes up is whether it's possible for this action to "share code and / or kernels" with the `computeGlobal()` pathway.  In practice, I imagine this is quite similar to computeGlobal but with an additional action taken after the kernel is executed.

**Comment by jchodera** [comment]
I wonder if the simplest possible way to implement something that makes use of the `computeGlobal()` code is to explicitly use `addComputeGlobal()` to compute the value of the conditional in an explicitly defined global variable.

That is, instead of
```
integrator.addConditionalTermination(expression)
```
we have the user write
```
integrator.addComputeGlobal(variable, expression)
integrator.addConditionalTermination(variable)
```
That way, you only need to implement a very simple termination kernel.

**Comment by jchodera** [comment]
That may not be as convenient for the user, of course!

**Comment by kyleabeauchamp** [comment]
I was just thinking that as well--that might be the simplest API addition to openmm.

**Comment by jchodera** [comment]
I'm not sure it is any simpler from the API perspective, but it sounds a
hell of a lot easier to implement.

**Comment by peastman** [comment]
I'd actually prefer if we could back off on this.  This isn't something we're ready to start implementing yet.  It needs a lot of design first, and I'm not sure if this is even the right approach to be taking.  For any new feature, step 1 is always to identify the requirements, and we haven't done that yet.  Perhaps you could open a new issue where we could start doing that?

**Comment by kyleabeauchamp** [comment]
OK, so I think the discussion of this is now in #941.  Furthermore, for my immediate needs I may have found a workaround that doesn't require modification of OpenMM.  

If I decide otherwise, I will re-open this or a new pull.

**Pull request closed without merging**
