### PR TITLE
Pin sphinx to 1.5.6 because 1.6.x breaks things

### PR DESCRIPTION
**Pull request by jchodera**
cc: #1820

### CODE REVIEW

**Comment by jchodera** [comment]
This seems to have at least fixed the travis builds, @peastman.

**Comment by peastman** [comment]
Great!  I'm going to hold off on merging until we've determined exactly what it was that broke.  If it doesn't work with the latest version of sphinx, that will cause problems for users.  I'll look into it today.

**Comment by jchodera** [comment]
@peastman : Do you want to merge this since a solution doesn't seem forthcoming?

@Lnaden : You haven't discovered anything that would resolve this issue without pinning sphinx, have you?

**Comment by Lnaden** [comment]
I have not, I also have not looked at the problem in a while.

**Comment by peastman** [comment]
Sounds reasonable.  I tried to figure out the problem, but wasn't able to.  I then posted on the Sphinx discussion group (https://groups.google.com/forum/#!topic/sphinx-users/6rqewb-SqH4), but didn't get much there either.  At this point, the only way I'm likely to figure it out is by digging through the Sphinx source code.  I still plan to do that eventually, but in the mean time pinning the version seems like a reasonable worksaround.

**Comment by peastman** [comment]
It looks like this still failed: https://travis-ci.org/pandegroup/openmm/jobs/242962112

**Comment by jchodera** [comment]
It seems to be failing due to errors in the docstrings now:
https://travis-ci.org/pandegroup/openmm/jobs/242962112#L6028-L6045
```
/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/simtk/openmm/app/charmmpsffile.py:docstring of simtk.openmm.app.charmmpsffile.CharmmPsfFile:5: ERROR: Unexpected indentation.
...
/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py:docstring of simtk.openmm.app.forcefield.ForceField.registerTemplateGenerator:15: ERROR: Unexpected indentation.
```
It looks like it doesn't like indentation in lists, like [here](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/charmmpsffile.py#L119-L130):
```python
class CharmmPsfFile(object):
    """A chemical structure instantiated from CHARMM files.
    This structure has numerous attributes that are lists of the elements of
    this structure, including atoms, bonds, torsions, etc. The attributes are
        - residue_list
        - atom_list
        - bond_list
...
```
This seems to be a different error than before, where we were running into `ImportError` errors:
https://github.com/pandegroup/openmm/issues/1820

I'm not sure why we are only seeing this now, though, rather than in the PR.

**Comment by peastman** [comment]
I don't think we build the documentation in PRs.  That doesn't happen until they get merged.

**Comment by jchodera** [comment]
OK, I've captured this in a new issue: https://github.com/pandegroup/openmm/issues/1835

**Pull request merged**
