### PR TITLE
Optimizations to updateParametersInContext()

### PR DESCRIPTION
**Pull request by peastman**
This partially addresses #1661.  I'm hoping to speed it up a bit more in the future.

### CODE REVIEW

**Comment by jchodera** [comment]
Tagging @bas-rustenburg: Can you profile your constant pH code before and after this update? The `openmm==7.2.0` `dev` label version is being rebuilt right now. You can compare to `openmm==7.1.0rc1` (groan).

**Comment by jchodera** [comment]
> This partially addresses #1661. I'm hoping to speed it up a bit more in the future.

Thanks, @peastman !

**Comment by gregoryross** [comment]
Hi @peastman, @bas-rustenburg and I have been benchmarking these latest optimizations, and have found that `updateParametersInContext` appears to run approximately 4 times slower in `openmm 7.2` (git revision `9963e51a6427f96aad9ada358d56c7f947934fb7`) than `openmm==7.1.0rc1`. I've tried a `GTX titan`, `GTX 980` as well as `CUDA 8.0` and `OpenCL`. 

This slowdown was first observed in our constant-pH code and can be replicated in the minimal benchmarking script `time_update_parameters.py`, attached. The minimal example is comprised of a box of water in which `updateParametersInContext` is used to repeatedly adjust the non-bonded parameters of a TIP3P water molecule.

Please let me know if there is any more information you need.

[time_update_parameters.py.zip](https://github.com/pandegroup/openmm/files/791408/time_update_parameters.py.zip)

**Comment by peastman** [comment]
I'm not seeing this.  With these optimizations, I'm now seeing the overhead being roughly 1.5-2x better than what was reported in #1661.

**Comment by jchodera** [comment]
@peastman: What GPU are you using?

**Comment by peastman** [comment]
GTX 980 and Titan X Pascal.

**Comment by gregoryross** [comment]
Thanks @peastman. What script(s) did you use for the timings? We can make sure that we use the same ones on our end.

**Comment by peastman** [comment]
I used the script that was posted in #1661.

**Comment by gregoryross** [comment]
Okay thanks. @bas-rustenburg, you just ran that script and also observed the slower performance, right?

**Comment by bas-rustenburg** [comment]
Yes, I got these timings:
(openmm-7.1.0RC1)
```
System has 50442 particles
VerletIntegrator.step(nsteps)                                   :    1.655 s for      500 steps (   1.000 ps) :    3.311 ms / step :   1.000 x
VerletIntegrator                                                :    1.659 s for      500 steps (   1.000 ps) :    3.317 ms / step :   1.000 x
VerletIntegrator with updateParametersInContext                 :    4.264 s for      500 steps (   1.000 ps) :    8.527 ms / step :   2.571 x
LangevinIntegrator                                              :    1.585 s for      500 steps (   1.000 ps) :    3.170 ms / step :   0.955 x
LangevinIntegrator with updateParametersInContext               :    4.215 s for      500 steps (   1.000 ps) :    8.430 ms / step :   2.541 x
GHMCIntegratorIntegrator                                        :    3.833 s for      500 steps (   1.000 ps) :    7.666 ms / step :   2.311 x
GHMCIntegrator with updateParametersInContext                   :    7.460 s for      500 steps (   1.000 ps) :   14.920 ms / step :   4.498 x
```

(openmm-7.2) 
 ```
System has 50442 particles
VerletIntegrator.step(nsteps)                                   :    1.701 s for      500 steps (   1.000 ps) :    3.402 ms / step :   1.000 x
VerletIntegrator                                                :    1.698 s for      500 steps (   1.000 ps) :    3.396 ms / step :   1.000 x
VerletIntegrator with updateParametersInContext                 :   15.031 s for      500 steps (   1.000 ps) :   30.062 ms / step :   8.852 x
LangevinIntegrator                                              :    1.619 s for      500 steps (   1.000 ps) :    3.237 ms / step :   0.953 x
LangevinIntegrator with updateParametersInContext               :   14.918 s for      500 steps (   1.000 ps) :   29.836 ms / step :   8.785 x
GHMCIntegratorIntegrator                                        :    3.946 s for      500 steps (   1.000 ps) :    7.891 ms / step :   2.324 x
GHMCIntegrator with updateParametersInContext                   :   19.848 s for      500 steps (   1.000 ps) :   39.695 ms / step :  11.688 x```

**Comment by jchodera** [comment]
@bas-rustenburg : Can you also try a GTX-TITAN-X Pascal so we can compare directly to @peastman's numbers? Use the `cpath` queue and the `gtxtitanxpas` GPU selector.

**Comment by bas-rustenburg** [comment]
On it.

**Comment by bas-rustenburg** [comment]
7.1.0RC1
```
System has 50442 particles
VerletIntegrator.step(nsteps)                                   :    0.539 s for      500 steps (   1.000 ps) :    1.077 ms / step :   1.000 x
VerletIntegrator                                                :    0.512 s for      500 steps (   1.000 ps) :    1.024 ms / step :   1.000 x
VerletIntegrator with updateParametersInContext                 :    2.660 s for      500 steps (   1.000 ps) :    5.319 ms / step :   5.195 x
LangevinIntegrator                                              :    0.513 s for      500 steps (   1.000 ps) :    1.026 ms / step :   1.002 x
LangevinIntegrator with updateParametersInContext               :    2.608 s for      500 steps (   1.000 ps) :    5.217 ms / step :   5.095 x
GHMCIntegratorIntegrator                                        :    1.659 s for      500 steps (   1.000 ps) :    3.318 ms / step :   3.241 x
GHMCIntegrator with updateParametersInContext                   :    5.026 s for      500 steps (   1.000 ps) :   10.052 ms / step :   9.817 x
```

7.2
```
System has 50442 particles
VerletIntegrator.step(nsteps)                                   :    0.551 s for      500 steps (   1.000 ps) :    1.101 ms / step :   1.000 x
VerletIntegrator                                                :    0.550 s for      500 steps (   1.000 ps) :    1.101 ms / step :   1.000 x
VerletIntegrator with updateParametersInContext                 :   12.155 s for      500 steps (   1.000 ps) :   24.309 ms / step :  22.089 x
LangevinIntegrator                                              :    0.545 s for      500 steps (   1.000 ps) :    1.090 ms / step :   0.990 x
LangevinIntegrator with updateParametersInContext               :   12.277 s for      500 steps (   1.000 ps) :   24.554 ms / step :  22.312 x
GHMCIntegratorIntegrator                                        :    1.940 s for      500 steps (   1.000 ps) :    3.879 ms / step :   3.525 x
GHMCIntegrator with updateParametersInContext                   :   14.285 s for      500 steps (   1.000 ps) :   28.569 ms / step :  25.960 x
```

**Pull request merged**
