### PR TITLE
CustomIntegrator can use tabulated functions

### LINKED ISSUE #1772: Add tabulated function capabilities to CustomIntegrator?
How hard would it be to add tabulated function capabilities to `CustomIntegrator` to match those found in the `Custom*Force` classes? 

This feature turns out to be surprisingly useful in build nonequilibrium integrators that use optimized nonequilibrium switching protocols, which could be very useful for the constant-pH code (and other tools) we are working on.

### PR DESCRIPTION
**Pull request by peastman**
Fixes #1772.

### CODE REVIEW

**Comment by jchodera** [comment]
Woohoo!

**Comment by jchodera** [comment]
Don't forget these will need to get serialized/deserialized (with a test to ensure everything is preserved)!

**Comment by peastman** [comment]
Oops, thanks for pointing that out.

**Comment by jlmaccal** [comment]
Does this address either of the points in #1796, and if not, could it be extended?

Specifically:
- Access to the derivative of the tabulated function from the integrator
- Access to the values and derivatives of the tabulated function from the C++ and python APIs

**Comment by peastman** [comment]
No, this only covers #1772.  I haven't implemented those features yet.

**Pull request merged**
