### PR TITLE
Replaced TinyXML with irrXML

### PR DESCRIPTION
**Pull request by peastman**
This should use a lot less memory when reading XML files.

### CODE REVIEW

**Comment by mpharrigan** [comment]
wooooo

**Comment by mpharrigan** [comment]
maybe don't include the irrxml example files?

**Comment by peastman** [comment]
For 3rd party libraries, I usually include their whole distribution, including READMEs, examples, etc.  It's a pretty tiny library.  Even with all of that, it's well under 200kb of files.

**Comment by peastman** [comment]
I missed checking in one file, which is why the build failed.  It's rerunning now.

**Pull request merged**
