### PR TITLE
updateParametersInContext() causes stateChanged() to be called

### PR DESCRIPTION
**Pull request by peastman**
See https://github.com/choderalab/openmmtools/issues/118.  @gregoryross or @jchodera can one of you verify this fixes the problem for you?

### CODE REVIEW

**Comment by gregoryross** [comment]
@peastman Thanks a lot, I'm happy to test this out. Could you recommend a way to test it? A good suggestion I've had is to create a separate conda environment for this PR. Do you have any other recommendations?

**Comment by peastman** [comment]
Are you not set up to build from source?  The instructions are at http://docs.openmm.org/7.0.0/userguide/library.html#compiling-openmm-from-source-code.

**Comment by gregoryross** [comment]
I'm trying to install it from source but I'm getting many errors with `make PythonInstall` and can't figure out the problem. I'm using a Mac, so I'm going to switch and try installing on a Linux machine.

**Comment by jchodera** [comment]
Is it essential to test if this solves the problem before merging? Once we merge, the nightly builds will allow us to test the `dev` package in the morning without problems.

**Comment by peastman** [comment]
No, I assumed it would be easy for you to test.  But if it isn't I can go ahead and merge.

**Comment by gregoryross** [comment]
Okay great, thanks. That certainly simplifies things for me!

**Comment by jchodera** [comment]
I've retriggered the `conda-dev-recipes` build, so the new package should appear [here](https://anaconda.org/omnia/openmm/files) in a few minutes.

**Comment by jchodera** [comment]
Something is broken with `conda-dev-recipes`---will have a look in the morning.

**Comment by jchodera** [comment]
Fixed:
https://anaconda.org/omnia/openmm/files

You should now be able to do
```
conda install -c https://conda.anaconda.org/omnia/label/dev
```
to test.

**Pull request merged**
