### PR TITLE
Fixes to CustomIntegrator

### LINKED ISSUE #1677: Precision in CustomIntegrator kernels
In GHMC (Metropolized Langevin dynamics) implementations for OpenCL using mixed precision, the following forms of the inner velocity Verlet step have very different 

Version 1 (based on the "velocity Verlet" example code):
```python
        self.addComputePerDof("v", "v + 0.5*dt*f/m")
        self.addComputePerDof("x", "x + v*dt")
        self.addComputePerDof("x1", "x")
        self.addConstrainPositions()
        self.addComputePerDof("v", "v + (x-x1)/dt + 0.5*dt*f/m")
        self.addConstrainVelocities()
```
Version 2:
```python
        self.addComputePerDof("v", "v + 0.5*dt*f/m")
        self.addComputePerDof("x", "x + v*dt")
        self.addComputePerDof("x1", "x")
        self.addConstrainPositions()
        self.addComputePerDof("v", "v + (x-x1)/dt")
        self.addComputePerDof("v", "v + 0.5*dt*f/m")
        self.addConstrainVelocities()
```
Surprisingly, Version 2 has much better acceptance rates than version 1.

Looking through the [code for `CustomIntegrator](https://github.com/pandegroup/openmm/blob/master/platforms/cuda/src/CudaKernels.cpp#L7076-L7097), it looks like there is some cleverness going on with how positions are represented---even in mixed precision.

Any chance we could get a more elaborate explanation of how this works, and what we might be able to do to improve numerical conditioning in these Metropolized integrators?

### PR DESCRIPTION
**Pull request by peastman**
Fixes #1677.

### CODE REVIEW

**Comment by jchodera** [comment]
Good catch!

Can we also change `energy` from `real` to `mixed` as you note in https://github.com/pandegroup/openmm/issues/1677#issuecomment-263327501
and clean up any other minor precision issues there?

**Comment by peastman** [comment]
I already did.

**Comment by jchodera** [comment]
Whoops, thanks!

**Comment by jchodera** [comment]
Travis is [having issues with `osx` builds](https://www.traviscistatus.com/incidents/nq0sf0srvx8s), but it looks like the linux tests pass (except for a stochastic test failure).

**Pull request merged**
