### PR TITLE
CustomNonbondedForce with interaction groups uses neighbor lists

### PR DESCRIPTION
**Pull request by peastman**
This is an attempt at addressing #1765.  @jchodera could you try it and see how it works for you?

There are a couple of limitations to be aware of.  I've only implemented it for the CUDA and OpenCL platforms.  I could potentially do a similar optimization for CPU, but it would take a different algorithm.

This optimization is only enabled if the system also includes a standard nonbonded force (either a NonbondedForce or a CustomNonbondedForce without interaction groups), such that CudaNonbondedUtilities/OpenCLNonbondedUtilities is building the standard neighbor list.  CustomNonbondedForce is actually building its own neighbor list, but it relies on CudaNonbondedUtilities to figure out when the neighbor list needs to be rebuilt.

### CODE REVIEW

**Comment by jchodera** [comment]
Awesome! Thanks so much!
I'll benchmark this and report back.

**Comment by jchodera** [comment]
@peastman : I'm having a bit of trouble with the implementation of a solute-solvent splitting MTS integrator that puts the local forces in force group 0 and nonlocal forces in force group 1. The code below attempts to construct this:
* moves `NonbondedForce` to force group 1
* creates a `CustomNonbondedForce` and `CustomBondForce` to represent the LJ and direct-space PME solute-solute and solute-solvent interactions, adding this to force group 0
* adds copies of the same custom forces, with energy expressions multiplied by -1, to force group 1

For a small host-guest system (`HostGuestExplicit`), it provides a modest speedup on a GTX-1080, but for larger systems (`DHFRExplicit`, `SrcExplicit`), it seems to spend forever creating the Context regardless of whether I use CUDA or OpenCL. Note that this happens on both 7.2.0 and your PR version.

### 7.2.0 timings for `HostGuestExplicit`
```
[chodera@lilac:openmmtools]$ python cnbtiming.py
126 solute atoms, 4365 solvent atoms
Creating custom forces...
Creating negative custom force...
Creating Context...
Minimizing...
Warming...
Timing 1000 steps of integration...
1000 steps of 6.0 fs timestep (6.000 ps) took 2.743 s : 188.987 ns/day
```
### 7.3.0 (currently built from this PR) timings for `HostGuestExplicit`
```
[chodera@lilac:openmmtools]$ python cnbtiming.py
126 solute atoms, 4365 solvent atoms
Creating custom forces...
3.2893431387452243 /nm
Creating negative custom force...
Creating Context...
Minimizing...
Warming...
Timing 1000 steps of integration...
1000 steps of 6.0 fs timestep (6.000 ps) took 2.543 s : 203.856 ns/day
```

Code below:
```
#!/bin/env python

from simtk import openmm, unit
from simtk.openmm import app
from openmmtools import testsystems, integrators
from openmmtools.constants import ONE_4PI_EPS0
import mdtraj as md
import numpy as np
import copy
import time

#t = testsystems.SrcExplicit(nonbondedMethod=app.PME)
t = testsystems.DHFRExplicit(nonbondedMethod=app.PME)
#t = testsystems.HostGuestExplicit(nonbondedMethod=app.PME)
system, positions, topology = t.system, t.positions, t.topology

def create_solute_forces(nonbonded_force, solvent, solute, switch_width=None):
    """
    Create CustomNonbondedForce to capture solute-solute and solute-solvent interactions.
    Assumes PME is in use.
    """

    # Determine PME parameters from nonbonded_force
    cutoff_distance = nonbonded_force.getCutoffDistance()
    [alpha_ewald, nx, ny, nz] = nonbonded_force.getPMEParameters()
    if (alpha_ewald/alpha_ewald.unit) == 0.0:
        # If alpha is 0.0, alpha_ewald is computed by OpenMM from from the error tolerance
        tol = nonbonded_force.getEwaldErrorTolerance()
        alpha_ewald = (1.0/cutoff_distance) * np.sqrt(-np.log(2.0*tol))        
    print(alpha_ewald)

    # Create CustomNonbondedForce
    energy_expression  = "(4*epsilon*((sigma/r)^12 - (sigma/r)^6) + ONE_4PI_EPS0*chargeprod*erfc(alpha_ewald*r)/r);"
    energy_expression += "epsilon = epsilon1*epsilon2;"
    energy_expression += "sigma = 0.5*(sigma1+sigma2);"
    energy_expression += "ONE_4PI_EPS0 = {:f};".format(ONE_4PI_EPS0)  # already in OpenMM units
    energy_expression += "chargeprod = charge1*charge2;"
    energy_expression += "alpha_ewald = {:f};".format(alpha_ewald.value_in_unit_system(unit.md_unit_system))
    custom_nonbonded_force = openmm.CustomNonbondedForce(energy_expression)
    custom_nonbonded_force.addPerParticleParameter('charge')
    custom_nonbonded_force.addPerParticleParameter('sigma')
    custom_nonbonded_force.addPerParticleParameter('epsilon')
    custom_nonbonded_force.addInteractionGroup(solute, solute)
    custom_nonbonded_force.addInteractionGroup(solute, solvent)

    # Configure force
    custom_nonbonded_force.setNonbondedMethod(openmm.CustomNonbondedForce.CutoffPeriodic)
    custom_nonbonded_force.setCutoffDistance(cutoff_distance)
    custom_nonbonded_force.setUseLongRangeCorrection(False)
    if switch_width is not None:
        custom_nonbonded_force.setUseSwitchingFunction(True)
        custom_nonbonded_force.setSwitchingDistance(cutoff_distance - switch_width)
    else:  # Truncated
        custom_nonbonded_force.setUseSwitchingFunction(False)

    # Create CustomBondForce for exceptions
    energy_expression  = "(4*epsilon*((sigma/r)^12 - (sigma/r)^6) + ONE_4PI_EPS0*chargeprod/r);"
    energy_expression += "ONE_4PI_EPS0 = {:f};".format(ONE_4PI_EPS0)  # already in OpenMM units
    custom_bond_force = openmm.CustomBondForce(energy_expression)
    custom_bond_force.addPerBondParameter('chargeprod')
    custom_bond_force.addPerBondParameter('sigma')
    custom_bond_force.addPerBondParameter('epsilon')

    # Copy particles
    for particle_index in range(nonbonded_force.getNumParticles()):
        [charge, sigma, epsilon] = nonbonded_force.getParticleParameters(particle_index)
        custom_nonbonded_force.addParticle([charge, sigma, epsilon])

    # Copy solute-solute exclusions
    for exception_index in range(nonbonded_force.getNumExceptions()):
        [iatom, jatom, chargeprod, sigma, epsilon] = nonbonded_force.getExceptionParameters(exception_index)
        custom_nonbonded_force.addExclusion(iatom, jatom)      
        if (iatom in solute) and (jatom in solute):
            custom_bond_force.addBond(iatom, jatom, [chargeprod, sigma, epsilon])

    return custom_nonbonded_force, custom_bond_force

def create_negative_force(force):
    negative_force = copy.copy(force)
    energy_expression = '-1.0*{}'.format(force.getEnergyFunction())
    negative_force.setEnergyFunction(energy_expression)
    return negative_force

# Get solute and solvent indices
mdtraj_topology = md.Topology.from_openmm(topology)
solute = [ int(i) for i in mdtraj_topology.select('protein') ]
solvent = [ int(i) for i in mdtraj_topology.select('not protein') ]
print('%d solute atoms, %d solvent atoms' % (len(solute), len(solvent)))

# Get forces
forces = { force.__class__.__name__ : force for force in system.getForces() }
nonbonded_force = forces['NonbondedForce']

# Create custom forces
print('Creating custom forces...')
custom_nonbonded_force, custom_bond_force = create_solute_forces(nonbonded_force, solute, solvent)
system.addForce(custom_nonbonded_force)
system.addForce(custom_bond_force)
print('Creating negative custom force...')

# Set force groups:
# Force group 0 is solute-solute and solute-solvent interactions
# Force group 1 is solvent-solvent interactions
nonbonded_force.setForceGroup(1)
negative_custom_nonbonded_force = create_negative_force(custom_nonbonded_force)
negative_custom_nonbonded_force.setForceGroup(1)
system.addForce(negative_custom_nonbonded_force)
negative_custom_bond_force = create_negative_force(custom_bond_force)
negative_custom_bond_force.setForceGroup(1)
system.addForce(negative_custom_bond_force)

# Create MTS solute-solvent splitting g-BAOAB integrator with 4 substeps
print('Creating Context...')
timestep = 6.0*unit.femtoseconds
nsteps = 1000
integrator = integrators.LangevinIntegrator(temperature=300*unit.kelvin, collision_rate=1.0/unit.picoseconds, timestep=timestep,
                                            splitting="V1 V0 R R O R R V0 V0 R R O R R V0 V0 R R O R R V0 V0 R R O R R V0 V1")
context = openmm.Context(system, integrator)
context.setPositions(positions)
print('Minimizing...')
openmm.LocalEnergyMinimizer.minimize(context)

print('Warming...')
integrator.step(nsteps)

# Time integration
print('Timing %d steps of integration...' % nsteps)
initial_time = time.time()
integrator.step(nsteps)
final_time = time.time()
elapsed_time = (final_time - initial_time) * unit.seconds
integrated_time = nsteps*timestep
print('%d steps of %.1f fs timestep (%.3f ps) took %.3f s : %.3f ns/day' % (nsteps, timestep/unit.femtoseconds, integrated_time/unit.picoseconds, elapsed_time/unit.seconds, (integrated_time/elapsed_time)/(unit.nanoseconds/unit.day)))
```

**Comment by jchodera** [comment]
Also tagging @pgrinaway @andrrizzi @lnaden @maxentile who are interested in this PR.

**Comment by jchodera** [comment]
@peastman : If I comment out the two lines that add interaction groups, the context is successfully created rapidly:
```python
    custom_nonbonded_force.addInteractionGroup(solute, solute)
    custom_nonbonded_force.addInteractionGroup(solute, solvent)
```
If I leave these lines in, for `DHFRExplicit`, the memory usage just keeps growing over many minutes until memory limits are exhausted.

For `DHFRExplicit`, there are 2404 solute atoms and 21154 solvent atoms. Is it possible that there is an algorithm being used somewhere that has poor memory scaling for this case?

**Comment by jchodera** [comment]
Note that I don't think we'd run into this before because one interaction group would always have a very small number of atoms (<100).

**Comment by jchodera** [comment]
One more question: Does updating a context parameter force pairlists to be rebuilt?

**Comment by jchodera** [comment]
Odd---the CPU platform is now failing:
```
The following tests FAILED:
	  5 - TestCpuCustomNonbondedForce (Failed)
Errors while running CTest
******************************
Rerunning failing tests...
******************************
Test project /home/travis/build/pandegroup/openmm
    Start 5: TestCpuCustomNonbondedForce
1/1 Test #5: TestCpuCustomNonbondedForce ......***Failed    0.20 sec
exception: Assertion failure at TestCustomNonbondedForce.h:1039.  Expected 4276.04, found 4259.17
```

**Comment by peastman** [comment]
I fixed the slow context creation.  When some atoms appear in both sets for an interaction group, it needs to identify all duplicate interactions and make sure they only get computed once.  The method it was using to do that became very slow when the number of shared atoms was large.  I replaced it with a faster method.

I'll look into the CPU test failure next.

**Comment by jchodera** [comment]
Context creation is now tractable!  But it still takes a significant number of seconds.
Here are some timings on a GTX-1080Ti for the solute-solvent splitting g-BAOAB integrator:
```
[chodera@lilac:openmmtools]$ python cnbtiming.py
DHFRExplicit
2404 solute atoms, 21154 solvent atoms
Creating custom forces...
3.2893431387452243 /nm
Creating negative custom force...
Creating Context...
  81.040 s elapsed
Setting positions...
Minimizing...
Warming...
Timing 1000 steps of integration...
1000 steps of 6.0 fs timestep (6.000 ps) took 11.835 s : 43.804 ns/day
```
It looks like the complexity of the `CustomIntegrator` may be hurting us here. There is still lots of stuff to try to tune, though. I'll try to see if I can evaluate the cost of the `CustomNonbondedForce` vs the overhead of the integrator.

Use of pairlists is automatic, yes? I don't have to set anything via the API?

For comparison, the standard OpenMM `LangevinIntegrator` with 2 fs timestep is a lot faster:
```
[chodera@lilac:openmmtools]$ python cnbtiming.py
DHFRExplicit
2404 solute atoms, 21154 solvent atoms
Creating Context...
   1.528 s elapsed
Setting positions...
Minimizing...
Warming...
Timing 1000 steps of integration...
1000 steps of 2.0 fs timestep (2.000 ps) took 1.776 s : 97.292 ns/day
```
and with 4 fs timestep with HMR (2 amu):
```
[chodera@lilac:openmmtools]$ python cnbtiming.py
DHFRExplicit
2404 solute atoms, 21154 solvent atoms
Creating Context...
   2.069 s elapsed
Setting positions...
Minimizing...
Warming...
Timing 1000 steps of integration...
1000 steps of 4.0 fs timestep (4.000 ps) took 1.776 s : 194.575 ns/day
```

**Comment by peastman** [comment]
What are the corresponding times for the master branch?  Does this optimization help?

**Comment by jchodera** [comment]
> What are the corresponding times for the master branch? Does this optimization help?

Working on that profiling! I should probably do some more conventional profiling where I just add two `CustomNonbondedForce` terms that exactly cancel each other and ignore the `CustomIntegrator` part for now.

**Comment by jchodera** [comment]
Before moving on to more profiling, the `SrcExplicit` context creation time is ~490 s!
```
[chodera@lilac:openmmtools]$ python cnbtiming.py
SrcExplicit
4427 solute atoms, 52200 solvent atoms
Creating custom forces...
3.2893431387452243 /nm
Creating negative custom force...
Creating Context...
 490.925 s elapsed
```

**Comment by jchodera** [comment]
For this test, I'm just adding two `CustomBondForce` terms with interaction groups between solute and solvent (to avoid the huge Context creation time for including solute-solute interactions). I'm running with standard `openmm.LangevinIntegrator` to avoid `CustomIntegrator` overhead.

`master`:
```
HostGuestExplicit
126 solute atoms, 4365 solvent atoms
1000 steps of 2.0 fs timestep (2.000 ps) took 0.618 s : 279.693 ns/day
DHFRExplicit
2404 solute atoms, 21154 solvent atoms
1000 steps of 2.0 fs timestep (2.000 ps) took 3.612 s : 47.846 ns/day
SrcExplicit
4427 solute atoms, 52200 solvent atoms
1000 steps of 2.0 fs timestep (2.000 ps) took 12.931 s : 13.363 ns/day
```
and this PR:
```
HostGuestExplicit
126 solute atoms, 4365 solvent atoms
1000 steps of 2.0 fs timestep (2.000 ps) took 0.608 s : 284.276 ns/day
DHFRExplicit
2404 solute atoms, 21154 solvent atoms
1000 steps of 2.0 fs timestep (2.000 ps) took 2.936 s : 58.851 ns/day
SrcExplicit
4427 solute atoms, 52200 solvent atoms
1000 steps of 2.0 fs timestep (2.000 ps) took 7.295 s : 23.687 ns/day
```
For `SrcExplicit`, the PR is almost 2x as fast! The advantage diminishes as the solute gets smaller, as expected. So this is certainly a significant improvement!

Just to make sure: Does changing a context parameter trigger pairlist rebuilds?

**Comment by jchodera** [comment]
Here's the timing code test:
```python
#!/bin/env python

from simtk import openmm, unit
from simtk.openmm import app
from openmmtools import testsystems, integrators
from openmmtools.constants import ONE_4PI_EPS0
import mdtraj as md
import numpy as np
import copy
import time

#t = testsystems.SrcExplicit(nonbondedMethod=app.PME)
#t = testsystems.DHFRExplicit(nonbondedMethod=app.PME)
t = testsystems.HostGuestExplicit(nonbondedMethod=app.PME)
system, positions, topology = t.system, t.positions, t.topology
print(t.__class__.__name__)

def create_solute_forces(nonbonded_force, solvent, solute, switch_width=None):
    """
    Create CustomNonbondedForce to capture solute-solute and solute-solvent interactions.
    Assumes PME is in use.
    """

    # Determine PME parameters from nonbonded_force
    cutoff_distance = nonbonded_force.getCutoffDistance()
    [alpha_ewald, nx, ny, nz] = nonbonded_force.getPMEParameters()
    if (alpha_ewald/alpha_ewald.unit) == 0.0:
        # If alpha is 0.0, alpha_ewald is computed by OpenMM from from the error tolerance
        tol = nonbonded_force.getEwaldErrorTolerance()
        alpha_ewald = (1.0/cutoff_distance) * np.sqrt(-np.log(2.0*tol))        
    print(alpha_ewald)

    # Create CustomNonbondedForce
    energy_expression  = "(4*epsilon*((sigma/r)^12 - (sigma/r)^6) + ONE_4PI_EPS0*chargeprod*erfc(alpha_ewald*r)/r);"
    energy_expression += "epsilon = epsilon1*epsilon2;"
    energy_expression += "sigma = 0.5*(sigma1+sigma2);"
    energy_expression += "ONE_4PI_EPS0 = {:f};".format(ONE_4PI_EPS0)  # already in OpenMM units
    energy_expression += "chargeprod = charge1*charge2;"
    energy_expression += "alpha_ewald = {:f};".format(alpha_ewald.value_in_unit_system(unit.md_unit_system))
    custom_nonbonded_force = openmm.CustomNonbondedForce(energy_expression)
    custom_nonbonded_force.addPerParticleParameter('charge')
    custom_nonbonded_force.addPerParticleParameter('sigma')
    custom_nonbonded_force.addPerParticleParameter('epsilon')
    #custom_nonbonded_force.addInteractionGroup(solute, solute)
    custom_nonbonded_force.addInteractionGroup(solute, solvent)

    # Configure force
    custom_nonbonded_force.setNonbondedMethod(openmm.CustomNonbondedForce.CutoffPeriodic)
    custom_nonbonded_force.setCutoffDistance(cutoff_distance)
    custom_nonbonded_force.setUseLongRangeCorrection(False)
    if switch_width is not None:
        custom_nonbonded_force.setUseSwitchingFunction(True)
        custom_nonbonded_force.setSwitchingDistance(cutoff_distance - switch_width)
    else:  # Truncated
        custom_nonbonded_force.setUseSwitchingFunction(False)

    # Create CustomBondForce for exceptions
    energy_expression  = "(4*epsilon*((sigma/r)^12 - (sigma/r)^6) + ONE_4PI_EPS0*chargeprod/r);"
    energy_expression += "ONE_4PI_EPS0 = {:f};".format(ONE_4PI_EPS0)  # already in OpenMM units
    custom_bond_force = openmm.CustomBondForce(energy_expression)
    custom_bond_force.addPerBondParameter('chargeprod')
    custom_bond_force.addPerBondParameter('sigma')
    custom_bond_force.addPerBondParameter('epsilon')

    # Copy particles
    for particle_index in range(nonbonded_force.getNumParticles()):
        [charge, sigma, epsilon] = nonbonded_force.getParticleParameters(particle_index)
        custom_nonbonded_force.addParticle([charge, sigma, epsilon])

    # Copy solute-solute exclusions
    for exception_index in range(nonbonded_force.getNumExceptions()):
        [iatom, jatom, chargeprod, sigma, epsilon] = nonbonded_force.getExceptionParameters(exception_index)
        custom_nonbonded_force.addExclusion(iatom, jatom)      
        if (iatom in solute) and (jatom in solute):
            custom_bond_force.addBond(iatom, jatom, [chargeprod, sigma, epsilon])

    return custom_nonbonded_force, custom_bond_force

def create_negative_force(force):
    negative_force = copy.copy(force)
    energy_expression = '-1.0*{}'.format(force.getEnergyFunction())
    negative_force.setEnergyFunction(energy_expression)
    return negative_force

# Get solute and solvent indices
mdtraj_topology = md.Topology.from_openmm(topology)
solute = [ int(i) for i in mdtraj_topology.select('protein') ]
solvent = [ int(i) for i in mdtraj_topology.select('not protein') ]
print('%d solute atoms, %d solvent atoms' % (len(solute), len(solvent)))

# Get forces
forces = { force.__class__.__name__ : force for force in system.getForces() }
nonbonded_force = forces['NonbondedForce']

# Add a custom force and its negative
custom_nonbonded_force, custom_bond_force = create_solute_forces(nonbonded_force, solute, solvent, switch_width=1.0*unit.angstroms)
negative_custom_nonbonded_force = create_negative_force(custom_nonbonded_force)
system.addForce(custom_nonbonded_force)
system.addForce(negative_custom_nonbonded_force)

# Create MTS solute-solvent splitting g-BAOAB integrator with 4 substeps
print('Creating Context...')
temperature = 300*unit.kelvin
collision_rate = 1.0/unit.picoseconds
timestep = 2.0*unit.femtoseconds
nsteps = 1000
integrator = openmm.LangevinIntegrator(temperature, collision_rate, timestep)
initial_time = time.time()
context = openmm.Context(system, integrator)
final_time = time.time()
elapsed_time = (final_time - initial_time) * unit.seconds
print('%8.3f s elapsed' % (elapsed_time / unit.seconds))
print('Setting positions...')
context.setPositions(positions)
print('Minimizing...')
openmm.LocalEnergyMinimizer.minimize(context)

print('Warming...')
integrator.step(nsteps)

# Time integration
print('Timing %d steps of integration...' % nsteps)
initial_time = time.time()
integrator.step(nsteps)
final_time = time.time()
elapsed_time = (final_time - initial_time) * unit.seconds
integrated_time = nsteps*timestep
print('%d steps of %.1f fs timestep (%.3f ps) took %.3f s : %.3f ns/day' % (nsteps, timestep/unit.femtoseconds, integrated_time/unit.picoseconds, elapsed_time/unit.seconds, (integrated_time/elapsed_time)/(unit.nanoseconds/unit.day)))
```

**Comment by peastman** [comment]
> For SrcExplicit, the PR is almost 2x as fast!

Yay!

> Just to make sure: Does changing a context parameter trigger pairlist rebuilds?

No, that shouldn't make any difference.  The only case I can think of where that would be expensive is if you were using the long range correction.

**Comment by jchodera** [comment]
Quick benchmark update: After #2019, the `SrcExplicit` `CustomNonbondedForce` context creation time went down from ~490s to ~37s!
```
[chodera@lilac:openmmtools]$ python cnbtiming2.py
SrcExplicit
4427 solute atoms, 52200 solvent atoms
3.2893431387452243 /nm
Creating Context...
  37.100 s elapsed
Setting positions...
Minimizing...
Warming...
Timing 1000 steps of integration...
1000 steps of 2.0 fs timestep (2.000 ps) took 5.108 s : 33.830 ns/day
```

**Comment by EqualAPriori** [comment]
Thanks for the awesome work! I wanted to get some performance advice.

I'm coming from the coarse-grained, LAMMPS world where interactions are implemented using interaction groups. We are testing out a variety of potential types, and wanted to translate them from LAMMPS into OpenMM in a flexible way. 

If all the interactions had the same functional form, I've implemented the interaction in OpenMM using a single Custom Nonbonded interaction with parameters that are drawn from a 2D tabulated function based in atom type pairs. However, in the case where we are prototyping and trying different functional forms, it would be much more convenient to layer these potentials on via inteaction groups in OpenMM (which can be easily implemented by creating interaction building blocks, like Lammps), instead of writing an ever-more complicated general functional form each time we change the functional form (we have in-house tools that use the language of interaction groups, and want to keep that in place if possible).

My question is, performance-wise, how big of a performance hit might I expect to see if I use, say, a single complicated custom nonbonded interaction, vs. say 10 separate pair interactions (i.e. 5 different bead-types would have 10 different pair interactions)? 

From what I can surmise reading the Q&A pages, I need to be careful to:
1. have a Nonbonded or CustomNonbonded interaction with no interaction groups in order to generate the neighbor lists
2. all interactions must have the same cutoff and NonbondedMethod

Thanks!

**Comment by peastman** [comment]
That's an interesting question, and I'm not really sure what would be faster.  You'll need to try both and see how they compare.  There are two factors that work in opposite directions.

First, interaction groups inherently make things slower in terms of time per interaction.  They require it to use a less efficient algorithm.  Of course, usually you're using interaction groups to compute fewer interactions total, so it may still end up being faster.  But in this case you're computing all interactions, just with a bunch of different interaction groups.  So that will be slower than computing all interactions without groups.

On the other hand, each CustomNonbondedForce (with interaction groups) is computed independently of the others.  Adding a new one doesn't make the others slower.  Not so with a single really complicated CustomNonbondedForce.  Each time you add a new type of interaction to the expression it makes *every* interaction slower.

So probably there will be a crossover point where it switches which approach is faster.  But I don't where that will be.

**Comment by EqualAPriori** [comment]
I see, thank you for the extra insight into how things run under the hood! 
I'll try both implementations out.

**Comment by EqualAPriori** [comment]
Just wanted to leave an update --
In the end I went with somewhat of a workaround:
1. Using the customnonbodedforce's supported energy function definition language, I wrote a spline interaction
2. In a wrapper script I would sum up and tabulate the total interaction energy between every pair of atom types

This seemed the cleanest, and only one interaction definition is needed, meaning it scales well to many atom types, and one won't run into the limit of 32 force objects in openMM (correct me if that is a misunderstanding).

In some sample tests of a custom-nonbonded force implementation of LJ for all atom pairs vs the spline interpolation, the spline interpolation was only 1.3~2x slower for 250-500 knot points for the spline interpolation. The real gain is that now one doesn't have to rewrite the energy function each time the interactions are changed (easier to prototype), and should scale better with increasing number of different interaction types.

Thanks again for the discussion and help!

**Pull request merged**
