### PR TITLE
Use Jenkinsfile to drive the pipeline job

### PR DESCRIPTION
**Pull request by swails**

### CODE REVIEW

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
I'm hopeful that Jenkins will work this time around.  If it does, this can be merged.

Alternatively I can open a new PR with a branch where all of these commits are squash-merged, so I *don't* break the record of commits in a PR :)

**Comment by jchodera** [comment]
Woohoo! It works!

Can't you squash the commits on merging the PR?

**Comment by swails** [comment]
Depends on the repo settings. But I think there’s a setting to allow that. 

I’ll leave the ball in @peastman’s court for that.

**Comment by peastman** [comment]
You can use `git rebase` to squash the commit history.  See https://help.github.com/articles/about-git-rebase/ and http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by swails** [comment]
Do you want me to do that?

**Comment by peastman** [comment]
Actually, never mind.  I just noticed that if I click the arrow next to "merge pull request" I have an option to squash the commits.  Amazing!

**Pull request merged**
