### PR TITLE
Eliminate stray non-ASCII characters from references.bib since this breaks sphinx

### LINKED ISSUE #1949: Sphinx docs are failing due to non-ASCII character in references.bib
A stray non-ASCII character in `references.bib` added in https://github.com/pandegroup/openmm/pull/1942 is [causing the `dev` conda package builds to fail](https://travis-ci.org/omnia-md/conda-dev-recipes/jobs/309839769#L8989-L9013):
```
! Package inputenc Error: Unicode char ϕ (U+3D5)
(inputenc)                not set up for use with LaTeX.
See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.9879 ...ing improved sampling of the backbone ϕ
                                                  , \(\psi\) and side-chain ...
? 
! Emergency stop.
 ...                                              
                                                  
l.9879 ...ing improved sampling of the backbone ϕ
                                                  , \(\psi\) and side-chain ...
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on OpenMMUsersGuide.log.
make[5]: *** [OpenMMUsersGuide.pdf] Error 1
make[4]: *** [latexpdf] Error 2
make[3]: *** [sphinx-docs/userguide/latex/OpenMMUsersGuide.pdf] Error 2
make[2]: *** [docs-source/CMakeFiles/sphinxpdf.dir/all] Error 2
make[1]: *** [docs-source/CMakeFiles/sphinxpdf.dir/rule] Error 2
make: *** [sphinxpdf] Error 2
```
Here's the failure in `docs-source/usersguide/references.bib`:
```
@article{Best2012,
   author = {Best, Robert B. and Zhu, Xiao and Shim, Jihyun and Lopes, Pedro E. M. and Mittal, Jeetain and Feig, Michael and MacKerell, Alexander D.},
   title = {Optimization of the Additive CHARMM All-Atom Protein Force Field Targeting Improved Sampling of the Backbone ϕ, ψ and Side-Chain χ1 and χ2 Dihedral Angles},
```
I'll open a PR to correct this, but @peastman should add a travis test branch that will fail if the sphinx docs builds fail so we don't merge PRs that break the conda builds.

### PR DESCRIPTION
**Pull request by jchodera**
Fixes #1949

### CODE REVIEW

**Comment by Lnaden** [comment]
Or this, this works too. You may have to wrap the characters around a `{}` from what I am seeing of others who have had this problem, but thats if this doesn't fix it

**Comment by Lnaden** [comment]
Also will resolve test failures in pandegroup/pdbfixer#157

**Comment by peastman** [comment]
It doesn't like something about your travis change:

```
ERROR: An error occured while trying to parse your .travis.yml file.

Please make sure that the file is valid YAML.

http://lint.travis-ci.org can check your .travis.yml.

The log message was: Build config file had a parse error: did not find expected '-' indicator while parsing a block collection at line 167 column 3.
```

**Comment by Lnaden** [comment]
Odd. But if I had to take a guess, I bet it doesn't like the inline comment. I have found the CI YAML parsers can get uppity with comments, even the conda yaml parser can actually parse the comments too.

**Comment by peastman** [comment]
We can't build the beta until this gets fixed.

**Comment by jchodera** [comment]
Whoops! Sorry, things got busy---will fix now. 

Should I also give you permission to push to my fork in case you need to fix things like this in future?

**Comment by Lnaden** [comment]
I cant promise that will fix it, just my guess

**Comment by jchodera** [comment]
Seems to fix things.

**Comment by jchodera** [comment]
All tests pass.

**Comment by peastman** [comment]
Thanks!

**Pull request merged**
