### PR TITLE
Enabled OpenCL on OS X

### PR DESCRIPTION
**Pull request by peastman**
As of OS X 10.10.3, Apple has finally fixed their OpenCL bugs!  That means we can finally start supporting it again.

### CODE REVIEW

**Comment by jchodera** [comment]
Hooray!

**Comment by jhprinz** [comment]
Cool. That will be very useful here in Amsterdam since most iMacs have AMD chips!

**Comment by jhprinz** [comment]
Does that also mean we could use it already, when compiling OpenMM ourselves?

**Comment by swails** [comment]
> Does that also mean we could use it already, when compiling OpenMM ourselves?

Yes.

**Comment by jchodera** [comment]
The development conda package of OpenMM should also work:
https://binstar.org/omnia/openmm-dev
```
conda install -c https://conda.binstar.org/omnia openmm-dev
```

**Comment by bb30994** [comment]
>swails commented Apr 17, 2015
>>    Does that also mean we could use it already, when compiling OpenMM ourselves?
>Yes.
For stand-alone OpenMM Yes.  For FAH, the servers still won't send you WUs.

**Pull request merged**
