### PR TITLE
Add $ORIGIN rpath to plugins

### PR DESCRIPTION
**Pull request by rmcgibbo**
Re #996, #997. This appears to work on linux. I'm not sure if it works on Apple or Windows, or if on apple the extra `install_name_tool` invocations that modify the loader path can be removed with this change.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
I'm not sure how to get this to solve the problem on OSX

**Comment by peastman** [comment]
The magic value "$ORIGIN" is completely Linux specific.  This will not have the intended effect on either Mac or Windows, and may break them.

Possibly there's some special CMake incantation that has the desired effect on all platforms, but if so I don't know what it is.  We already have one that works for Mac, and I'm not sure if it even exists on Windows: I *think* DLLs always look in their own directory for dependencies.  I suggest making this change only apply on Linux.

**Comment by rmcgibbo** [comment]
I know that it's linux specific. I've been trying to figure out the mac analog -- no success yet.

**Comment by rmcgibbo** [comment]
The plugins do not correctly load on mac without the sort order fix. e.g. test out this script https://gist.github.com/rmcgibbo/f5ca495d9f121833f1dc

**Comment by rmcgibbo** [comment]
This PR doesn't break the osx build (on my laptop) -- it's just no different that the current master.

**Comment by rmcgibbo** [comment]
#997 solves [this problem](https://gist.github.com/rmcgibbo/f5ca495d9f121833f1dc) on both OSX and linux, whereas this PR only works on LINUX, and there is no feature of the OSX dynamic linker that can be used to solve this problem, I think. My vote is to merge #997.

**Comment by peastman** [comment]
> #997 solves this problem on both OSX and linux, whereas this PR only works on linux, and there is no corresponding feature of the OSX dynamic linker that can be used to solve this problem, I think.

Fair enough.  I think there *is* a feature that can be used to solve it on OS X, but we can save working that out till some time in the future.

**Pull request closed without merging**
