### PR TITLE
Add script to build on my Jenkins machine

### PR DESCRIPTION
**Pull request by swails**
test

### CODE REVIEW

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
All of the tests seem to pass, with a caveat.  Just a few comments here:

1. Jenkins will not build *all* pull requests automatically -- only those initiated from a whitelist of users.  Currently, that is every user in the omnia-md, Amber-MD, and pandegroup groups.  This is primarily as a protection for my computer.  Although the Jenkins user has a strictly limited permission set, I'm still wary of letting *any* pull request with any arbitrary code execute on my machine.  If someone outside those groups submits a PR, Jenkins will post a message (posing as @peastman), with something like "Will an admin please verify this patch?".  Anyone in one of those groups can then trigger a build with the phrase "r u n  j e n k i n s" after they check that the diff isn't clearly malicious (without the extra spaces -- I didn't want to trigger another build here).
1. @peastman or I can add (trustworthy :smiley:) users to the whitelist if I missed anybody
1. You can use the trigger phrase I mentioned above to rebuild if necessary.
1. The script `devtools/ci/jenkins/install.sh` runs the install and test, and the script in the Jenkins setup is just sourcing this file.  Any command in the build process that ends in a non-zero exit status kills the whole build and marks it as failed.

[It also appears that timeout tests do not get rerun](http://www.jasonswails.com:8888/job/Omnia/job/OpenMM/7/default/console) -- is this known? Intentional?

**Comment by peastman** [comment]
Excellent!  I think the whitelist makes sense, and that will cover most PRs.

> Jenkins will post a message (posing as @peastman)

Wait—it has the ability to post messages pretending to be me?  How does it manage that?

> It also appears that timeout tests do not get rerun -- is this known? Intentional?

That's because of the way we run OpenCL tests.  Travis doesn't give us enough time for it to get through all of them.  So we run them in a random order, and let it go for a fixed amount of time.  Whichever test it's in the middle of when time runs out will get a timeout, but that doesn't indicate any problem with it, so we don't rerun it.

Is this ready to merge?

**Comment by swails** [comment]
> Wait—it has the ability to post messages pretending to be me? How does it manage that?

The token you gave me to post status notifications was derived from your account.

> That's because of the way we run OpenCL tests. Travis doesn't give us enough time for it to get through all of them. So we run them in a random order, and let it go for a fixed amount of time. Whichever test it's in the middle of when time runs out will get a timeout, but that doesn't indicate any problem with it, so we don't rerun it.

We don't have any such time constraint on Jenkins, so should we change how the tests are run to get all of the test cases?

On the one hand, it's irritating to have a super long build set up as a merge gate, but on the other hand it would probably be nice to ensure all tests are being run.

Another option is to set up SCM polling so that the master branch is built nightly or weekly and runs through a more comprehensive test suite and opens an issue if the tests fail.  That way we get earl(ier) failure notifications without introducing huge latency in the test step.

Assuming we are happy with this Jenkins build as a merge gate right now, this is good to merge.

**Comment by peastman** [comment]
By default, the `run-ctest.py` script limits each test to 180 seconds and the whole suite to 30 minutes.  But you can pass arguments to it to increase those, which I think would be a good idea.  As you say, you don't have any strict time limit there.  Right now, the main limiter on merging builds is the travis OS X build, which often takes a few hours to start running.  So we could easily let jenkins run for a couple of hours without slowing anything down.  We can reconsider that in the future if things change.

**Comment by swails** [comment]
Done -- although is something wrong with Travis?

**Comment by peastman** [comment]
I think travis is having problems related to the AWS outage.

**Comment by peastman** [comment]
Jenkins is reporting failure, but I'm not sure what to make of the console output.  It's very short, and I don't see anything that looks like it actually tried to build.

**Comment by swails** [comment]
> It's very short, and I don't see anything that looks like it actually tried to build.

You're looking at the parent matrix build.  Click on the link to the "default" build in that console output to see the actual build. [See here](http://www.jasonswails.com:8888/job/Omnia/job/OpenMM/8/default/console)

I figured at some point we may want to include some more tests, or use the matrix build to split up the tasks.  For instance, we can have one build just do the OpenCL tests and one do just the CUDA tests to speed things up.  We can also test the GCC compilers (I have multiple versions to choose from) and/or the Intel compilers (ditto).

There's a lot we can do with Jenkins.  We can also set up a polling job that periodically runs some benchmark tests to start generating a report of performance vs. time, we can set up a pipeline job that checks the stability of the Omnia suite (PDBFixer + OpenMM, etc.), and so on.

**Comment by peastman** [comment]
Ok, I see.  The error is a failure in TestOpenCLVirtualSitesSingle.  Not sure why it's failing (possibly just exceeding the tolerance), but I'll look into that later.  Anyway, I think this is ready to merge!

**Pull request merged**
