### PR TITLE
Added checkpointing functions to Simulation

### PR DESCRIPTION
**Pull request by peastman**
This is the first piece of #914.  Comments would be great.

### CODE REVIEW

**Comment by swails** [comment]
Nice additions to the `Simulation` API.

**Comment by mpharrigan** [comment]
Nice! 

Can we have a static method e.g.
```python
simulation = Simulation.fromCheckpoint("checkpoint.mm")
```

**Comment by kyleabeauchamp** [comment]
I agree with the idea of having super convenient ways to load / save things with as few keystrokes as possible.

**Comment by jchodera** [comment]
Looking good!

**Comment by swails** [comment]
@mpharrigan -- `classmethod` you mean, yes? +1 for the alternate XML-based constructor.

**Comment by mpharrigan** [comment]
@swails whatever python likes to call them :)

**Comment by swails** [comment]
Well Python has both.  Alternate constructors are `classmethod`s (they can be implemented as a `staticmethod`, but not in an inheritance-friendly way).

**Comment by peastman** [comment]
It takes a lot more than a checkpoint to create a simulation.  For that, you also need a System, a Topology, and an Integrator.

**Comment by swails** [comment]
> It takes a lot more than a checkpoint to create a simulation. For that, you also need a System, a Topology, and an Integrator.

I know, but all three of those can be exported to XML files, right?  So the `from_xml` constructor could take 3 XML files and an optional checkpoint file to instantiate it, yes?

**Comment by peastman** [comment]
> I know, but all three of those can be exported to XML files, right?

Topology can't be.

**Comment by swails** [comment]
On Thu, May 14, 2015 at 1:57 PM, peastman <notifications@github.com> wrote:

> I know, but all three of those can be exported to XML files, right?
>
> Topology can't be.
> ​
>
> ​
​Bummer.​

**Pull request merged**
