### PR TITLE
WIP: Nicer swig wrappers

### PR DESCRIPTION
**Pull request by rmcgibbo**
Re #882, #879, this now generates nicer swig wrappers that have the proper function signatures when using a sufficiently new version of swig (definitely 3.0.6, not 3.0.2, not sure exactly where in between).

Previously, all of the python wrappers formally had a signature like `openmm.LangevinIntegrator.setTemperature(self, *args)`. Using new swig, with this PR the signature is `LangevinIntegrator.setTemperature(self, temp)`. This allows you to use keyword arguments for example, for most methods.

Still some bugs to be worked out, I suspect. Try it out and let me know if it works for you.

### CODE REVIEW

**Comment by peastman** [comment]
Cool!  But *definitely* something to wait until after 6.3 to merge.

**Comment by rmcgibbo** [comment]
Yep :) (which is hopefully imminent, right?)

**Comment by peastman** [comment]
I hope so!  I'm still corresponding with Nvidia to try to track down the Windows performance problem.

**Comment by rmcgibbo** [comment]
TODO notes for me:

 - [ ] Unit stripping in constructors
 - [ ] Overloaded methods are not treated correctly (`system.getForce`)
 - [ ] Methods that use pass-by-reference to return values like `System.getConstraintParameters` not handled correctly when stripping units.

**Comment by rmcgibbo** [comment]
Actually, I think it will be more robust to use typemaps to apply the unit conversion.

**Comment by peastman** [comment]
Looks like there are some test failures.

**Comment by rmcgibbo** [comment]
Incorporating this into #1031

**Pull request closed without merging**
