### PR TITLE
Deploy development docs to S3

### PR DESCRIPTION
**Pull request by rmcgibbo**
RE https://github.com/pandegroup/openmm/pull/1228#issuecomment-156209569, this should deploy the development docs to S3 at http://docs.openmm.org/development, which could aid with debugging.

### CODE REVIEW

**Comment by peastman** [comment]
I hope you're not doing anything insecure by hardcoding the access keys?

**Comment by rmcgibbo** [comment]
They're encrypted. http://docs.travis-ci.com/user/environment-variables/#Encrypting-Variables-Using-a-Public-Key

**Comment by peastman** [comment]
Ok, just making sure!  Seeing a field called `secret_access_key` hardcoded in the script made me a little nervous.

**Comment by mpharrigan** [comment]
but it's followed by `secure:` :)

**Comment by rmcgibbo** [comment]
Kk. I think this is correct now. We'll only see the site once it runs in `master` after the merge.

**Comment by rmcgibbo** [comment]
The docs for the master branch can now be found here.

 - http://docs.openmm.org/development/api-python/annotated.html
 - http://docs.openmm.org/development/api-c++/annotated.html

**Pull request merged**
