### PR TITLE
Silence OSX CMake RPATH warning

### LINKED ISSUE #493: cmake 3.0.0 warning
Has anyone run into this warning with cmake 3.0.0 on OS X?
```
[LSKI1497:~/code/openmm/openmm.jchodera] choderaj% cmake .
-- The C compiler identification is AppleClang 5.1.0.5030040
-- The CXX compiler identification is AppleClang 5.1.0.5030040
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Doxygen: /opt/local/bin/doxygen (found version "1.8.7") 
-- Found OPENCL: /System/Library/Frameworks/OpenCL.framework  
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   OpenMM
   OpenMMAmoeba
   OpenMMAmoebaReference
   OpenMMCPU
   OpenMMDrude
   OpenMMDrudeOpenCL
   OpenMMDrudeReference
   OpenMMOpenCL
   OpenMMPME
   OpenMMRPMD
   OpenMMRPMDOpenCL
   OpenMMRPMDReference

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/choderaj/code/openmm/openmm.jchodera
```

Here is my version info:
```
[LSKI1497:~/code/openmm/openmm.jchodera] choderaj% cmake --version
cmake version 3.0.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

### PR DESCRIPTION
**Pull request by rmcgibbo**
Fixes #493.

### CODE REVIEW

**Comment by peastman** [comment]
This fails to build:

```
CMake Error at CMakeLists.txt:25 (CMAKE_POLICY):
  Policy "CMP0042" is not known to this version of CMake.
```

**Comment by rmcgibbo** [comment]
What version of cmake do you have?

**Comment by rmcgibbo** [comment]
Oh, I see, that's travis. I'll find when this was first added.

**Comment by rmcgibbo** [comment]
Fixed.

**Pull request merged**
