### PR TITLE
Use g++ instead of clang and fix PythonInstall

### PR DESCRIPTION
**Pull request by swails**
clang is tested everywhere else, and it's not as routinely up-to-date on
my Jenkins machine.

PythonInstall failed on Linux machines where the build/install
directories had paths with spaces in them.

### CODE REVIEW

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
I had changed some settings, so the "default" check won't appear on future PRs.

However, everything *seems* to be working now.  The last build failed because I accidentally set the build to timeout after an hour, rather than timing out if no activity had been detected in an hour.  I've updated the recipe to run until completion or there has been no activity for an hour.

**Comment by swails** [comment]
My last commit fixes #2034

**Comment by swails** [comment]
Hey, look at that!

@peastman -- you can (finally) merge this.  If you update your next PR that you just raised, it'll fix the Jenkins build there, too.

**Comment by peastman** [comment]
Wow, thank you!  Amazing work!

**Pull request merged**
