### PR TITLE
Optimizations to updateParametersInContext()

### PR DESCRIPTION
**Pull request by peastman**
This is a further attempt at improving #1661.  @jchodera can you try it and see if it helps?

### CODE REVIEW

**Comment by jchodera** [comment]
Awesome! Let me build a dev package for @bas-rustenburg so he can compare the impact of before and after this PR.

**Comment by peastman** [comment]
Actually, hold on.  There's one more minor improvement I want to make.

**Comment by peastman** [comment]
Ok, go ahead.

**Comment by bas-rustenburg** [comment]
Going to see how it affects my benchmark results. Thanks for putting this together.

**Comment by jchodera** [comment]
@bas-rustenburg posted his performance data here: https://github.com/pandegroup/openmm/issues/1661#issuecomment-375405715

**Comment by peastman** [comment]
@bas-rustenburg I couldn't quite tell from your comments whether this change improved performance or not.  For reference, here's what I'm getting before and after this change, running on a 4 core CPU and a Titan X.

Before:

```
VerletIntegrator.step(nsteps)                                   :    0.015 s for      500 steps (   1.000 ps) :    0.030 ms / step :   1.000 x
VerletIntegrator                                                :    0.494 s for      500 steps (   1.000 ps) :    0.987 ms / step :   1.000 x
VerletIntegrator with updateParametersInContext                 :    1.688 s for      500 steps (   1.000 ps) :    3.376 ms / step :   3.421 x
LangevinIntegrator                                              :    0.482 s for      500 steps (   1.000 ps) :    0.965 ms / step :   0.977 x
LangevinIntegrator with updateParametersInContext               :    1.676 s for      500 steps (   1.000 ps) :    3.352 ms / step :   3.396 x
GHMCIntegratorIntegrator                                        :    0.000 s for      500 steps (   1.000 ps) :    0.001 ms / step :   0.001 x
GHMCIntegrator with updateParametersInContext                   :    3.791 s for      500 steps (   1.000 ps) :    7.581 ms / step :   7.681 x
```

After:

```
VerletIntegrator.step(nsteps)                                   :    0.015 s for      500 steps (   1.000 ps) :    0.030 ms / step :   1.000 x
VerletIntegrator                                                :    0.578 s for      500 steps (   1.000 ps) :    1.156 ms / step :   1.000 x
VerletIntegrator with updateParametersInContext                 :    1.435 s for      500 steps (   1.000 ps) :    2.869 ms / step :   2.482 x
LangevinIntegrator                                              :    0.484 s for      500 steps (   1.000 ps) :    0.968 ms / step :   0.838 x
LangevinIntegrator with updateParametersInContext               :    1.279 s for      500 steps (   1.000 ps) :    2.558 ms / step :   2.213 x
GHMCIntegratorIntegrator                                        :    0.000 s for      500 steps (   1.000 ps) :    0.001 ms / step :   0.001 x
GHMCIntegrator with updateParametersInContext                   :    3.322 s for      500 steps (   1.000 ps) :    6.645 ms / step :   5.748 x
```

So I'm seeing a small but still useful speedup.

**Comment by bas-rustenburg** [comment]
Thanks Peter.

I ran the other benchmark script. I think I can conclude it is slightly slower on our system. This is on a GeForce GTX 1080 Ti and 1 cpu core.

Before
```
(benchmark-before) rustenburg@lt01:~/openmm-protons-benchmarks/MinimalTest2:
 Tue Mar 27 16:23:02 [0] $ python minimal_test.py
openmm 6b32fc32dddada6418f52da2283986a91f69f8d4
System has 50442 particles
VerletIntegrator.step(nsteps)                                   :    2.877 s for      500 steps (   1.000 ps) :    5.753 ms / step :   1.000 x
VerletIntegrator                                                :    2.893 s for      500 steps (   1.000 ps) :    5.785 ms / step :   1.000 x
VerletIntegrator with updateParametersInContext                 :   20.454 s for      500 steps (   1.000 ps) :   40.908 ms / step :   7.071 x
LangevinIntegrator                                              :    2.913 s for      500 steps (   1.000 ps) :    5.826 ms / step :   1.007 x
LangevinIntegrator with updateParametersInContext               :   20.109 s for      500 steps (   1.000 ps) :   40.218 ms / step :   6.952 x
GHMCIntegratorIntegrator                                        :    5.410 s for      500 steps (   1.000 ps) :   10.820 ms / step :   1.870 x
GHMCIntegrator with updateParametersInContext                   :   26.756 s for      500 steps (   1.000 ps) :   53.511 ms / step :   9.250 x
```
After
```(benchmark-after) rustenburg@lt01:~/openmm-protons-benchmarks/MinimalTest2:
 Tue Mar 27 16:26:24 [0] $ python minimal_test.py
openmm af57bf9852d7d7de958a2c0db75213059a79e35f
System has 50442 particles
VerletIntegrator.step(nsteps)                                   :    2.863 s for      500 steps (   1.000 ps) :    5.726 ms / step :   1.000 x
VerletIntegrator                                                :    2.902 s for      500 steps (   1.000 ps) :    5.804 ms / step :   1.000 x
VerletIntegrator with updateParametersInContext                 :   21.098 s for      500 steps (   1.000 ps) :   42.195 ms / step :   7.270 x
LangevinIntegrator                                              :    2.910 s for      500 steps (   1.000 ps) :    5.821 ms / step :   1.003 x
LangevinIntegrator with updateParametersInContext               :   21.009 s for      500 steps (   1.000 ps) :   42.019 ms / step :   7.240 x
GHMCIntegratorIntegrator                                        :    5.283 s for      500 steps (   1.000 ps) :   10.567 ms / step :   1.821 x
GHMCIntegrator with updateParametersInContext                   :   27.696 s for      500 steps (   1.000 ps) :   55.391 ms / step :   9.544 x
```

**Comment by peastman** [comment]
Right, it will be a little slower with only one core.  Part of the optimization comes from parallelizing it.  Is there a reason you're only using one core?

**Comment by jchodera** [comment]
Ah! We usually set `OPENMM_CPU_THREADS` to `1` to run on our batch queue system so we can request an equal number of thread-slots as GPUs from the batch queue system. We can look into how to request multiple thread-slots per GPU (on the same node) to let us use multiple cores, but we hadn't done this before because we didn't know there was an advantage in doing so!

**Comment by bas-rustenburg** [comment]
As John notes, we can only specify GPU requests in a `gpus per cpu` way on our cluster because of poor GPU support in the LSF queue software. We, and users from other groups have requested multiple times that they implement this, but so far no luck with the sysadmins. Until then, I usually am stuck running on 1 cpu and 1 gpu.

**Comment by peastman** [comment]
There aren't a lot of parallel operations in the CUDA platform.  I think the only other one might be that `getState()` is a little faster, since it parallelizes the work of translating all the positions into the proper periodic box.

Shall I go ahead and merge this?  I expect multiple cores to be the more common case in practice, and the speedup when you have multiple cores seems to be larger than the slowdown when you don't.

**Comment by jchodera** [comment]
Seems fine to merge!

**Comment by bas-rustenburg** [comment]
I wasn't actually using `OPENMM_CPU_THREADS`. This actually did speed up my runs by a large amount. 

multiple threads 

```openmm af57bf9852d7d7de958a2c0db75213059a79e35f

System has 50442 particles

VerletIntegrator.step(nsteps)                                   :    2.863 s for      500 steps (   1.000 ps) :    5.726 ms / step :   1.000 x
VerletIntegrator                                                :    2.902 s for      500 steps (   1.000 ps) :    5.804 ms / step :   1.000 x
VerletIntegrator with updateParametersInContext                 :   21.098 s for      500 steps (   1.000 ps) :   42.195 ms / step :   7.270 x
LangevinIntegrator                                              :    2.910 s for      500 steps (   1.000 ps) :    5.821 ms / step :   1.003 x
LangevinIntegrator with updateParametersInContext               :   21.009 s for      500 steps (   1.000 ps) :   42.019 ms / step :   7.240 x
GHMCIntegratorIntegrator                                        :    5.283 s for      500 steps (   1.000 ps) :   10.567 ms / step :   1.821 x
GHMCIntegrator with updateParametersInContext                   :   27.696 s for      500 steps (   1.000 ps) :   55.391 ms / step :   9.544 x
```

one thread

```openmm af57bf9852d7d7de958a2c0db75213059a79e35f
System has 50442 particles
VerletIntegrator.step(nsteps)                                   :    2.851 s for      500 steps (   1.000 ps) :    5.701 ms / step :   1.000 x
VerletIntegrator                                                :    2.866 s for      500 steps (   1.000 ps) :    5.731 ms / step :   1.000 x
VerletIntegrator with updateParametersInContext                 :   11.322 s for      500 steps (   1.000 ps) :   22.643 ms / step :   3.951 x
LangevinIntegrator                                              :    2.878 s for      500 steps (   1.000 ps) :    5.756 ms / step :   1.004 x
LangevinIntegrator with updateParametersInContext               :   11.204 s for      500 steps (   1.000 ps) :   22.407 ms / step :   3.910 x
GHMCIntegratorIntegrator                                        :    5.014 s for      500 steps (   1.000 ps) :   10.029 ms / step :   1.750 x
GHMCIntegrator with updateParametersInContext                   :   17.395 s for      500 steps (   1.000 ps) :   34.789 ms / step :   6.070 x
```

**Comment by peastman** [comment]
Great, that's exactly what I was hoping to see!

**Pull request merged**
