### PR TITLE
Fix gradient of periodicdistance at 0

### PR DESCRIPTION
**Pull request by rmcgibbo**
cc #1191

### CODE REVIEW

**Comment by peastman** [comment]
I don't think that's actually guaranteed to work.  Depending on the implementation, inf*0 could be nan.  Instead of

```
periodicDistance_delta.x*periodicDistance_rinv*(periodicDistance_r2>0)
```

write

```
(periodicDistance_r2 > 0 ? periodicDistance_delta.x*periodicDistance_rinv : 0)
```

Could you give the test case a meaningful name?  Something like "testZeroPeriodicDistance".

**Comment by rmcgibbo** [comment]
Okay, done.

**Comment by rmcgibbo** [comment]
For CUDA and OpenCL, the test I added didn't actually fail with the old code -- it was giving a very very large force, but not NaN.

**Comment by peastman** [comment]
There was a travis failure that looks like a networking error or problem on Github:

```
Cloning into 'pandegroup/openmm'...
warning: Could not find remote branch add-test-for-1191 to clone.
fatal: Remote branch add-test-for-1191 not found in upstream origin
Unexpected end of command stream
```

Since only one of the four failed, I'm not going to worry about it.

**Pull request merged**
