### PR TITLE
Improved behaviour of LocalEnergyMinimizer

### PR DESCRIPTION
**Pull request by tristanic**
Significantly improves the behaviour of the minimizer in my tests as discussed in #2250, particularly on the GPU and in the presence of constraints. Only automatically falls back to the CPU if an inf or NaN force is encountered on the GPU. If a force greater than 2e9 kJ/mol/nm is encountered on the GPU **and** the minimization fails to converge to within constraint tolerance, an `OpenMMException` is raised suggesting to try the CPU platform, but advising to carefully check the model for the source of the problem first. It might be worth extending upon this to catch cases where there are no constraints and it fails to converge to any reasonable energy, and throw a meaningful exception. 

In my test case (the demo model built into ISOLDE - a MDFF simulation of 3io0 in implicit solvent, with all hydrogen bond lengths constrained) on the OpenCL platform it now repeatedly recovers from a random perturbation of all atoms up to +/-0.5A along each axis in about 3 seconds, and recovers from 1A perturbations (i.e. truly crazy geometry) about 4 times out of 5.

### CODE REVIEW

**Comment by peastman** [comment]
I don't think this is the right behavior.  For one thing, forces greater than 2e9 are the most common sign that clipping is present, *not* nan or inf.  For another, this is a very common situation.  Throwing an exception and telling the user to switch to the CPU platform makes things a lot harder on the user.  It also makes minimization much slower.  That requires the entire minimization to run on the CPU, whereas currently it uses the CPU for just a few steps until the clash is resolved, then goes back to the GPU.

I'm also nervous about your changes to the configuration parameters.  I tested this on various systems and tried to find values that worked reliably on across many cases.  Different values might work better on your particular system but be worse on other systems.  We shouldn't change them without thorough testing to make sure the new values are consistently better.

How about if we start by just making the single change

```c++
double k = 100/workingConstraintTol;
```

Then we can evaluate how things are working across lots of test cases and consider what further changes are appropriate.

**Comment by jchodera** [comment]
> Throwing an exception and telling the user to switch to the CPU platform makes things a lot harder on the user. 

What about having selectable behavior, controlled by an optional flag, with the default behavior as before?

**Comment by peastman** [comment]
Under what circumstances would you want the alternative behavior?

**Comment by tristanic** [comment]
That’s fine with me. My bias is towards not making it too easy for the user to shoot themselves in the foot - people have a tendency to expect minimization and MD to correct for all manner of sins, but the reality is that coordinates causing forces of those magnitudes are often going to be garbage-in, garbage-out whether or not they successfully minimize.

Anyway, I can accept that my needs (in particular, my need to avoid the CPU fall-back) are well outside mainstream use, and I can write my own custom implementation easily enough. 

 
 
Tristan Croll
Research Fellow
Cambridge Institute for Medical Research
University of Cambridge CB2 0XY

**Comment by jchodera** [comment]
> Under what circumstances would you want the alternative behavior?

My understanding was that @tristanic needed the alternate behavior, but I may have misunderstood.

**Comment by tristanic** [comment]
No need to go to that trouble if I’d be the only one to use it. I’m already calling minimize() exclusively through the C++ interface, so now I know where to look it’ll be a fairly trivial task to roll my own. 

 
 
Tristan Croll
Research Fellow
Cambridge Institute for Medical Research
University of Cambridge CB2 0XY

**Comment by tristanic** [comment]
I've gone ahead and implemented a custom minimizer in ISOLDE specific to its needs. For the official one, @peastman's approach is fine by me.

**Pull request closed without merging**
