### PR TITLE
OS X rpath

### LINKED ISSUE #1342: Problem with runtime linking on OS X El Capitan
The System Integrity Protection (SIP) feature in El Capitan prevents setting of all `DYLD_*` variables:

```
    % export DYLD_LIBRARY_PATH=foo   
    % env | grep DYLD_LIBRARY_PATH
    %
```

When I compile OpenMM from source (github) using a standard `ccmake`, `make install`, `make PythonInstall` workflow, OpenMM cannot load the CUDA plugin:

```
% ipython
'Error loading library /usr/local/openmm/lib/plugins/libOpenMMCUDA.dylib: dlopen(/usr/local/openmm/lib/plugins/libOpenMMCUDA.dylib, 9): Library not loaded: @rpath/libcufft.7.5.dylib\n  Referenced from: /usr/local/openmm/lib/plugins/libOpenMMCUDA.dylib\n  Reason: image not found',
 'Error loading library /usr/local/openmm/lib/plugins/libOpenMMRPMDCUDA.dylib: dlopen(/usr/local/openmm/lib/plugins/libOpenMMRPMDCUDA.dylib, 9): Library not loaded: @rpath/libOpenMMCUDA.dylib\n  Referenced from: /usr/local/openmm/lib/plugins/libOpenMMRPMDCUDA.dylib\n  Reason: image not found',
 'Error loading library /usr/local/openmm/lib/plugins/libOpenMMDrudeCUDA.dylib: dlopen(/usr/local/openmm/lib/plugins/libOpenMMDrudeCUDA.dylib, 9): Library not loaded: @rpath/libOpenMMCUDA.dylib\n  Referenced from: /usr/local/openmm/lib/plugins/libOpenMMDrudeCUDA.dylib\n  Reason: image not found',
 'Error loading library /usr/local/openmm/lib/plugins/libOpenMMAmoebaCUDA.dylib: dlopen(/usr/local/openmm/lib/plugins/libOpenMMAmoebaCUDA.dylib, 9): Library not loaded: @rpath/libOpenMMCUDA.dylib\n  Referenced from: /usr/local/openmm/lib/plugins/libOpenMMAmoebaCUDA.dylib\n  Reason: image not found',
 'Error loading library /usr/local/openmm/lib/plugins/libOpenMMCudaCompiler.dylib: dlopen(/usr/local/openmm/lib/plugins/libOpenMMCudaCompiler.dylib, 9): Library not loaded: @rpath/libnvrtc.7.5.dylib\n  Referenced from: /usr/local/openmm/lib/plugins/libOpenMMCudaCompiler.dylib\n  Reason: image not found'
```

Running `otool -L libOpenMMCUDA.dylib' gives:

```
libOpenMMCUDA.dylib:
    @rpath/libOpenMMCUDA.dylib (compatibility version 0.0.0, current version 0.0.0)
    @rpath/CUDA.framework/Versions/A/CUDA (compatibility version 1.1.0, current version 7.5.20)
    @rpath/libOpenMM.dylib (compatibility version 0.0.0, current version 0.0.0)
    /usr/local/cuda/lib/libcuda.dylib (compatibility version 1.1.0, current version 7.5.20)
    @rpath/libcufft.7.5.dylib (compatibility version 0.0.0, current version 7.5.20)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

Running `otool -l libOpenMMCUDA.dylib` gives:

```
... snipped ...

Load command 11
          cmd LC_LOAD_DYLIB
      cmdsize 64
         name /usr/local/cuda/lib/libcuda.dylib (offset 24)
   time stamp 2 Wed Dec 31 17:00:02 1969
      current version 7.5.20
compatibility version 1.1.0
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name @rpath/libcufft.7.5.dylib (offset 24)
   time stamp 2 Wed Dec 31 17:00:02 1969
      current version 7.5.20
compatibility version 0.0.0

... snipped ...
```

It looks like for some reason, the load path is baked in for `libcuda`, but not for `libcufft`. Because we can't set `DYLD_*` anymore, there doesn't seem to be any way to allow the linker to find `libcufft`.

Is there some linker / cmake magic to properly encode the load path into the library? I believe there is also a similar problem with `libOpenMMCudaCompiler.dylib` and `libnvrtc`.

### PR DESCRIPTION
**Pull request by rmcgibbo**
@jlmaccal can you see if this fixes #1342 for you? I don't have a CUDA mac to test on.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Perhaps bb51e02 will work better.

**Comment by jlmaccal** [comment]
```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: for: /Users/jlmaccal/Source/OpenMM/Build/libOpenMMCUDA.dylib (for architecture x86_64) option "-add_rpath /usr/local/cuda/lib" would duplicate path, file already has LC_RPATH for: /usr/local/cuda/lib
```

Strangely, running `otool -L` on in build directory does indeed show the correct `LC_RPATH` entry, while running it on the version installed to `/usr/local/openmm/lib/plugins` does not. This is after nuking `/usr/local/openmm`. It looks like it's being stripped off somehow.

Looking through my build directory, I find in ``platforms/cuda/sharedTarget/cmake_install.cmake`:
```
# Install script for directory: /Users/jlmaccal/Source/OpenMM/Source/platforms/cuda/sharedTarget

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local/openmm")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  EXECUTE_PROCESS(COMMAND install_name_tool -add_rpath /usr/local/cuda/lib /Users/jlmaccal/Source/OpenMM/Build/libOpenMMCUDA.dylib;)
endif()

if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/plugins" TYPE SHARED_LIBRARY FILES "/Users/jlmaccal/Source/OpenMM/Build/libOpenMMCUDA.dylib")
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/plugins/libOpenMMCUDA.dylib" AND
     NOT IS_SYMLINK "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/plugins/libOpenMMCUDA.dylib")
    execute_process(COMMAND "/usr/bin/install_name_tool"
      -id "@rpath/libOpenMMCUDA.dylib"
      -change "/Users/jlmaccal/Source/OpenMM/Build/libOpenMM.dylib" "@rpath/libOpenMM.dylib"
      "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/plugins/libOpenMMCUDA.dylib")
    execute_process(COMMAND /usr/bin/install_name_tool
      -delete_rpath "/usr/local/cuda/lib"
      "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/plugins/libOpenMMCUDA.dylib")
    if(CMAKE_INSTALL_DO_STRIP)
      execute_process(COMMAND "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip" "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/plugins/libOpenMMCUDA.dylib")
    endif()
  endif()
endif()
```

You can see towards the bottom that it's explicitly stripping `/usr/local/cuda/lib`. I don't know enough about CMAKE to figure out where this is coming from.

**Comment by rmcgibbo** [comment]
https://cmake.org/pipermail/cmake/2014-October/058901.html?

**Comment by jlmaccal** [comment]
FWIW, something like:
```
install_name_tool -change @rpath/libcufft.7.5.dylib /usr/local/cuda/lib/libcufft.7.5.dylib libOpenMMCUDA.dylib
```
seems to work. `libnvrtc.7.5.dylib` needs the same treatment for `libOpenMMCudaCompiler`.

**Comment by rmcgibbo** [comment]
This PR is obviously not the right way to solve this problem.

**Pull request closed without merging**
