### PR TITLE
Update `Topology` creation from CHARMM parsers and fix Amber prmtop parsing when %COMMENT sections are present

### PR DESCRIPTION
**Pull request by swails**
I still want to turn the prmtop that gave rise to this error into a test case.  Don't merge yet.

### CODE REVIEW

**Comment by swails** [comment]
Test case added.  This should be good to go.

**Comment by peastman** [comment]
Did you check in the case case?  I don't see it there.

**Comment by swails** [comment]
> Did you check in the case case? I don't see it there.

Assuming you mean test case, I modified an existing one by adding a `%COMMENT` section.  That is sufficient to guarantee coverage for this fix.

**Comment by swails** [comment]
See 0a0e3ba

**Comment by peastman** [comment]
Ok!

**Pull request merged**
