### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by peastman**
This fixes two errors.  One was a mistake in #1290.  The other was a memory leak.

### CODE REVIEW

**Comment by jchodera** [comment]
Does this also affect the openmm-core bugfix?

**Comment by peastman** [comment]
No.  The error was only in CUDA, not OpenCL.

**Comment by peastman** [comment]
I did, however, just find a different error in that patch.  It will fail if you run it in mixed precision mode.  Does FAH ever do that, or does it always run in single precision?

**Comment by jchodera** [comment]
As of 0.0.14, fah can run in mixed precision mode, so we will need to fix
this.

**Pull request merged**
