### PR TITLE
CustomNonbodedForce interaction group validation now occurs during kernel initialization

### PR DESCRIPTION
**Pull request by jchodera**
Addresses modifications to #1221 discussed therein.

### CODE REVIEW

**Comment by jchodera** [comment]
That's an [odd travis failure](https://travis-ci.org/pandegroup/openmm/jobs/88573213#L1321-L1328):
```
Generating docs for compound OpenMM::AmoebaAngleForce...
/Users/travis/build/pandegroup/openmm/openmmapi/src/AndersenThermostat.cpp:32:10: fatal error: 'openmm/AndersenThermostat.h' file not found
#include "openmm/AndersenThermostat.h"
         ^
1 error generated.
make[2]: *** [CMakeFiles/OpenMM.dir/openmmapi/src/AndersenThermostat.cpp.o] Error 1
make[1]: *** [CMakeFiles/OpenMM.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by jchodera** [comment]
OK, I'm super confused about the travis failures.

**Comment by jchodera** [comment]
These travis failures are odd:
* On `osx` (1532.3), the failure appears to be due to looking in the wrong directory for include files:
```
/Users/travis/build/pandegroup/openmm/openmmapi/src/AndersenThermostat.cpp:32:10: fatal error: 'openmm/AndersenThermostat.h' file not found
#include "openmm/AndersenThermostat.h"
         ^
1 error generated.
make[2]: *** [CMakeFiles/OpenMM.dir/openmmapi/src/AndersenThermostat.cpp.o] Error 1
make[1]: *** [CMakeFiles/OpenMM.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
* On 1532.4, .5, and .6, swig is not correctly installed because retrieving it from `anaconda.org` fails:
```
0.06s$ if [[ "$OPENCL" == "false" && "$CUDA" == "false" && "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://anaconda.org/anaconda/swig/3.0.2/download/linux-64/swig-3.0.2-0.tar.bz2; mkdir $HOME/swig; tar -xjvf swig-3.0.2-0.tar.bz2 -C $HOME/swig; export PATH=$HOME/swig/bin:$PATH; export SWIG_LIB=$HOME/swig/share/swig/3.0.2; fi
--2015-10-31 21:57:28--  https://anaconda.org/anaconda/swig/3.0.2/download/linux-64/swig-3.0.2-0.tar.bz2
Resolving anaconda.org (anaconda.org)... 54.235.223.122, 54.225.69.182
Connecting to anaconda.org (anaconda.org)|54.235.223.122|:443... connected.
HTTP request sent, awaiting response... 404 NOT FOUND
2015-10-31 21:57:28 ERROR 404: NOT FOUND.
```
In fact, that whole `anaconda` channel is empty now:
https://anaconda.org/anaconda/

It seems to have been renamed `anaconda-old`:
https://anaconda.org/anaconda-old

**Comment by rmcgibbo** [comment]
I'll add the newest version of swig to our omnia channel.

**Comment by jchodera** [comment]
> I'll add the newest version of swig to our omnia channel.

Thanks---great idea to insulate ourselves from whatever is going on over at continuum.

**Comment by rmcgibbo** [comment]
The OS X thing is quite odd.

**Comment by rmcgibbo** [comment]
@jchodera if you merge in the latest master HEAD, this should be able to pass.

**Comment by peastman** [comment]
I restarted the travis tests.

**Comment by rmcgibbo** [comment]
Does that pull in the latest master branch?

**Comment by peastman** [comment]
Yes.  It tests exactly what the master branch will be *after* the PR is merged.

**Comment by rmcgibbo** [comment]
Are you sure about that? It looks like it failed again downloading swig-3.0.2 https://travis-ci.org/pandegroup/openmm/jobs/88573214#L164, whereas I updated it in master to download 3.0.7 https://github.com/pandegroup/openmm/blob/master/.travis.yml#L101-L105

**Comment by jchodera** [comment]
Merged HEAD.  Sorry for the delay.

**Comment by jchodera** [comment]
Whoops; I guess that was unnecessary!  Thanks, @peastman.

**Comment by peastman** [comment]
All passed this time.

**Comment by jchodera** [comment]
Thanks!

**Pull request merged**
