### PR TITLE
Update OpenCL in Travis CI

### PR DESCRIPTION
**Pull request by rmcgibbo**
Perhaps this will fix the Travis CPU OpenCL bug. Or perhaps not.

### CODE REVIEW

**Comment by peastman** [comment]
I did also find one genuine error in the code.  This is the fix for it:

https://github.com/peastman/openmm/commit/2e53f824f87b7eb77eb371e6e6e36110ab64bf25

However, even after fixing it, the test still failed.  Try adding that fix to this PR.  Perhaps the combination of it plus the newer OpenCL will work.

**Comment by rmcgibbo** [comment]
Okay, I cherry-picked that in. From looking at the travis log, I suspect they don't have so many trusty VMs, because both the branches of the matrix that are supposed to run on trusty VMs are just waiting to start.

**Comment by rmcgibbo** [comment]
(https://www.traviscistatus.com/incidents/lpgbdfcmjhpk)

**Comment by peastman** [comment]
```
E: Unable to locate package 2
E: Couldn't find any package by regex '2:15.200-0ubuntu0.5'
```

**Comment by rmcgibbo** [comment]
oh, I probably shouldn't have removed the string `fglrx`. :-)

**Comment by rmcgibbo** [comment]
Okay, this is obviously still broken but in a different way, and I don't know how to fix it. Someone else can give it a shot if they want.

**Comment by peastman** [comment]
I'll mess around a bit and see what I can figure out.

**Comment by jchodera** [comment]
https://jenkins.choderalab.org/userContent/AMD-APP-SDKInstaller-v3.0.130.135-GA-linux64.tar.bz2

**Comment by peastman** [comment]
Thanks!  That should hopefully make it easier.

**Comment by peastman** [comment]
Closing, since #1360 did this.

**Pull request closed without merging**
