### PR TITLE
Backported fix for error in energy computation to 6.3

### PR DESCRIPTION
**Pull request by peastman**

### CODE REVIEW

**Comment by jchodera** [comment]
Thanks!  Will this be 6.3.1?

**Comment by peastman** [comment]
We still need to update the version number.  I think that's the only remaining change?

**Comment by jchodera** [comment]
Do we have a version-controlled `CHANGELOG.md` or release notes?

**Comment by peastman** [comment]
The release notes for each version are on simtk.org.

**Pull request merged**
