### PR TITLE
Added check for illegal particle index

### LINKED ISSUE #1525: Segfault in NonbondedForce::createExceptionsFromBonds()
This construct is illegal according to the API, but should throw an exception instead of a segfault:
```python
>>> from simtk import openmm
>>> force = openmm.NonbondedForce()
>>> force.createExceptionsFromBonds([(0, 1)], 1.0, 1.0)
Segmentation fault
```

### PR DESCRIPTION
**Pull request by peastman**
Fixes #1525.

### CODE REVIEW

**Comment by frank-stonybrook** [comment]
A OpenMM simulation restart error leads me here. I am curious what's the physical meaning of an illegal particle index error.

**Comment by peastman** [comment]
It means you passed a particle index to a method, but that index was either negative or greater than the number of particles.

**Comment by frank-stonybrook** [comment]
Thanks! What could be the reason for an incorrect particle index? The exact simulation has been restarted two times before without any problem.

**Comment by peastman** [comment]
This is a user error.  It means somewhere you called a method with an incorrect particle index.  From the exception you should be able to see exactly where you called it and figure out how the arguments were selected.

**Comment by frank-stonybrook** [comment]
Thanks Peter! Seems that it is related to the mpi4py module on the Frontera. I was able to restart the same simulation using our in-house cluster. Their mpi library drives us crazy.

**Pull request merged**
