### PR TITLE
Fixed bug in LennardJonesGenerator

### LINKED ISSUE #1844: LennardJonesGenerator.createForce() fails when NBFIX terms are identical to standard terms
From forcefield.py, line 2270:

```
        for i, atom in enumerate(data.atoms):
            atype = data.atomType[atom]
            values = tuple(self.ljTypes.getAtomParameters(atom, data))
            if values in typeMap and atype not in nbfixTypeSet:
                # Only non-NBFIX types can be compressed
                ljIndexList[i] = typeMap[values]
            else:
                typeMap[values] = numLjTypes
                ljIndexList[i] = numLjTypes
                numLjTypes += 1
                ljTypeList.append(atype)
        reverseMap = [0]*len(typeMap)
        for typeValue in typeMap:
            reverseMap[typeMap[typeValue]] = typeValue
```

This fails in the case where an NBFix term results in identical epsilon and sigma values to a standard term (which crops up multiple times in the CHARMM-36 ffxml from @jchodera). In each case where that happens, the existing type in typeMap is overwritten with the new one and everything falls apart (in my test case, numLjTypes reached 66, but only twenty-something entries remained in typeMap).

My solution:
```
        for i, atom in enumerate(data.atoms):
            atype = data.atomType[atom]
            values = tuple(self.ljTypes.getAtomParameters(atom, data))
            if values in typeMap and atype not in nbfixTypeSet:
                # Only non-NBFIX types can be compressed
                ljIndexList[i] = typeMap[values][0]
            else:
                if values not in typeMap:
                    typeMap[values] = []
                typeMap[values].append(numLjTypes)
                ljIndexList[i] = numLjTypes
                numLjTypes += 1
                ljTypeList.append(atype)
        reverseMap = [0]*numLjTypes
        for typeValue, type_list in typeMap.items():
            for t in type_list:
                reverseMap[t] = typeValue
```

This works, as far as I can tell so far. My simulation still crashes with
`Exception: All Forces must have identical exceptions`
... but I can see from reading back through previous discussions that this is a whole new kettle of fish, and that my attempts to work with the CHARMM ffxml may be somewhat premature.

### PR DESCRIPTION
**Pull request by peastman**
Fixes #1844 and #1914.

### CODE REVIEW

**Comment by jchodera** [comment]
I can verify that this fixes #1914!

**Comment by jchodera** [comment]
I'm not sure why Jenkins failed (login is required to see build logs, which makes it not particularly useful), but travis and AppVeyor both pass, so this should be good to merge.

**Comment by jchodera** [comment]
Thanks! I'll be able to finish up the ParmEd PR https://github.com/ParmEd/ParmEd/pull/895 now once the `dev` `openmm` build is complete.

**Comment by swails** [comment]
> I'm not sure why Jenkins failed (login is required to see build logs, which makes it not particularly useful), but travis and AppVeyor both pass, so this should be good to merge.

Jenkins anonymous read access restored.  I can create an account for people that need to make changes there.

**Comment by swails** [comment]
and the Jenkins tests seem to have failed because the CUDA driver needed to be reloaded (it since has, and everything should be working fine now)

**Pull request merged**
