### PR TITLE
Created CustomCVForce

### LINKED ISSUE #1796: Features to support metadynamics
I've been working to build a metadynamics integrator in OpenMM and am hitting a few snags.

Note, that I'm aware of the plumed plugin for OpenMM, but (a) it's to slow for us to use on GPUs, and (b) I want to define reaction coordinates in other ways, specifically  using MELD's energy function and other OpenMM custom forces.

The approach I'm taking is similar to that for the `AMDForceGroupIntegrator`. The goal is to treat the energy of a specified force group as a collective variable and to make that distribution uniform over a given range. I'm going to build the biasing potential on the CPU side, as it only needs to be updated occasionally. The modifications to the forces are straightforward and can easily be applied during integration. 

I think this should be straightforward to to implement, but I'm hitting a few issues.

## Issue 1: The energy is not correct.

Metadynamics works by applying a biasing potential. Using a custom integrator, it is possible to generate forces that correspond to this biased distribution, but it's not possible to modify the energy itself. The same issue occurs with the `AMD` integrators. The energies reported in `State` objects are not correct, although these could be corrected on the CPU-side after the fact. A more problematic issue is that the `MonteCarloBarostat` would be using the wrong energies.

I'm not sure of the best solution, but it might be nice if custom forces could access energies and forces from another force group. This would enable things like meta-D and AMD to be developed as forces rather than integrators and would enable the correct energies and forces to be reported. I'm not sure of the exact semantics of this, but probably these would be the energies and forces to that point in the calculation, so the order of forces would matter. 

This is just one possible solution, but it would be great if there was some mechanism where the forces and energies from one force could be modified in some way.

## Issue 2: There is no direct access to the derivative of tabulated functions

Generally, when we use tabulated functions, we use them as part of an energy expression and OpenMM automatically takes care of the correct derivative for us. However, in a custom integrator it is sometimes useful to have access to both the value from a tabulated function and its derivative, but it's currently not possible to access the derivative.

Of course, it's possible to define a tabulated function for both the energy and its derivative, but the derivatives don't actually match due to interpolation---the derivative is a second order spline in the first case and a third order spline in the second.

The proposed fix would be to make both the lookup table, `lookup(r)`, and its derivative `Dlookup(r)` available in custom expressions. For the 2D case, maybe the notation could be `D10lookup(r)` and `D01lookup(r)` or similar.

## Issue 3: Tabulated functions cannot be queried from python

It would be great if it was possible to lookup both the value and its derivative from tabulated functions directly from python. Of course one can extract the values and perform the spline interpolation, but this is tedious and potentially error-prone.

### PR DESCRIPTION
**Pull request by peastman**
Fixes #1796.

This is functional, but needs a lot of testing.  Please try it out and see how it works for you.  I'm not sure how fast it will be.  I might be able to further reduce the overhead, but that requires some good tests I can profile to see what happens in realistic use cases.

### CODE REVIEW

**Comment by peastman** [comment]
Here's what I'm seeing for the overhead using the DHFR benchmark.  Without the CustomCVForce, it gets 301 ns/day.  Adding a CustomCVForce that doesn't actually compute any CVs, it's 297 ns/day, so fairly negligible cost.  If I then add two CVs to it (each one is just the distance between two atoms), that goes down to 264 ns/day.  So about a 10% slowdown, which isn't bad.  I think that could be further improved by evaluating the CVs on a separate thread, but I really want to get feedback before I do more optimizing.

**Comment by jchodera** [comment]
Awesome!

Let me have our `openmm-dev` conda packaging framework build an `openmm 7.3` dev package for this branch. That'll make it easier for us to play with.

**Comment by jchodera** [comment]
OK, some of the `openmm` 7.3.0 dev packages are up here:
https://anaconda.org/omnia/openmm/files

**Comment by peastman** [comment]
Is anyone testing this?  If not, I'm going to go ahead and merge it.

**Comment by jlmaccal** [comment]
I haven't had a chance to play with this yet, but looking forward to it.

**Comment by jchodera** [comment]
I am! But I won't have results until Monday.

**Comment by peastman** [comment]
Shall I go ahead and merge this?

**Comment by jchodera** [comment]
Go for it---still behind in testing. I'll switch the `openmm` dev package back to building the master after you merge so that others can easily test too.

**Pull request merged**
