### PR TITLE
Add OpenCL on TravisCI

### PR DESCRIPTION
**Pull request by rmcgibbo**
With the OpenCL tests running on Travis, the test suite takes longer than 50 minutes (the timeout), so I changed the `ctest` invocation to run the tests in a random order with a ~~30~~ 40 minute timeout. Across multiple invocations, hopefully this will get reasonable coverage.

### CODE REVIEW

**Comment by peastman** [comment]
What OpenCL implementation is it using?

It looks like there were a number of failures in OpenCL test cases.  But since you told it failures were OK, you'll never know that unless you actually pull up the build log for that VM.  Which kind of limits the value of this.

**Comment by rmcgibbo** [comment]
Yes, obviously it has limited value, but it seems like a small improvement over the current situation. Presumably it's using whatever CPU OpenCL is provided by `fglrx`. If you want to turn off the `allowed_failures` -- go for it. None of this is set in stone.

**Comment by jchodera** [comment]
What if we install both CUDA and the AMD APP SDK using a scheme similar to [this](https://github.com/FoldingAtHome/docker-core-linux-build-environment/blob/master/Dockerfile#L11-L22)?  That way, we can at least make sure the CUDA and OpenCL platforms *compile* correctly, even if we can't run the CUDA or OpenCL tests.

**Comment by rmcgibbo** [comment]
The OpenCL is compiling and running just fine with this PR. That could work for CUDA -- I'm not sure. I recommend you open another PR if you want to try.

**Comment by peastman** [comment]
Are you sure it's using fglrx?  It may be using the Mesa OpenCL implementation, which is still buggy and incomplete.

> The OpenCL is compiling and running just fine with this PR.

It's not running fine.  There were four failures in OpenCL tests, and that's not even having run the full test suite.

**Comment by rmcgibbo** [comment]
I don't have any secret information beyond what you have, Peter. I assume that `sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers`, installs `fglrx, but I may be wrong. I copied that line from the Travis-CI configuration from boost::compute (https://github.com/boostorg/compute), which they appear to be using succesfully.

**Comment by rmcgibbo** [comment]
Do you know if there's something similar to the CUDA `deviceQuery` program that's included with the CUDA samples for OpenCL? We could run that at the top of the test script. From looking through the boost::compute issues, I see a link to https://travis-ci.org/ddemidov/vexcl/jobs/18265418#L280-L300 which might be useful to add.

**Comment by rmcgibbo** [comment]
I added https://github.com/rmcgibbo/openmm/blob/cl/platforms/opencl/tests/TestOpenCLDeviceQuery.cpp that just prints to stdout, but that might not be the best way to organize it.

**Comment by rmcgibbo** [comment]
```
OpenCL devices:
OpenCL Platform 0, Device 0: "AMD Opteron(tm) Processor 6376                 "
    CL_PLATFORM_NAME                 = AMD Accelerated Parallel Processing
    CL_PLATFORM_NAME                 = Advanced Micro Devices, Inc.
    CL_DEVICE_VENDOR                 = AuthenticAMD
    CL_DEVICE_VERSION                = OpenCL 1.2 AMD-APP (923.1)
    CL_DEVICE_MAX_COMPUTE_UNITS      = 32
    CL_DEVICE_HOST_UNIFIED_MEMORY    = 1
    CL_DEVICE_GLOBAL_MEM_SIZE        = 3221225472
    CL_DEVICE_LOCAL_MEM_SIZE         = 32768
    CL_DEVICE_MAX_MEM_ALLOC_SIZE     = 2147483648
    CL_DEVICE_ADDRESS_BITS           = 64
    CL_DEVICE_MAX_CLOCK_FREQUENCY    = 2300
    CL_DEVICE_EXTENSIONS             = cl_amd_device_attribute_query 
        cl_amd_fp64 cl_amd_media_ops cl_amd_popcnt cl_amd_printf cl_amd_vec3 
        cl_ext_device_fission cl_khr_byte_addressable_store cl_khr_fp64 
        cl_khr_gl_sharing cl_khr_global_int32_base_atomics 
        cl_khr_global_int32_extended_atomics cl_khr_int64_base_atomics 
        cl_khr_int64_extended_atomics cl_khr_local_int32_base_atomics 
        cl_khr_local_int32_extended_atomics 
```

**Comment by rmcgibbo** [comment]
grr. git is weird.

**Pull request closed without merging**
