### PR TITLE
Removed code that disabled OpenCL on OS X packaging.

### PR DESCRIPTION
**Pull request by jchodera**
Testing this now.

### CODE REVIEW

**Comment by peastman** [comment]
Is this ready to merge?

**Comment by jchodera** [comment]
There's a whole queue of builds we're waiting on.

**Comment by jchodera** [comment]
We only have one `osx` build machine active right now (an older Mac Mini).  Will hopefully add more in the next month.

**Comment by jchodera** [comment]
Running now.

**Comment by jchodera** [comment]
Seems to work:
https://jenkins.choderalab.org/job/package-openmm-osx/ws/packaging/

**Comment by jchodera** [comment]
Merge away.

**Comment by peastman** [comment]
Thanks!

**Pull request merged**
