### PR TITLE
Add a set of unit tests for unit handling in the core API.

### PR DESCRIPTION
**Pull request by swails**
This is the start of what I promised in #1031 

So far it just has the basic classes, but I still want to add:

- [x] `CMAPForce`
- [x] custom forces
- [x] integrators
- [x] Amoeba forces

### CODE REVIEW

**Comment by swails** [comment]
@rmcgibbo -- can you take a look at the test failure here?  For some reason it seems like `CustomManyParticleForce` isn't getting `strip_units` applied to all of the arguments correctly...

**Comment by rmcgibbo** [comment]
I see the bug. Good spot. Thanks for adding these tests.

**Comment by swails** [comment]
Awesome, thanks.  I should hopefully be almost done with this.

**Comment by rmcgibbo** [comment]
Okay, fixed a PR into this branch. I think I also fixed some memory leaks.

**Comment by swails** [comment]
Got it.  I thought you filed the PR to the main repo, sorry.  I'll hopefully finish up this PR sometime this week with the remaining integrator classes, tabulated functions, and amoeba plugin.

**Comment by rmcgibbo** [comment]
Great. It seems to have rescued the tests.

**Comment by swails** [comment]
There are *so many* amoeba forces :(

**Comment by peastman** [comment]
I know. :(  Be grateful you didn't have to write any of them!

**Comment by swails** [comment]
@peastman -- can you look at why I'm having such horrible problems with `AmoebaOutOfPlaneBendForce`?  I've been working at this for hours and I'm completely stuck.

In particular, look at a0f99fc -- where I change the return values for the expansion coefficient return values (`AmoebaOutOfPlaneBendForce.getOutOfPlaneBendCubic`, etc.), but that is for some reason not making its way to the `openmm.py` file, so the tests are failing.  I'm completely at a loss, because I've been doing this successfully for several other classes before this.

I have *no* idea what's going wrong here, and I'm getting a little lost going through `swigInputBuilder.py`.  Any help would be appreciated.

**Comment by peastman** [comment]
Try deleting the "python" and "wrappers" directories inside your build directory.  Occasionally those somehow get out of sync, such that CMake doesn't regenerate files when it ought to.

**Comment by swails** [comment]
> Try deleting the "python" and "wrappers" directories inside your build directory. Occasionally those somehow get out of sync, such that CMake doesn't regenerate files when it ought to.

Did that awhile ago.  No dice.  The irritating thing is that in the printout, it says it's applying the units that I added, but then the openmm.py script doesn't do it.

And this is breaking the Travis build, so it is definitely not a result of leftover files: https://travis-ci.org/pandegroup/openmm/jobs/81072615#L4638-L4651

**Comment by swails** [comment]
You can see here where the methods I added *say* they're getting returned with units: https://travis-ci.org/pandegroup/openmm/jobs/81072615#L2352-L2355

but that's a lie.

**Comment by swails** [comment]
OK, I found out how to fix this.  I had to change the call signature for `getGlobalOutOfPlaneBendCubic` from `(void)` to `()` in the header...

**Comment by swails** [comment]
@rmcgibbo -- another incarnation of #1135 popped up with `AmoebaTorsionTorsionForce`.  The current test here will fail because `vector<vector<vector<double> > >` isn't currently handled by `stripUnits`.  Any chance you can take care of this one, too?

**Comment by swails** [comment]
OK.  I'm done with this.  It's missing a few things, but my patience for this is long gone and it has things I think need to be added sooner rather than later.

It fixes a *lot* of return units and several small bugs (including the ones listed in #1136) and adds a nice set of tests for unit handling in almost every class in OpenMM (the process of doing this caught a number of issues).

There are some things notably missing from this PR, but that I'm not going to address here:

- Discrete*DFunction and Continuous*DFunction unit handling
- RPMDIntegrator
- RPMDMonteCarloBarostat

But I think most of the rest is covered.  I'm going to merge master and rebase.  After that, pending the test results and any code review comments, this is ready to merge.

**Comment by swails** [comment]
Rebase done.

**Comment by peastman** [comment]
Thanks!  That's fantastic.

**Pull request merged**
