### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by peastman**
Fixes a bug introduced by #2014.

### CODE REVIEW

**Comment by jchodera** [comment]
All tests pass! But do you want to add a test that would have caught this issue? I'm surprised it slipped by.

**Comment by peastman** [comment]
That's because jenkins is down, so CUDA tests aren't getting run.  @swails any idea what's happened to it?

**Comment by swails** [comment]
Sorry about missing this!  For the future, assume I won't see mentions in GH at all, or at least not for awhile.  Please feel free to email me directly -- I'll get those and respond.

The hard drive where all the Jenkins files were hosted crapped the bed a few months ago.  I brought it back up, but everything that was set up there was wiped away.

Fortunately the script in ``devtools/ci/jenkins/install.sh`` contains the vast majority of the work that went into getting it to work.  So @peastman, if you wanted to get Jenkins back up and working again on this repository I'd be happy to help.  I'll need another API key from an account with write permission on this repo so it can post comments on PRs and statuses.

Email me if you want to do this and we can get it back up pretty quickly.

**Comment by swails** [comment]
Scratch that, @peastman -- I found the last API key you sent me and just reused that.  I need to reboot my computer following a driver update (that's why all the CUDA and OpenCL tests are crapping out in the meaningless PR I just opened), but after that the CUDA and OpenCL tests should be back.

**Comment by peastman** [comment]
Wonderful, thanks!

**Pull request merged**
