### PR TITLE
Fixed compilation error on travis

### PR DESCRIPTION
**Pull request by peastman**
See #1841.

### CODE REVIEW

**Comment by peastman** [comment]
It's still failing.  How do I tell if it's actually installing it?  There's no mention of mesa anywhere in the build log.

**Comment by jchodera** [comment]
Hm, I don't see anything in the raw logs about `apt-get`ting those packages either. 

There's a [mysterious line](https://travis-ci.org/pandegroup/openmm/jobs/245959410#L618) in the output that says:
```
Could not locate requirements.txt. Override the install: key in your .travis.yml to install dependencies.
```

**Comment by jchodera** [comment]
The failing travis branches have `sudo: required`, so we can just install things directly with `sudo apt-get install -y libgl1-mesa-dev` in those branches in [here](https://github.com/peastman/openmm/blob/49c90bb3d35d341a9b9b4242c771fad8143a66b4/.travis.yml#L121-L132). Maybe that will work?

**Comment by Lnaden** [comment]
Do you think this change will need to be made on `conda-recipes` as well?

**Comment by jchodera** [comment]
We use our own docker image there, so this shouldn't be necessary.

**Pull request merged**
