### PR TITLE
Fix OpenCL on AppVeyor

### PR DESCRIPTION
**Pull request by peastman**

### CODE REVIEW

**Comment by peastman** [comment]
I've fixed the OpenCL problem, but appveyor has somehow gotten *really* slow.  It runs for an hour, then times out having gotten less than half way through compiling.  It used to be a lot faster than that.  Any idea what's going on?

**Comment by peastman** [comment]
I'm going to merge this, since it at least fixes the OpenCL problem.  But we still have more issues to deal with before AppVeyor will be functional.

**Comment by jchodera** [comment]
I wonder if using a build cache would help?
https://www.appveyor.com/docs/build-cache

**Comment by peastman** [comment]
We already are.

**Comment by jchodera** [comment]
We might ask here for help/ideas:
http://help.appveyor.com/discussions/problems

Others seem to have good feedback:
http://help.appveyor.com/discussions/problems/2548-slow-build-tends-fail-because-of-test-timeout

**Pull request merged**
