### PR TITLE
Build without doxygen

### PR DESCRIPTION
**Pull request by mpharrigan**
Cmake would refuse to continue without doxygen.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
doxygen is required for building the swig wrappers tho.

**Comment by mpharrigan** [comment]
If you don't want swig wrappers

**Comment by rmcgibbo** [comment]
what happens w/ this PR if you don't have doxygen but enable the
OPENMM_BUILD_PYTHON_WRAPPERS option?

**Comment by mpharrigan** [comment]
You're right. That's the source of the error:
```
  Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/CMake/share/cmake-3.2/Modules/FindDoxygen.cmake:107 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  wrappers/python/CMakeLists.txt:122 (find_package)
```

The proposed change in this PR does nothing

**Pull request closed without merging**
