### PR TITLE
Debugging OpenCL errors on travis

### PR DESCRIPTION
**Pull request by peastman**
This isn't meant to be merged.  I'm just using this PR as a way to run debugging code on travis to try to figure out what's causing the errors.

### CODE REVIEW

**Comment by swails** [comment]
This would be pretty awesome to merge though :)

**Comment by peastman** [comment]
Well, I found one problem and now it isn't segfaulting anymore.  Unfortunately it's still giving the wrong answer...

**Comment by peastman** [comment]
This really looks to me like a bug in the OpenCL implementation.  See https://github.com/peastman/openmm/blob/debugcl/platforms/opencl/src/kernels/customManyParticle.cl.  Line 270 never gets executed for two atoms (464 and 465).  You can see that from the log at https://travis-ci.org/pandegroup/openmm/jobs/104710149.  There's no output for those two atoms from the printf at line 269.  On the other hand, the printf at the start of the loop (line 185) does produce output for them.  There's also a printf in the middle of the loop (line 259) that only gets executed for atom 464, and it produces the correct output.

I've been trying to figure out what version of AMD's OpenCL we're using.  Here's the command we use to install it:

```
sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers
```

Is 8.960 the version number?  If so, that's a very old version.  Perhaps we need to upgrade?

**Comment by peastman** [comment]
Ok, what did I do wrong?  Here's the code I added:

```
  - if [[ "$OPENCL" == "true" ]]; then
      wget https://jenkins.choderalab.org/userContent/AMD-APP-SDKInstaller-v3.0.130.135-GA-linux64.tar.bz2;
      tar -xjf AMD-APP-SDK*.tar.bz2;
      AMDAPPSDK=${HOME}/AMDAPPSDK;
      export OPENCL_VENDOR_PATH=${AMDAPPSDK}/etc/OpenCL/vendors;
      mkdir -p ${OPENCL_VENDOR_PATH};
      sh AMD-APP-SDK*.sh --tar -xf -C ${AMDAPPSDK};
      echo libamdocl64.so > ${OPENCL_VENDOR_PATH}/amdocl64.icd;
      export LD_LIBRARY_PATH=${AMDAPPSDK}/lib/x86_64:${LD_LIBRARY_PATH};
      chmod +x ${AMDAPPSDK}/bin/x86_64/clinfo;
      ${AMDAPPSDK}/bin/x86_64/clinfo;
    fi
```

And here's the log: https://api.travis-ci.org/jobs/108140361/log.txt?deansi=true.  You can see where it executed the first line of that block and (successfully, as far as I can tell) downloaded the file.  But there's no indication it executed any of the rest of that block.

**Comment by swails** [comment]
> But there's no indication it executed any of the rest of that block.

What do you mean?  Isn't the output of clinfo clearly there?  What were you expecting to see that you didn't?

**Comment by jchodera** [comment]
Travis expects a single line of `bash` shell script per YAML line, and does weird things to process multi-line things, which makes `if` statements crazy hard to debug:
https://github.com/travis-ci/travis-ci/issues/497

**Comment by jchodera** [comment]
I'd also add the `--quiet` line to `wget` to suppress the `####...` output.

**Comment by jchodera** [comment]
Whoa, it looks like it actually printed out the output from `${AMDAPPSDK}/bin/x86_64/clinfo` in that multi-line `if` block, though!

**Comment by peastman** [comment]
Well, I just copied most of that block from the repository you referenced.  I was expecting the installer to produce some output, but maybe one of those command line flags told it not to.  I now think the problem is that CMake isn't locating it, so I'm working on that now.

**Comment by swails** [comment]
You can add the -v flag to the tar command to get a verbose dump of the tarball contents.  That should at least produce some output you can check against.  But it's not obvious to me that the commands between the wget and the clinfo actually produce any output...

**Comment by peastman** [comment]
Ok!  I have it successfully installing the newer OpenCL.  And... the test still fails.

Sigh.

**Comment by jchodera** [comment]
What if I have the platform tests packaged (or at least that test) packaged into the  openmm-dev conda package. That would make it trivial to try on any platform we can install conda.

**Comment by jchodera** [comment]
Still, progress!

Let's find another machine to reproduce the bug on...

**Comment by swails** [comment]
I was able to repro on a Vagrant machine I built:

```
vagrant@precise64:~/openmm$ ./TestOpenCLCustomManyParticleForce mixed 
Segmentation fault
vagrant@precise64:~/openmm$ ./TestOpenCLCustomManyParticleForce single
Segmentation fault
```

I'll check out this branch to test it out.

**Comment by swails** [comment]
Still fails on this branch -- log file here: https://www.dropbox.com/s/x3g06h3auuaptdf/multiparticle_force_single.log?dl=0

Anything you want me to do or try?  Has anyone been able to repro this before?

**Comment by swails** [comment]
If it'll help, I can give @peastman access to this machine until it goes down on Friday.

**Comment by rmcgibbo** [comment]
What OpenCL driver are you using?

**Comment by swails** [comment]
```
vagrant@precise64:~/openmm$ ./TestOpenCLDeviceQuery 
OpenCL devices:

OpenCLPlatformIndex 0, OpenCLDeviceIndex 0: "AMD FX(tm)-6100 Six-Core Processor             "
    CL_PLATFORM_NAME                 = AMD Accelerated Parallel Processing
    CL_PLATFORM_VENDOR               = Advanced Micro Devices, Inc.
    CL_DEVICE_VENDOR                 = AuthenticAMD
    CL_DEVICE_VERSION                = OpenCL 1.2 AMD-APP (923.1)
    CL_DEVICE_TYPE                   = CL_DEVICE_TYPE_CPU
    CL_DEVICE_MAX_COMPUTE_UNITS      = 2
    CL_DEVICE_MAX_WORK_ITEM_SIZES    = [1024, 1024, 1024]
    CL_DEVICE_HOST_UNIFIED_MEMORY    = 1
    CL_DEVICE_GLOBAL_MEM_SIZE        = 4147060736
    CL_DEVICE_LOCAL_MEM_SIZE         = 32768
    CL_DEVICE_MAX_MEM_ALLOC_SIZE     = 2147483648
    CL_DEVICE_ADDRESS_BITS           = 64
    CL_DEVICE_MAX_CLOCK_FREQUENCY    = 3311
    processingElementsPerComputeUnit = 1
    estimatedSpeed                   = 6622
    CL_DEVICE_EXTENSIONS             = cl_amd_device_attribute_query 
        cl_amd_fp64 cl_amd_media_ops cl_amd_popcnt cl_amd_printf cl_amd_vec3 
        cl_ext_device_fission cl_khr_byte_addressable_store cl_khr_fp64 
        cl_khr_gl_sharing cl_khr_global_int32_base_atomics 
        cl_khr_global_int32_extended_atomics cl_khr_int64_base_atomics 
        cl_khr_int64_extended_atomics cl_khr_local_int32_base_atomics 
        cl_khr_local_int32_extended_atomics 
```

Does this have the information you're looking for?  The output looks quite similar to what Travis prints.  I'm running the full test suite now, but the first couple tests have already passed.  So I suspect it's a reliable repro VM for this issue.

**Comment by peastman** [comment]
I finally found a way to reproduce this locally!  It seems to be related to the number of threads.  If I tell it to pretend my CPU only has one core, then I can reproduce it.  And after a lot of experimenting, I found that if I add a barrier at a particular place, the error goes away.  *I have no idea why that should make a difference*.  I'm still inclined to think it's a compiler bug, and this is just working around it.  But for now, I think that's good enough.  So I'm going to clean up the debugging code, rebase to get a cleaner version history, and then merge it.

**Comment by swails** [comment]
How much does the barrier slow stuff down?

**Comment by peastman** [comment]
Completely negligible.  It's at the end of an outermost loop.

**Comment by swails** [comment]
:). Puzzling. 

Awesome work!

**Comment by swails** [comment]
OK!  This is done!  The failure is the same error I was seeing on my Mac.  So I think this is ready to merge, unless you want me to try my hand at fixing the errors.

**Comment by swails** [comment]
Sorry, last post was meant for a different repo... :-[

**Pull request merged**
