### PR TITLE
Fix OpenCL Nonbonded Force on certain CPU devices

### PR DESCRIPTION
**Pull request by rmcgibbo**
Fixes https://github.com/pandegroup/openmm/issues/1079#issuecomment-136193271

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Note that this compilation fix leads to an error in `TestOpenCLNonbondedForce` in the dispersion correction.

```
vagrant@precise64:~/openmm/build$ ./TestOpenCLNonbondedForce 
exception: Assertion failure at TestOpenCLNonbondedForce.cpp:721.  Expected -1304.2, found -1304
```

The test machine is an Ubuntu 12.04 VM running inside a Mac Mini. The VM has the AMD APP SDK, and the OpenCL device is the CPU (OpenCL info: https://gist.github.com/rmcgibbo/7a20862e5f34dc3bc806)

**Comment by rmcgibbo** [comment]
Actually, there are quite a bit more OpenCL test errors.

**Comment by swails** [comment]
Maybe this isn't the right fix?  I *think* `MAX_CUTOFF` and `CUTOFF` can be different on account of different force groups can have different nonbonded cutoffs for their nonbonded forces.

**Comment by rmcgibbo** [comment]
No, it's the same change as https://github.com/pandegroup/openmm/commit/8ae2eba560313a211dab115a3ef73807ff911177, which is a fix for the previous PR that let different nonbonded force kernels have different cutoffs.

**Comment by swails** [comment]
Ah, OK.

**Comment by peastman** [comment]
I'm going to merge this since, whatever the other problems are caused by, this fix is clearly needed.

**Comment by jchodera** [comment]
Good catch!

**Pull request merged**
